-- arkher/actions2.lua — terrain/model/char/anim/cut/ui/mat.
local A = _G.ARKHER.ACTIONS
local H = _G.ARKHER.actionhelp
-- ===== terrain =====
local T = function() return H.E().systems.terrain end
A.terrain_draw = function(c, a) H.E().mode.set("TerrainDraw", a) end
A.terrain_sculpt = function(c, a) H.E().mode.set("TerrainSculpt", a) end
A.terrain_brush = function(c, a) T().brush(a.op, a) end
A.terrain_erode = function(c, a) T().erode(a) end
A.terrain_paint = function(c, a) H.E().mode.set("TerrainPaint", a) end
A.terrain_replace = function(c, a) T().replace(a) end
A.terrain_generate = function(c, a) T().generate(a) end
A.terrain_heightmap = function(c, a) T().heightmap(a) end
A.terrain_stamp = function(c, a) T().stamp(a) end
A.terrain_caves = function(c, a) T().caves(a) end
A.terrain_rivers = function(c, a) T().rivers(a) end
A.terrain_water = function(c, a) T().water(a.op, a) end
A.terrain_region = function(c, a) H.E().mode.set("TerrainRegion", a) end
A.terrain_copy = function() T().copyRegion() end
A.terrain_paste = function() T().pasteRegion() end
A.terrain_clear = function() T().clearAll() end
A.terrain_fillall = function(c, a) T().fillAll(a) end
A.terrain_readvox = function() T().readVox() end
A.terrain_preview = function() T().preview() end
A.terrain_export = function() T().export() end
A.terrain_import = function(c, a) T().import(a) end
-- ===== model =====
local M = function() return H.E().systems.model end
A.model_extrude = function(c, a) M().extrude(a) end
A.model_bevel = function(c, a) M().bevel(a) end
A.model_inset = function(c, a) M().inset(a) end
A.model_bridge = function(c, a) M().bridge(a) end
A.model_merge = function(c, a) M().merge(a) end
A.model_split = function(c, a) M().split(a) end
A.model_subdiv = function() M().subdiv() end
A.model_weld = function() M().weld() end
A.model_boolean = function(c, a) M().boolean(a.op) end
A.model_separate = function() M().separate() end
A.model_deform = function(c, a) M().deform(a.kind, a) end
A.model_array = function(c, a) M().array(a) end
A.model_mirror = function(c, a) M().mirror(a) end
A.model_normals = function() M().normals() end
A.model_smoothshade = function() M().smoothshade() end
A.model_decimate = function(c, a) M().decimate(a) end
A.model_remesh = function(c, a) M().remesh(a) end
A.model_bake = function() M().bake() end
A.model_freeze = function() M().freeze() end
A.model_resetxf = function() M().resetxf() end
A.model_cleanup = function() M().cleanup() end
A.model_export = function() M().export() end
A.model_import = function(c, a) M().import(a) end
-- ===== char =====
local C = function() return H.E().systems.char end
A.char_new = function(c, a) C().new(a) end
A.char_fromnpc = function() C().fromNPC(H.first()) end
A.char_posereset = function() C().poseReset(H.first()) end
A.char_savepreset = function() C().savePreset(H.first()) end
A.char_ik = function(c, a) H.E().mode.set("CharIK", a) end
A.char_ragdoll = function() C().ragdoll(H.first()) end
A.char_respawn = function() C().respawn(H.first()) end
A.char_kill = function() C().kill(H.first()) end
A.char_fullreset = function() C().fullReset(H.first()) end
A.char_export = function() C().export(H.first()) end
A.char_import = function(c, a) C().import(a) end
-- ===== anim =====
local N = function() return H.E().systems.anim end
A.anim_new = function(c, a) N().new(H.first(), a) end
A.anim_play = function() N().play() end
A.anim_pause = function() N().pause() end
A.anim_stop = function() N().stop() end
A.anim_loop = function() N().toggleLoop() end
A.anim_addkey = function(c, a) N().addKey(a) end
A.anim_delkey = function() N().delKey() end
A.anim_navkey = function(c, a) N().navKey(a.dir) end
A.anim_copykeys = function() N().copyKeys() end
A.anim_pastekeys = function() N().pasteKeys() end
A.anim_keyall = function() N().keyAll() end
A.anim_smooth = function() N().smooth() end
A.anim_mirror = function() N().mirror() end
A.anim_reverse = function() N().reverse() end
A.anim_quantize = function() N().quantize() end
A.anim_additive = function() N().additive() end
A.anim_export = function() N().export() end
A.anim_import = function(c, a) N().import(a) end
A.anim_bake = function() N().bake() end
A.anim_audit = function() N().audit() end
-- ===== cutscene =====
local K = function() return H.E().systems.cut end
A.cut_new = function(c, a) K().new(a) end
A.cut_play = function() K().play() end
A.cut_pause = function() K().pause() end
A.cut_stop = function() K().stop() end
A.cut_addshot = function() K().addShot() end
A.cut_dupshot = function() K().dupShot() end
A.cut_camadd = function() K().camAdd() end
A.cut_camgoto = function() K().camGoto() end
A.cut_recordcam = function() K().recordCam() end
A.cut_preview = function() K().preview() end
A.cut_export = function() K().export() end
A.cut_import = function(c, a) K().import(a) end
-- ===== ui tools =====
local G = function() return H.E().systems.uitools end
A.ui_align = function() G().align(H.sel()) end
A.ui_distribute = function() G().distribute(H.sel()) end
A.ui_showhide = function() G().showhide(H.sel()) end
A.ui_modal = function() G().modal(H.first()) end
A.ui_preview = function() G().preview(H.first()) end
A.ui_a11y = function() G().a11y(H.first()) end
A.ui_export = function() G().export(H.first()) end
A.ui_import = function(c, a) G().import(a) end
-- ===== materials =====
local MT = function() return H.E().systems.mat end
A.mat_apply = function() MT().apply(H.sel()) end
A.mat_fill = function() MT().fill(H.sel()) end
A.mat_surfaceapp = function() MT().surfaceApp(H.sel()) end
A.mat_delete = function() MT().deleteCustom() end
A.mat_import = function(c, a) MT().import(a) end
A.mat_export = function() MT().export() end
A.mat_audit = function() MT().audit() end
A.mat_copyprop = function() MT().copyProp(H.first()) end
A.mat_pasteprop = function() MT().pasteProp(H.sel()) end
A.mat_cleanunused = function() MT().cleanUnused() end
return true
