-- arkher/registry/tabs06.lua — Environment, Assets, Plugins, Settings, Help (5x40).
local T = {}
T[#T + 1] = { id = "ENVIRONMENT", label = "Environment", icon = "environment",
  groups = { { id = "weather", label = "Weather" }, { id = "render", label = "Render" },
    { id = "post", label = "Post" }, { id = "volume", label = "Volumes" }, { id = "presets", label = "Presets" } },
  commands = {
    { id = "env_rain", label = "Rain", icon = "cloud", tip = "Rain system controls.", group = "weather", act = "shell_panel", arg = { name = "env_rain" } },
    { id = "env_snow", label = "Snow", icon = "cloud", tip = "Snow system controls.", group = "weather", act = "shell_panel", arg = { name = "env_snow" } },
    { id = "env_storm", label = "Storm", icon = "cloud", tip = "Storm: rain+lightning+wind.", group = "weather", act = "shell_panel", arg = { name = "env_storm" } },
    { id = "env_fogdyn", label = "Dyn Fog", icon = "cloud", tip = "Animated fog density.", group = "weather", act = "shell_panel", arg = { name = "env_fogdyn" } },
    { id = "env_wind", label = "Wind", icon = "cloud", tip = "GlobalWind editor.", group = "weather", act = "shell_panel", arg = { name = "world_wind" } },
    { id = "env_clouds", label = "Clouds", icon = "cloud", tip = "Clouds object editor.", group = "weather", act = "shell_panel", arg = { name = "env_clouds" } },
    { id = "env_seasons", label = "Seasons", icon = "repfirst", tip = "Season tint presets.", group = "weather", act = "shell_panel", arg = { name = "env_seasons" } },
    { id = "env_cycle", label = "Wx Cycle", icon = "rotate", tip = "Weather cycle scheduler.", group = "weather", act = "shell_panel", arg = { name = "env_cycle" } },
    { id = "env_tech", label = "Technology", icon = "render", tip = "Render technology selector.", group = "render", act = "shell_panel", arg = { name = "light_tech" } },
    { id = "env_quality", label = "Quality", icon = "scaleI", tip = "Quality level controls.", group = "render", act = "shell_panel", arg = { name = "perf_quality" } },
    { id = "env_res", label = "Resolution", icon = "expand", tip = "Render resolution scale (honest limits).", group = "render", act = "shell_panel", arg = { name = "env_res" } },
    { id = "env_aa", label = "AA", icon = "check", tip = "Anti-aliasing info + best settings.", group = "render", act = "shell_panel", arg = { name = "env_aa" } },
    { id = "env_shadows", label = "Shadows", icon = "bulb", tip = "Shadow controls.", group = "render", act = "shell_panel", arg = { name = "perf_shadows" } },
    { id = "env_reflect", label = "Reflections", icon = "bulb", tip = "Reflection controls.", group = "render", act = "shell_panel", arg = { name = "env_reflect" } },
    { id = "env_bloom", label = "Bloom", icon = "effects", tip = "Bloom editor.", group = "post", act = "shell_panel", arg = { name = "light_bloom" } },
    { id = "env_dof", label = "DoF", icon = "search", tip = "Depth of field editor.", group = "post", act = "shell_panel", arg = { name = "light_dof" } },
    { id = "env_colorgrade", label = "ColorGrade", icon = "square", tip = "Color grading editor.", group = "post", act = "shell_panel", arg = { name = "light_colorcorr" } },
    { id = "env_vignette", label = "Vignette", icon = "square", tip = "Vignette overlay.", group = "post", act = "settings_toggle", arg = { key = "fx_vignette" } },
    { id = "env_grain", label = "Grain", icon = "effects", tip = "Film grain overlay.", group = "post", act = "shell_panel", arg = { name = "env_grain" } },
    { id = "env_chroma", label = "Chromatic", icon = "effects", tip = "Chromatic aberration (honest: overlay approx).", group = "post", act = "shell_panel", arg = { name = "env_chroma" } },
    { id = "env_ppvol", label = "PP Volumes", icon = "boxG", tip = "Post-process volumes.", group = "volume", act = "shell_panel", arg = { name = "env_ppvol" } },
    { id = "env_fogvol", label = "Fog Volumes", icon = "boxG", tip = "Local fog volumes.", group = "volume", act = "shell_panel", arg = { name = "env_fogvol" } },
    { id = "env_lightvol", label = "Light Vols", icon = "boxG", tip = "Lighting override volumes.", group = "volume", act = "shell_panel", arg = { name = "world_zonefx" } },
    { id = "env_trigger", label = "Triggers", icon = "pin", tip = "Environment trigger volumes.", group = "volume", act = "shell_panel", arg = { name = "env_trigger" } },
    { id = "env_preset_day", label = "Day", icon = "bulb", tip = "Day environment preset.", group = "presets", act = "env_preset", arg = { name = "day" } },
    { id = "env_preset_dusk", label = "Dusk", icon = "bulb", tip = "Dusk preset.", group = "presets", act = "env_preset", arg = { name = "dusk" } },
    { id = "env_preset_night", label = "Night", icon = "bulb", tip = "Night preset.", group = "presets", act = "env_preset", arg = { name = "night" } },
    { id = "env_preset_storm", label = "Storm", icon = "cloud", tip = "Storm preset.", group = "presets", act = "env_preset", arg = { name = "storm" } },
    { id = "env_preset_snow", label = "Snow", icon = "cloud", tip = "Snow preset.", group = "presets", act = "env_preset", arg = { name = "snow" } },
    { id = "env_preset_desert", label = "Desert", icon = "bulb", tip = "Desert preset.", group = "presets", act = "env_preset", arg = { name = "desert" } },
    { id = "env_preset_alien", label = "Alien", icon = "effects", tip = "Alien world preset.", group = "presets", act = "env_preset", arg = { name = "alien" } },
    { id = "env_preset_under", label = "Underwater", icon = "drop", tip = "Underwater preset.", group = "presets", act = "env_preset", arg = { name = "underwater" } },
    { id = "env_savepreset", label = "Save", icon = "save", tip = "Save environment preset.", group = "presets", act = "env_savepreset", panel = "env_savepreset" },
    { id = "env_compare", label = "Compare", icon = "search", tip = "A/B compare presets.", group = "presets", act = "shell_panel", arg = { name = "env_compare" } },
    { id = "env_audit", label = "Audit", icon = "search", tip = "Environment audit.", group = "presets", act = "env_audit" },
    { id = "env_reset", label = "Reset", icon = "rotate", tip = "Reset environment.", group = "presets", act = "env_reset" },
    { id = "env_skybox", label = "Skybox", icon = "plus", tip = "Skybox presets.", group = "render", act = "shell_panel", arg = { name = "world_sky" } },
    { id = "env_stars", label = "Stars", icon = "effects", tip = "Stars config.", group = "render", act = "shell_panel", arg = { name = "world_sky" } },
    { id = "env_atmo", label = "Atmosphere", icon = "cloud", tip = "Atmosphere editor.", group = "post", act = "shell_panel", arg = { name = "light_atmosphere" } },
    { id = "env_limits", label = "Limits", icon = "info", tip = "Honest render limits.", group = "render", act = "shell_panel", arg = { name = "env_limits" } },
  } }
T[#T + 1] = { id = "ASSETS", label = "Assets", icon = "assets",
  groups = { { id = "browse", label = "Browse" }, { id = "models", label = "Models" },
    { id = "media", label = "Media" }, { id = "packs", label = "Packs" }, { id = "tools", label = "Tools" } },
  commands = {
    { id = "asset_browse", label = "Browse", icon = "search", tip = "Asset library browser.", group = "browse", act = "shell_panel", arg = { name = "asset_browse" } },
    { id = "asset_search", label = "Search", icon = "search", tip = "Search assets by name/tag.", group = "browse", act = "shell_panel", arg = { name = "asset_browse" } },
    { id = "asset_fav", label = "Favorites", icon = "gem", tip = "Favorite assets.", group = "browse", act = "shell_panel", arg = { name = "asset_fav" } },
    { id = "asset_recent", label = "Recent", icon = "repfirst", tip = "Recently used assets.", group = "browse", act = "shell_panel", arg = { name = "asset_recent" } },
    { id = "asset_insert", label = "Insert", icon = "plus", tip = "Insert asset by id.", group = "browse", act = "asset_insert", panel = "asset_insert" },
    { id = "asset_toolbox", label = "Toolbox", icon = "toolbox", tip = "Toolbox panel (InsertService-based).", group = "browse", act = "shell_toggle", arg = { panel = "toolbox" } },
    { id = "asset_models", label = "Models", icon = "model", tip = "Model library.", group = "models", act = "shell_panel", arg = { name = "asset_models" } },
    { id = "asset_meshes", label = "Meshes", icon = "model", tip = "Mesh id registry.", group = "models", act = "shell_panel", arg = { name = "asset_meshes" } },
    { id = "asset_packages", label = "Packages", icon = "toolbox", tip = "Package manager (auto-update).", group = "models", act = "shell_panel", arg = { name = "asset_packages" } },
    { id = "asset_rigs", label = "Rigs", icon = "character", tip = "Rig library.", group = "models", act = "shell_panel", arg = { name = "asset_rigs" } },
    { id = "asset_images", label = "Images", icon = "plus", tip = "Image id registry.", group = "media", act = "shell_panel", arg = { name = "asset_images" } },
    { id = "asset_sounds", label = "Sounds", icon = "note", tip = "Sound id registry.", group = "media", act = "shell_panel", arg = { name = "audio_browse" } },
    { id = "asset_anims", label = "Anims", icon = "keyframe", tip = "Animation id registry.", group = "media", act = "shell_panel", arg = { name = "asset_anims" } },
    { id = "asset_fonts", label = "Fonts", icon = "textA", tip = "Font list.", group = "media", act = "shell_panel", arg = { name = "ui_font" } },
    { id = "asset_videos", label = "Videos", icon = "play", tip = "VideoFrame id registry.", group = "media", act = "shell_panel", arg = { name = "asset_videos" } },
    { id = "asset_packnew", label = "New Pack", icon = "plus", tip = "Create asset pack.", group = "packs", act = "shell_panel", arg = { name = "asset_packnew" } },
    { id = "asset_packopen", label = "Open Pack", icon = "open", tip = "Open asset pack.", group = "packs", act = "shell_panel", arg = { name = "asset_packs" } },
    { id = "asset_packpub", label = "Publish Pack", icon = "cloud", tip = "Publish pack (guide).", group = "packs", act = "shell_panel", arg = { name = "asset_packpub" } },
    { id = "asset_versions", label = "Versions", icon = "repfirst", tip = "Asset version history.", group = "packs", act = "shell_panel", arg = { name = "asset_versions" } },
    { id = "asset_verify", label = "Verify", icon = "check", tip = "Verify asset ids (preload test).", group = "tools", act = "asset_verify" },
    { id = "asset_preload", label = "Preload", icon = "open", tip = "Preload asset set.", group = "tools", act = "asset_preload" },
    { id = "asset_replace", label = "Replace Id", icon = "rotate", tip = "Replace asset id across scope.", group = "tools", act = "shell_panel", arg = { name = "asset_replace" } },
    { id = "asset_missing", label = "Missing", icon = "search", tip = "Find missing/failed assets.", group = "tools", act = "asset_missing" },
    { id = "asset_audit", label = "Audit", icon = "search", tip = "Full asset audit.", group = "tools", act = "asset_audit" },
    { id = "asset_export", label = "Export", icon = "share", tip = "Export asset list JSON.", group = "tools", act = "asset_export" },
    { id = "asset_import", label = "Import", icon = "open", tip = "Import asset list JSON.", group = "tools", act = "asset_import", panel = "asset_import" },
    { id = "asset_ugc", label = "UGC", icon = "gem", tip = "UGC catalog browser (ids).", group = "models", act = "shell_panel", arg = { name = "asset_ugc" } },
    { id = "asset_avatar", label = "Avatar", icon = "character", tip = "Avatar item ids.", group = "models", act = "shell_panel", arg = { name = "asset_avatar" } },
    { id = "asset_badges", label = "Badges", icon = "gem", tip = "Badge ids.", group = "models", act = "shell_panel", arg = { name = "game_badges" } },
    { id = "asset_passes", label = "Passes", icon = "gem", tip = "Gamepass ids.", group = "models", act = "shell_panel", arg = { name = "game_passes" } },
    { id = "asset_cache", label = "Cache", icon = "data", tip = "Asset cache manager.", group = "browse", act = "shell_panel", arg = { name = "asset_cache" } },
    { id = "asset_quota", label = "Quota", icon = "data", tip = "Asset quota usage.", group = "browse", act = "shell_panel", arg = { name = "asset_quota" } },
    { id = "asset_moderation", label = "Moderation", icon = "check", tip = "Moderation status of assets.", group = "tools", act = "shell_panel", arg = { name = "asset_moderation" } },
    { id = "asset_perms", label = "Perms", icon = "lock", tip = "Asset permission flags.", group = "tools", act = "shell_panel", arg = { name = "asset_perms" } },
    { id = "asset_archive", label = "Archive", icon = "folderP", tip = "Archive unused assets.", group = "packs", act = "asset_archive" },
    { id = "asset_restore", label = "Restore", icon = "rotate", tip = "Restore archived assets.", group = "packs", act = "asset_restore", panel = "asset_restore" },
    { id = "asset_dupfind", label = "Duplicates", icon = "copy", tip = "Find duplicate assets.", group = "tools", act = "asset_dupfind" },
    { id = "asset_limits", label = "Limits", icon = "info", tip = "Honest asset limits.", group = "tools", act = "shell_panel", arg = { name = "asset_limits" } },
    { id = "asset_tags", label = "Tag Assets", icon = "textA", tip = "Tag/organize assets.", group = "browse", act = "shell_panel", arg = { name = "asset_tags" } },
    { id = "asset_collections", label = "Collections", icon = "folder", tip = "Asset collections.", group = "browse", act = "shell_panel", arg = { name = "asset_collections" } },
  } }
T[#T + 1] = { id = "PLUGINS", label = "Plugins", icon = "plugin",
  groups = { { id = "manage", label = "Manage" }, { id = "develop", label = "Develop" },
    { id = "toolbar", label = "Toolbar" }, { id = "permissions", label = "Permissions" }, { id = "store", label = "Store" } },
  commands = {
    { id = "plugin_list", label = "Installed", icon = "data", tip = "Installed plugins list.", group = "manage", act = "shell_panel", arg = { name = "plugin_list" } },
    { id = "plugin_enable", label = "Enable", icon = "check", tip = "Enable selected plugin.", group = "manage", act = "plugin_toggle", arg = { value = true } },
    { id = "plugin_disable", label = "Disable", icon = "close", tip = "Disable selected plugin.", group = "manage", act = "plugin_toggle", arg = { value = false } },
    { id = "plugin_reload", label = "Reload", icon = "rotate", tip = "Reload selected plugin.", group = "manage", act = "plugin_reload" },
    { id = "plugin_uninstall", label = "Uninstall", icon = "minus", tip = "Uninstall selected plugin.", group = "manage", act = "plugin_uninstall" },
    { id = "plugin_updates", label = "Updates", icon = "cloud", tip = "Check plugin updates.", group = "manage", act = "plugin_updates" },
    { id = "plugin_new", label = "New Plugin", icon = "plus", tip = "Scaffold a new plugin.", group = "develop", act = "plugin_new", panel = "plugin_new" },
    { id = "plugin_edit", label = "Edit Code", icon = "edit", tip = "Edit plugin stored source.", group = "develop", act = "shell_panel", arg = { name = "plugin_edit" } },
    { id = "plugin_test", label = "Test", icon = "play", tip = "Run plugin in sandbox.", group = "develop", act = "plugin_test" },
    { id = "plugin_debug", label = "Debug", icon = "search", tip = "Debug plugin execution.", group = "develop", act = "shell_panel", arg = { name = "plugin_debug" } },
    { id = "plugin_package", label = "Package", icon = "toolbox", tip = "Package plugin for sharing.", group = "develop", act = "plugin_package" },
    { id = "plugin_docs", label = "API Docs", icon = "note", tip = "Plugin API reference.", group = "develop", act = "shell_panel", arg = { name = "plugin_docs" } },
    { id = "plugin_toolbar", label = "Toolbar", icon = "dock", tip = "Plugin toolbar buttons manager.", group = "toolbar", act = "shell_panel", arg = { name = "plugin_toolbar" } },
    { id = "plugin_buttons", label = "Buttons", icon = "plus", tip = "Register toolbar button.", group = "toolbar", act = "shell_panel", arg = { name = "plugin_buttons" } },
    { id = "plugin_menus", label = "Menus", icon = "data", tip = "Context menu contributions.", group = "toolbar", act = "shell_panel", arg = { name = "plugin_menus" } },
    { id = "plugin_widgets", label = "Widgets", icon = "dock", tip = "Dock widget contributions.", group = "toolbar", act = "shell_panel", arg = { name = "plugin_widgets" } },
    { id = "plugin_perms", label = "Perms", icon = "lock", tip = "Plugin permission grants.", group = "permissions", act = "shell_panel", arg = { name = "plugin_perms" } },
    { id = "plugin_sandbox", label = "Sandbox", icon = "lock", tip = "Sandbox policy per plugin.", group = "permissions", act = "shell_panel", arg = { name = "plugin_sandbox" } },
    { id = "plugin_auditlog", label = "Audit Log", icon = "textA", tip = "Plugin action audit log.", group = "permissions", act = "shell_panel", arg = { name = "plugin_auditlog" } },
    { id = "plugin_trust", label = "Trust", icon = "check", tip = "Trust/untrust plugin author.", group = "permissions", act = "shell_panel", arg = { name = "plugin_trust" } },
    { id = "plugin_store", label = "Store", icon = "cloud", tip = "Plugin store browser (local registry).", group = "store", act = "shell_panel", arg = { name = "plugin_store" } },
    { id = "plugin_install", label = "Install", icon = "plus", tip = "Install plugin from id/file.", group = "store", act = "plugin_install", panel = "plugin_install" },
    { id = "plugin_rate", label = "Rate", icon = "gem", tip = "Rate installed plugin.", group = "store", act = "shell_panel", arg = { name = "plugin_rate" } },
    { id = "plugin_publish", label = "Publish", icon = "share", tip = "Publish plugin (guide).", group = "store", act = "shell_panel", arg = { name = "plugin_publish" } },
    { id = "plugin_settings", label = "Settings", icon = "settings", tip = "Per-plugin settings.", group = "manage", act = "shell_panel", arg = { name = "plugin_settings" } },
    { id = "plugin_data", label = "Data", icon = "save", tip = "Plugin data storage viewer.", group = "manage", act = "shell_panel", arg = { name = "plugin_data" } },
    { id = "plugin_errors", label = "Errors", icon = "close", tip = "Plugin error list.", group = "manage", act = "shell_panel", arg = { name = "plugin_errors" } },
    { id = "plugin_perf", label = "Perf", icon = "performance", tip = "Per-plugin cost.", group = "manage", act = "shell_panel", arg = { name = "plugin_perf" } },
    { id = "plugin_hooks", label = "Hooks", icon = "share", tip = "Lifecycle hooks registry.", group = "develop", act = "shell_panel", arg = { name = "plugin_hooks" } },
    { id = "plugin_events", label = "Events", icon = "play", tip = "Engine events for plugins.", group = "develop", act = "shell_panel", arg = { name = "plugin_events" } },
    { id = "plugin_hotkeys", label = "Hotkeys", icon = "textA", tip = "Plugin hotkey bindings.", group = "toolbar", act = "shell_panel", arg = { name = "plugin_hotkeys" } },
    { id = "plugin_conflicts", label = "Conflicts", icon = "search", tip = "Detect plugin conflicts.", group = "permissions", act = "plugin_conflicts" },
    { id = "plugin_export", label = "Export", icon = "share", tip = "Export plugin JSON.", group = "store", act = "plugin_export" },
    { id = "plugin_import", label = "Import", icon = "open", tip = "Import plugin JSON.", group = "store", act = "plugin_import", panel = "plugin_import" },
    { id = "plugin_verify", label = "Verify", icon = "check", tip = "Verify plugin signature (local hash).", group = "permissions", act = "plugin_verify" },
    { id = "plugin_limits", label = "Limits", icon = "info", tip = "Honest plugin limits (vs Studio plugins).", group = "store", act = "shell_panel", arg = { name = "plugin_limits" } },
    { id = "plugin_activity", label = "Activity", icon = "data", tip = "Plugin activity monitor.", group = "manage", act = "shell_panel", arg = { name = "plugin_activity" } },
    { id = "plugin_queue", label = "Queue", icon = "data", tip = "Install/update queue.", group = "store", act = "shell_panel", arg = { name = "plugin_queue" } },
    { id = "plugin_autoupd", label = "Auto-Update", icon = "rotate", tip = "Toggle auto-updates.", group = "store", act = "settings_toggle", arg = { key = "plugin_autoupd" } },
    { id = "plugin_reset", label = "Reset", icon = "rotate", tip = "Reset plugin system.", group = "manage", act = "plugin_reset" },
  } }
T[#T + 1] = { id = "SETTINGS", label = "Settings", icon = "settings",
  groups = { { id = "general", label = "General" }, { id = "editor", label = "Editor" },
    { id = "input", label = "Input" }, { id = "access", label = "Access" }, { id = "data", label = "Data" } },
  commands = {
    { id = "set_language", label = "Language", icon = "globe", tip = "Engine UI language.", group = "general", act = "shell_panel", arg = { name = "set_language" } },
    { id = "set_theme", label = "Theme", icon = "bulb", tip = "Theme controls.", group = "general", act = "shell_panel", arg = { name = "theme" } },
    { id = "set_uiscale", label = "UI Scale", icon = "expand", tip = "UI scale slider.", group = "general", act = "shell_panel", arg = { name = "set_uiscale" } },
    { id = "set_autosave", label = "Autosave", icon = "save", tip = "Autosave toggle + interval.", group = "general", act = "shell_panel", arg = { name = "set_autosave" } },
    { id = "set_telemetry", label = "Telemetry", icon = "data", tip = "Local-only diagnostics toggle.", group = "general", act = "settings_toggle", arg = { key = "telemetry" } },
    { id = "set_updates", label = "Updates", icon = "cloud", tip = "Update channel + notes.", group = "general", act = "shell_panel", arg = { name = "updates" } },
    { id = "set_resetall", label = "Reset All", icon = "rotate", tip = "Reset all settings.", group = "general", act = "settings_resetall" },
    { id = "set_grid", label = "Grid", icon = "dock", tip = "Grid size/snap defaults.", group = "editor", act = "shell_panel", arg = { name = "snap_settings" } },
    { id = "set_snap", label = "Snap", icon = "snap", tip = "Snap defaults.", group = "editor", act = "shell_panel", arg = { name = "snap_settings" } },
    { id = "set_gizmo", label = "Gizmo", icon = "move", tip = "Gizmo size/style.", group = "editor", act = "shell_panel", arg = { name = "set_gizmo" } },
    { id = "set_camera", label = "Camera", icon = "camera", tip = "Camera speed/invert.", group = "editor", act = "shell_panel", arg = { name = "set_camera" } },
    { id = "set_selection", label = "Selection", icon = "select", tip = "Selection highlight/outlines.", group = "editor", act = "shell_panel", arg = { name = "set_selection" } },
    { id = "set_undo", label = "Undo Depth", icon = "undo", tip = "Undo history depth.", group = "editor", act = "shell_panel", arg = { name = "set_undo" } },
    { id = "set_viewport", label = "Viewport", icon = "camera", tip = "Viewport defaults.", group = "editor", act = "shell_panel", arg = { name = "set_viewport" } },
    { id = "set_keys", label = "Shortcuts", icon = "textA", tip = "Shortcut remap.", group = "input", act = "shell_panel", arg = { name = "shortcuts" } },
    { id = "set_mouse", label = "Mouse", icon = "select", tip = "Mouse buttons + sensitivity.", group = "input", act = "shell_panel", arg = { name = "set_mouse" } },
    { id = "set_touch", label = "Touch", icon = "playersI", tip = "Touch controls layout.", group = "input", act = "shell_panel", arg = { name = "set_touch" } },
    { id = "set_gamepad", label = "Gamepad", icon = "playersI", tip = "Gamepad mapping.", group = "input", act = "shell_panel", arg = { name = "set_gamepad" } },
    { id = "set_vr", label = "VR", icon = "view", tip = "VR comfort + controls.", group = "input", act = "shell_panel", arg = { name = "set_vr" } },
    { id = "set_contrast", label = "Contrast", icon = "bulb", tip = "High-contrast theme.", group = "access", act = "settings_toggle", arg = { key = "contrast" } },
    { id = "set_textsize", label = "Text Size", icon = "textA", tip = "UI text size.", group = "access", act = "shell_panel", arg = { name = "set_textsize" } },
    { id = "set_colorblind", label = "Colorblind", icon = "view", tip = "Colorblind-safe palette.", group = "access", act = "shell_panel", arg = { name = "set_colorblind" } },
    { id = "set_reduce", label = "Reduce Motion", icon = "pause", tip = "Reduce animations.", group = "access", act = "settings_toggle", arg = { key = "reduce_motion" } },
    { id = "set_screenreader", label = "Screen Rdr", icon = "chat", tip = "Screen-reader labels verbosity.", group = "access", act = "shell_panel", arg = { name = "set_screenreader" } },
    { id = "set_captions", label = "Captions", icon = "textA", tip = "Caption defaults.", group = "access", act = "shell_panel", arg = { name = "set_captions" } },
    { id = "set_export", label = "Export", icon = "share", tip = "Export settings JSON.", group = "data", act = "settings_export" },
    { id = "set_import", label = "Import", icon = "open", tip = "Import settings JSON.", group = "data", act = "settings_import", panel = "settings_import" },
    { id = "set_profiles", label = "Profiles", icon = "playersI", tip = "Settings profiles.", group = "data", act = "shell_panel", arg = { name = "set_profiles" } },
    { id = "set_sync", label = "Sync", icon = "cloud", tip = "Cloud settings sync.", group = "data", act = "shell_panel", arg = { name = "set_sync" } },
    { id = "set_wipe", label = "Wipe Data", icon = "close", tip = "Wipe local engine data.", group = "data", act = "settings_wipe", panel = "settings_wipe" },
    { id = "set_about", label = "About", icon = "emblem", tip = "About + version.", group = "general", act = "shell_panel", arg = { name = "about" } },
    { id = "set_perfmode", label = "Perf Mode", icon = "performance", tip = "Low-spec UI mode.", group = "general", act = "settings_toggle", arg = { key = "perfmode" } },
    { id = "set_backup", label = "Backups", icon = "save", tip = "Backup settings.", group = "data", act = "shell_panel", arg = { name = "backup" } },
    { id = "set_logs", label = "Log Level", icon = "textA", tip = "Engine log verbosity.", group = "data", act = "shell_panel", arg = { name = "set_logs" } },
    { id = "set_crash", label = "Crash Rep", icon = "close", tip = "Crash report viewer.", group = "data", act = "shell_panel", arg = { name = "set_crash" } },
    { id = "set_first", label = "First Run", icon = "info", tip = "Replay first-run setup.", group = "general", act = "shell_panel", arg = { name = "first_run" } },
    { id = "set_tips", label = "Tips", icon = "bulb", tip = "Tips toggle.", group = "general", act = "settings_toggle", arg = { key = "tips" } },
    { id = "set_statusbar", label = "Status Bar", icon = "dock", tip = "Status bar content.", group = "editor", act = "shell_panel", arg = { name = "set_statusbar" } },
    { id = "set_toolbar", label = "Toolbar", icon = "dock", tip = "Customize quick toolbar.", group = "editor", act = "shell_panel", arg = { name = "set_toolbar" } },
    { id = "set_ribbon", label = "Ribbon", icon = "dock", tip = "Ribbon density.", group = "editor", act = "shell_panel", arg = { name = "set_ribbon" } },
  } }
T[#T + 1] = { id = "HELP", label = "Help", icon = "info",
  groups = { { id = "learn", label = "Learn" }, { id = "docs", label = "Docs" },
    { id = "support", label = "Support" }, { id = "diag", label = "Diagnostics" }, { id = "about", label = "About" } },
  commands = {
    { id = "help_welcome", label = "Welcome", icon = "info", tip = "Welcome page.", group = "learn", act = "shell_panel", arg = { name = "welcome" } },
    { id = "help_tour", label = "Tour", icon = "info", tip = "Guided tour.", group = "learn", act = "shell_panel", arg = { name = "tour" } },
    { id = "help_quickstart", label = "Quickstart", icon = "play", tip = "5-minute quickstart.", group = "learn", act = "shell_panel", arg = { name = "quickstart" } },
    { id = "help_tutorials", label = "Tutorials", icon = "note", tip = "Tutorial list.", group = "learn", act = "shell_panel", arg = { name = "tutorials" } },
    { id = "help_tips", label = "Tips", icon = "bulb", tip = "Tips browser.", group = "learn", act = "shell_panel", arg = { name = "tips" } },
    { id = "help_shortcuts", label = "Shortcuts", icon = "textA", tip = "Shortcut map.", group = "learn", act = "shell_panel", arg = { name = "shortcuts" } },
    { id = "help_cmdlist", label = "All Cmds", icon = "search", tip = "All 1200 commands browser.", group = "learn", act = "shell_panel", arg = { name = "cmdlist" } },
    { id = "help_docs", label = "Docs", icon = "note", tip = "Documentation browser.", group = "docs", act = "shell_panel", arg = { name = "docs" } },
    { id = "help_apiref", label = "API Ref", icon = "note", tip = "API reference.", group = "docs", act = "shell_panel", arg = { name = "arkher_api" } },
    { id = "help_guides", label = "Guides", icon = "note", tip = "How-to guides.", group = "docs", act = "shell_panel", arg = { name = "guides" } },
    { id = "help_faq", label = "FAQ", icon = "chat", tip = "Frequently asked questions.", group = "docs", act = "shell_panel", arg = { name = "faq" } },
    { id = "help_glossary", label = "Glossary", icon = "textA", tip = "Terms glossary.", group = "docs", act = "shell_panel", arg = { name = "glossary" } },
    { id = "help_report", label = "Report Bug", icon = "close", tip = "File a bug report (stored).", group = "support", act = "shell_panel", arg = { name = "report" } },
    { id = "help_feedback", label = "Feedback", icon = "chat", tip = "Send feedback.", group = "support", act = "shell_panel", arg = { name = "feedback" } },
    { id = "help_community", label = "Community", icon = "people", tip = "Community links.", group = "support", act = "shell_panel", arg = { name = "community" } },
    { id = "help_status", label = "Status", icon = "check", tip = "Service status.", group = "support", act = "shell_panel", arg = { name = "status" } },
    { id = "help_sysinfo", label = "Sys Info", icon = "data", tip = "System information.", group = "diag", act = "shell_panel", arg = { name = "sysinfo" } },
    { id = "help_logs", label = "Logs", icon = "textA", tip = "Engine log viewer.", group = "diag", act = "shell_panel", arg = { name = "help_logs" } },
    { id = "help_crash", label = "Crashes", icon = "close", tip = "Crash reports.", group = "diag", act = "shell_panel", arg = { name = "set_crash" } },
    { id = "help_selftest", label = "Self Test", icon = "check", tip = "Run engine self-test.", group = "diag", act = "test_local" },
    { id = "help_version", label = "Version", icon = "info", tip = "Version + build info.", group = "about", act = "shell_panel", arg = { name = "version" } },
    { id = "help_changelog", label = "Changelog", icon = "note", tip = "Changelog.", group = "about", act = "shell_panel", arg = { name = "changelog" } },
    { id = "help_credits", label = "Credits", icon = "people", tip = "Credits.", group = "about", act = "shell_panel", arg = { name = "credits" } },
    { id = "help_license", label = "License", icon = "note", tip = "License info.", group = "about", act = "shell_panel", arg = { name = "license" } },
    { id = "help_cheatsheet", label = "Cheatsheet", icon = "textA", tip = "One-page cheatsheet.", group = "learn", act = "shell_panel", arg = { name = "cheatsheet" } },
    { id = "help_videos", label = "Videos", icon = "play", tip = "Video tutorial links.", group = "learn", act = "shell_panel", arg = { name = "videos" } },
    { id = "help_examples", label = "Examples", icon = "folder", tip = "Example projects.", group = "learn", act = "shell_panel", arg = { name = "examples" } },
    { id = "help_migrate", label = "Migrate", icon = "share", tip = "Migrate from Studio guide.", group = "docs", act = "shell_panel", arg = { name = "migrate" } },
    { id = "help_bestprac", label = "Best Pract", icon = "check", tip = "Best practices.", group = "docs", act = "shell_panel", arg = { name = "bestprac" } },
    { id = "help_limits", label = "All Limits", icon = "info", tip = "Every honest limit in one place.", group = "docs", act = "shell_panel", arg = { name = "all_limits" } },
    { id = "help_contact", label = "Contact", icon = "chat", tip = "Contact info.", group = "support", act = "shell_panel", arg = { name = "contact" } },
    { id = "help_discord", label = "Discord", icon = "people", tip = "Discord invite.", group = "support", act = "shell_panel", arg = { name = "discord" } },
    { id = "help_forum", label = "Forum", icon = "chat", tip = "Forum link.", group = "support", act = "shell_panel", arg = { name = "forum" } },
    { id = "help_diag", label = "Diagnose", icon = "search", tip = "Auto-diagnose issues.", group = "diag", act = "project_validate" },
    { id = "help_bench", label = "Benchmark", icon = "performance", tip = "Run benchmark.", group = "diag", act = "perf_audit" },
    { id = "help_resetui", label = "Reset UI", icon = "rotate", tip = "Reset engine UI layout.", group = "diag", act = "view_layout", arg = { op = "reset" } },
    { id = "help_reload", label = "Reload Eng", icon = "rotate", tip = "Reload engine UI (rebuild).", group = "diag", act = "shell_reload" },
    { id = "help_safemode", label = "Safe Mode", icon = "lock", tip = "Restart in safe mode (no plugins).", group = "diag", act = "shell_safemode" },
    { id = "help_about", label = "About", icon = "emblem", tip = "About ARKHER.", group = "about", act = "shell_panel", arg = { name = "about" } },
    { id = "help_privacy", label = "Privacy", icon = "lock", tip = "Privacy info.", group = "about", act = "shell_panel", arg = { name = "privacy" } },
  } }
return T
