-- arkher/registry/tabs03.lua — Character, Animation, Cutscene, UI, Materials (5x40).
local T = {}
T[#T + 1] = { id = "CHARACTER", label = "Character", icon = "character",
  groups = { { id = "create", label = "Create" }, { id = "rig", label = "Rig" },
    { id = "look", label = "Look" }, { id = "stats", label = "Stats" }, { id = "anim", label = "Anims" } },
  commands = {
    { id = "char_new", label = "New Char", icon = "character", tip = "Spawn R15 rig at focus (real).", group = "create", act = "char_new", panel = "char_new" },
    { id = "char_r6", label = "R6 Rig", icon = "character", tip = "Spawn R6 rig.", group = "create", act = "char_new", arg = { rig = "R6" } },
    { id = "char_r15", label = "R15 Rig", icon = "character", tip = "Spawn R15 rig.", group = "create", act = "char_new", arg = { rig = "R15" } },
    { id = "char_npc", label = "From NPC", icon = "npc", tip = "Convert NPC to playable character.", group = "create", act = "char_fromnpc" },
    { id = "char_clone", label = "Clone Char", icon = "copy", tip = "Clone selected character.", group = "create", act = "edit_duplicate" },
    { id = "char_delete", label = "Delete Char", icon = "close", tip = "Delete selected character.", group = "create", act = "edit_delete" },
    { id = "char_pose", label = "Pose Reset", icon = "rotate", tip = "Reset pose to default.", group = "create", act = "char_posereset" },
    { id = "char_save", label = "Save Char", icon = "save", tip = "Save character preset.", group = "create", act = "char_savepreset", panel = "char_presets" },
    { id = "char_rigedit", label = "Rig Edit", icon = "playersI", tip = "Rig editor: Motor6D tree + offsets.", group = "rig", act = "shell_panel", arg = { name = "char_rig" } },
    { id = "char_ik", label = "IK", icon = "share", tip = "Two-bone IK handles for limbs.", group = "rig", act = "char_ik", panel = "char_ik" },
    { id = "char_scale", label = "Body Scale", icon = "scaleI", tip = "Height/Width/Depth/Head scales.", group = "rig", act = "shell_panel", arg = { name = "char_scale" } },
    { id = "char_proportion", label = "Proportion", icon = "data", tip = "BodyType/Proportion sliders.", group = "rig", act = "shell_panel", arg = { name = "char_scale" } },
    { id = "char_colliders", label = "Colliders", icon = "boxG", tip = "Per-limb CanCollide/CanQuery flags.", group = "rig", act = "shell_panel", arg = { name = "char_colliders" } },
    { id = "char_ragdoll", label = "Ragdoll", icon = "rotate", tip = "Toggle ragdoll (BallSocket swap, preview).", group = "rig", act = "char_ragdoll" },
    { id = "char_face", label = "Face", icon = "plus", tip = "Face texture picker.", group = "look", act = "shell_panel", arg = { name = "char_face" } },
    { id = "char_skin", label = "Skin", icon = "drop", tip = "Skin tone picker.", group = "look", act = "shell_panel", arg = { name = "char_skin" } },
    { id = "char_shirt", label = "Shirt", icon = "plus", tip = "Shirt asset id.", group = "look", act = "shell_panel", arg = { name = "char_clothes" } },
    { id = "char_pants", label = "Pants", icon = "plus", tip = "Pants asset id.", group = "look", act = "shell_panel", arg = { name = "char_clothes" } },
    { id = "char_hats", label = "Hats", icon = "plus", tip = "Attach hats/accessories by id.", group = "look", act = "shell_panel", arg = { name = "char_hats" } },
    { id = "char_outfit", label = "Outfits", icon = "character", tip = "Outfit presets save/load.", group = "look", act = "shell_panel", arg = { name = "char_outfits" } },
    { id = "char_emotes", label = "Emotes", icon = "play", tip = "Emote bar: play emote animations.", group = "look", act = "shell_panel", arg = { name = "char_emotes" } },
    { id = "char_health", label = "Health", icon = "plus", tip = "MaxHealth/Health editor.", group = "stats", act = "shell_panel", arg = { name = "char_stats" } },
    { id = "char_speed", label = "WalkSpeed", icon = "data", tip = "WalkSpeed editor.", group = "stats", act = "shell_panel", arg = { name = "char_stats" } },
    { id = "char_jump", label = "Jump", icon = "data", tip = "JumpPower/JumpHeight editor.", group = "stats", act = "shell_panel", arg = { name = "char_stats" } },
    { id = "char_attrs", label = "Attributes", icon = "data", tip = "Custom attributes editor.", group = "stats", act = "shell_panel", arg = { name = "char_attrs" } },
    { id = "char_tags", label = "Tags", icon = "textA", tip = "CollectionService tags editor.", group = "stats", act = "shell_panel", arg = { name = "char_tags" } },
    { id = "char_respawn", label = "Respawn", icon = "rotate", tip = "Respawn character at spawn.", group = "stats", act = "char_respawn" },
    { id = "char_kill", label = "Kill", icon = "close", tip = "Set health to 0 (preview).", group = "stats", act = "char_kill" },
    { id = "char_fullreset", label = "Full Reset", icon = "rotate", tip = "Reset pose + stats + anims to defaults.", group = "stats", act = "char_fullreset" },
    { id = "char_idle", label = "Idle Anim", icon = "play", tip = "Set idle animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_walk", label = "Walk Anim", icon = "play", tip = "Set walk animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_run", label = "Run Anim", icon = "play", tip = "Set run animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_jumpanim", label = "Jump Anim", icon = "play", tip = "Set jump animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_fall", label = "Fall Anim", icon = "play", tip = "Set fall animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_swim", label = "Swim Anim", icon = "play", tip = "Set swim animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_climb", label = "Climb Anim", icon = "play", tip = "Set climb animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_sit", label = "Sit Anim", icon = "play", tip = "Set sit animation id.", group = "anim", act = "shell_panel", arg = { name = "char_anims" } },
    { id = "char_preview", label = "Preview", icon = "view", tip = "Preview stage: turntable + anim test.", group = "anim", act = "shell_panel", arg = { name = "char_preview" } },
    { id = "char_export", label = "Export Char", icon = "share", tip = "Export character JSON.", group = "anim", act = "char_export" },
    { id = "char_import", label = "Import Char", icon = "open", tip = "Import character JSON.", group = "anim", act = "char_import", panel = "char_import" },
  } }
T[#T + 1] = { id = "ANIMATION", label = "Animation", icon = "keyframe",
  groups = { { id = "timeline", label = "Timeline" }, { id = "keys", label = "Keys" },
    { id = "curves", label = "Curves" }, { id = "layers", label = "Layers" }, { id = "export", label = "Export" } },
  commands = {
    { id = "anim_new", label = "New Clip", icon = "plus", tip = "New animation clip on selected rig.", group = "timeline", act = "anim_new", panel = "anim_new" },
    { id = "anim_open", label = "Open Clip", icon = "open", tip = "Open saved clip.", group = "timeline", act = "shell_panel", arg = { name = "anim_clips" } },
    { id = "anim_play", label = "Play", icon = "play", tip = "Play clip on rig.", group = "timeline", act = "anim_play" },
    { id = "anim_pause", label = "Pause", icon = "pause", tip = "Pause playback.", group = "timeline", act = "anim_pause" },
    { id = "anim_stop", label = "Stop", icon = "close", tip = "Stop playback.", group = "timeline", act = "anim_stop" },
    { id = "anim_loop", label = "Loop", icon = "rotate", tip = "Toggle loop.", group = "timeline", act = "anim_loop" },
    { id = "anim_speed", label = "Speed", icon = "data", tip = "Playback speed.", group = "timeline", act = "shell_panel", arg = { name = "anim_speed" } },
    { id = "anim_fps", label = "FPS", icon = "data", tip = "Clip frame rate.", group = "timeline", act = "shell_panel", arg = { name = "anim_speed" } },
    { id = "anim_addkey", label = "Add Key", icon = "keyframe", tip = "Keyframe panel: add key at playhead for selection.", group = "keys", act = "anim_addkey", panel = "anim_keyframe" },
    { id = "anim_delkey", label = "Delete Key", icon = "close", tip = "Delete key at playhead.", group = "keys", act = "anim_delkey" },
    { id = "anim_prevkey", label = "Prev Key", icon = "chevR", tip = "Jump to previous key.", group = "keys", act = "anim_navkey", arg = { dir = -1 } },
    { id = "anim_nextkey", label = "Next Key", icon = "chevR", tip = "Jump to next key.", group = "keys", act = "anim_navkey", arg = { dir = 1 } },
    { id = "anim_copykeys", label = "Copy Keys", icon = "copy", tip = "Copy selected keys.", group = "keys", act = "anim_copykeys" },
    { id = "anim_pastekeys", label = "Paste Keys", icon = "paste", tip = "Paste keys at playhead.", group = "keys", act = "anim_pastekeys" },
    { id = "anim_allkeys", label = "Key All", icon = "keyframe", tip = "Key all animated joints at playhead.", group = "keys", act = "anim_keyall" },
    { id = "anim_curves", label = "Curve Edit", icon = "data", tip = "Curve editor panel (per-joint).", group = "curves", act = "shell_panel", arg = { name = "anim_curves" } },
    { id = "anim_ease", label = "Easing", icon = "data", tip = "Easing style for selected keys.", group = "curves", act = "shell_panel", arg = { name = "anim_ease" } },
    { id = "anim_smooth", label = "Smooth", icon = "rotate", tip = "Smooth selected key segment.", group = "curves", act = "anim_smooth" },
    { id = "anim_mirror", label = "Mirror", icon = "share", tip = "Mirror pose/keys left-right.", group = "curves", act = "anim_mirror" },
    { id = "anim_reverse", label = "Reverse", icon = "rotate", tip = "Reverse clip time.", group = "curves", act = "anim_reverse" },
    { id = "anim_scale", label = "Time Scale", icon = "scaleI", tip = "Scale clip duration.", group = "curves", act = "shell_panel", arg = { name = "anim_timescale" } },
    { id = "anim_layers", label = "Layers", icon = "data", tip = "Animation layers: add/blend/mute.", group = "layers", act = "shell_panel", arg = { name = "anim_layers" } },
    { id = "anim_blend", label = "Blend", icon = "share", tip = "Crossfade between two clips.", group = "layers", act = "shell_panel", arg = { name = "anim_blend" } },
    { id = "anim_mask", label = "Mask", icon = "lock", tip = "Body-part mask for layer.", group = "layers", act = "shell_panel", arg = { name = "anim_mask" } },
    { id = "anim_additive", label = "Additive", icon = "plus", tip = "Additive layer mode.", group = "layers", act = "anim_additive" },
    { id = "anim_pose", label = "Pose Lib", icon = "save", tip = "Pose library save/apply.", group = "layers", act = "shell_panel", arg = { name = "anim_poses" } },
    { id = "anim_ikfk", label = "IK/FK", icon = "share", tip = "IK/FK blend per limb.", group = "layers", act = "shell_panel", arg = { name = "char_ik" } },
    { id = "anim_onion", label = "Onion Skin", icon = "view", tip = "Ghost prev/next frames.", group = "layers", act = "settings_toggle", arg = { key = "anim_onion" } },
    { id = "anim_events", label = "Events", icon = "play", tip = "Clip event markers (sound/FX hooks).", group = "export", act = "shell_panel", arg = { name = "anim_events" } },
    { id = "anim_export", label = "Export Clip", icon = "share", tip = "Export clip JSON.", group = "export", act = "anim_export" },
    { id = "anim_import", label = "Import Clip", icon = "open", tip = "Import clip JSON.", group = "export", act = "anim_import", panel = "anim_import" },
    { id = "anim_publish", label = "To Roblox", icon = "cloud", tip = "Guide: publish clip as Roblox Animation (limit noted).", group = "export", act = "shell_panel", arg = { name = "anim_publish" } },
    { id = "anim_bake", label = "Bake", icon = "save", tip = "Bake layers to single clip.", group = "export", act = "anim_bake" },
    { id = "anim_retarget", label = "Retarget", icon = "share", tip = "Retarget clip R6<->R15 (map panel).", group = "export", act = "shell_panel", arg = { name = "anim_retarget" } },
    { id = "anim_audit", label = "Audit Clip", icon = "search", tip = "Check clip for gaps/pops.", group = "export", act = "anim_audit" },
    { id = "anim_facial", label = "Facial", icon = "character", tip = "Facial pose controls.", group = "keys", act = "shell_panel", arg = { name = "anim_facial" } },
    { id = "anim_fingers", label = "Fingers", icon = "select", tip = "Finger pose controls.", group = "keys", act = "shell_panel", arg = { name = "anim_fingers" } },
    { id = "anim_root", label = "Root Motion", icon = "move", tip = "Root motion on/off + extract.", group = "curves", act = "shell_panel", arg = { name = "anim_root" } },
    { id = "anim_snapping", label = "Key Snap", icon = "snap", tip = "Snap keys to frames.", group = "curves", act = "settings_toggle", arg = { key = "anim_keysnap" } },
    { id = "anim_quantize", label = "Quantize", icon = "snap", tip = "Quantize selected keys to step grid.", group = "curves", act = "anim_quantize" },
  } }
T[#T + 1] = { id = "CUTSCENE", label = "Cutscene", icon = "cutscene",
  groups = { { id = "sequence", label = "Sequence" }, { id = "camera", label = "Camera" },
    { id = "actors", label = "Actors" }, { id = "audio", label = "Audio" }, { id = "render", label = "Render" } },
  commands = {
    { id = "cut_new", label = "New Scene", icon = "plus", tip = "New cutscene sequence.", group = "sequence", act = "cut_new", panel = "cut_new" },
    { id = "cut_open", label = "Open Scene", icon = "open", tip = "Open saved sequence.", group = "sequence", act = "shell_panel", arg = { name = "cut_list" } },
    { id = "cut_play", label = "Play", icon = "play", tip = "Play sequence.", group = "sequence", act = "cut_play" },
    { id = "cut_pause", label = "Pause", icon = "pause", tip = "Pause sequence.", group = "sequence", act = "cut_pause" },
    { id = "cut_stop", label = "Stop", icon = "close", tip = "Stop sequence.", group = "sequence", act = "cut_stop" },
    { id = "cut_timeline", label = "Timeline", icon = "data", tip = "Sequence timeline panel.", group = "sequence", act = "shell_panel", arg = { name = "cut_timeline" } },
    { id = "cut_shots", label = "Shots", icon = "camera", tip = "Shot list manager.", group = "sequence", act = "shell_panel", arg = { name = "cut_shots" } },
    { id = "cut_addshot", label = "Add Shot", icon = "plus", tip = "Add shot at playhead.", group = "sequence", act = "cut_addshot" },
    { id = "cut_dupshot", label = "Dupl Shot", icon = "copy", tip = "Duplicate current shot.", group = "sequence", act = "cut_dupshot" },
    { id = "cut_camadd", label = "Add Cam", icon = "camera", tip = "Add camera track key.", group = "camera", act = "cut_camadd" },
    { id = "cut_camgoto", label = "Goto Cam", icon = "search", tip = "Jump viewport to shot camera.", group = "camera", act = "cut_camgoto" },
    { id = "cut_dolly", label = "Dolly", icon = "move", tip = "Dolly path between two keys.", group = "camera", act = "shell_panel", arg = { name = "cut_dolly" } },
    { id = "cut_shake", label = "Shake", icon = "rotate", tip = "Camera shake envelope.", group = "camera", act = "shell_panel", arg = { name = "cut_shake" } },
    { id = "cut_fov", label = "FOV Track", icon = "camera", tip = "FOV animation track.", group = "camera", act = "shell_panel", arg = { name = "cut_fov" } },
    { id = "cut_focus", label = "Focus Track", icon = "search", tip = "Depth-of-field focus track.", group = "camera", act = "shell_panel", arg = { name = "cut_focus" } },
    { id = "cut_trans", label = "Transitions", icon = "share", tip = "Cut/fade/dissolve between shots.", group = "camera", act = "shell_panel", arg = { name = "cut_trans" } },
    { id = "cut_letterbox", label = "Letterbox", icon = "dock", tip = "Cinematic bars overlay.", group = "camera", act = "settings_toggle", arg = { key = "cut_letterbox" } },
    { id = "cut_cast", label = "Cast", icon = "npc", tip = "Cast list: assign actors.", group = "actors", act = "shell_panel", arg = { name = "cut_cast" } },
    { id = "cut_blocking", label = "Blocking", icon = "move", tip = "Actor marks + paths.", group = "actors", act = "shell_panel", arg = { name = "cut_blocking" } },
    { id = "cut_dialog", label = "Dialog", icon = "chat", tip = "Subtitle/dialog track.", group = "actors", act = "shell_panel", arg = { name = "cut_dialog" } },
    { id = "cut_acting", label = "Acting", icon = "play", tip = "Per-shot animation assignments.", group = "actors", act = "shell_panel", arg = { name = "cut_acting" } },
    { id = "cut_crowd", label = "Crowd", icon = "people", tip = "Background crowd spawner.", group = "actors", act = "shell_panel", arg = { name = "cut_crowd" } },
    { id = "cut_lipsync", label = "Lip Sync", icon = "chat", tip = "Viseme track (honest: manual keys).", group = "actors", act = "shell_panel", arg = { name = "cut_lipsync" } },
    { id = "cut_music", label = "Music", icon = "note", tip = "Music track.", group = "audio", act = "shell_panel", arg = { name = "cut_music" } },
    { id = "cut_sfx", label = "SFX Track", icon = "effects", tip = "SFX cue track.", group = "audio", act = "shell_panel", arg = { name = "cut_sfx" } },
    { id = "cut_voice", label = "Voice", icon = "chat", tip = "Voiceover track.", group = "audio", act = "shell_panel", arg = { name = "cut_voice" } },
    { id = "cut_duck", label = "Ducking", icon = "data", tip = "Music ducking under dialog.", group = "audio", act = "settings_toggle", arg = { key = "cut_duck" } },
    { id = "cut_mix", label = "Mix", icon = "data", tip = "Cutscene mix levels.", group = "audio", act = "shell_panel", arg = { name = "cut_mix" } },
    { id = "cut_record", label = "Record Cam", icon = "close", tip = "Record free camera move as track.", group = "audio", act = "cut_recordcam" },
    { id = "cut_preview", label = "Preview", icon = "view", tip = "Fullscreen preview.", group = "render", act = "cut_preview" },
    { id = "cut_exportvid", label = "Export Video", icon = "share", tip = "Honest: frame-by-frame capture guide (no video encoder).", group = "render", act = "shell_panel", arg = { name = "cut_exportvid" } },
    { id = "cut_exportseq", label = "Export Seq", icon = "save", tip = "Export sequence JSON.", group = "render", act = "cut_export" },
    { id = "cut_importseq", label = "Import Seq", icon = "open", tip = "Import sequence JSON.", group = "render", act = "cut_import", panel = "cut_import" },
    { id = "cut_storyboard", label = "Storyboard", icon = "dock", tip = "Shot thumbnail board.", group = "render", act = "shell_panel", arg = { name = "cut_storyboard" } },
    { id = "cut_script", label = "Script Doc", icon = "note", tip = "Screenplay text view.", group = "render", act = "shell_panel", arg = { name = "cut_script" } },
    { id = "cut_timecode", label = "Timecode", icon = "data", tip = "Timecode display format.", group = "render", act = "shell_panel", arg = { name = "cut_timecode" } },
    { id = "cut_skip", label = "Skip Logic", icon = "play", tip = "Skippable + skip-to-shot setup.", group = "render", act = "shell_panel", arg = { name = "cut_skip" } },
    { id = "cut_triggers", label = "Triggers", icon = "pin", tip = "In-world cutscene triggers.", group = "actors", act = "shell_panel", arg = { name = "cut_triggers" } },
    { id = "cut_fade", label = "Fade IO", icon = "square", tip = "Fade in/out controls.", group = "camera", act = "shell_panel", arg = { name = "cut_fade" } },
    { id = "cut_speed", label = "Speed", icon = "data", tip = "Sequence playback speed.", group = "sequence", act = "shell_panel", arg = { name = "cut_speed" } },
  } }
T[#T + 1] = { id = "UI", label = "UI", icon = "dock",
  groups = { { id = "create", label = "Create" }, { id = "layout", label = "Layout" },
    { id = "style", label = "Style" }, { id = "bind", label = "Bind" }, { id = "preview", label = "Preview" } },
  commands = {
    { id = "ui_frame", label = "Frame", icon = "dock", tip = "Insert Frame.", group = "create", act = "create", arg = { class = "Frame", intoSelection = true } },
    { id = "ui_textbtn", label = "TextButton", icon = "textA", tip = "Insert TextButton.", group = "create", act = "create", arg = { class = "TextButton", intoSelection = true } },
    { id = "ui_textlabel", label = "TextLabel", icon = "textA", tip = "Insert TextLabel.", group = "create", act = "create", arg = { class = "TextLabel", intoSelection = true } },
    { id = "ui_textbox", label = "TextBox", icon = "textA", tip = "Insert TextBox.", group = "create", act = "create", arg = { class = "TextBox", intoSelection = true } },
    { id = "ui_image", label = "ImageLabel", icon = "plus", tip = "Insert ImageLabel.", group = "create", act = "create", arg = { class = "ImageLabel", intoSelection = true } },
    { id = "ui_imgbtn", label = "ImageButton", icon = "plus", tip = "Insert ImageButton.", group = "create", act = "create", arg = { class = "ImageButton", intoSelection = true } },
    { id = "ui_scroll", label = "ScrollFrame", icon = "dock", tip = "Insert ScrollingFrame.", group = "create", act = "create", arg = { class = "ScrollingFrame", intoSelection = true } },
    { id = "ui_viewport", label = "ViewportF", icon = "camera", tip = "Insert ViewportFrame.", group = "create", act = "create", arg = { class = "ViewportFrame", intoSelection = true } },
    { id = "ui_list", label = "UIList", icon = "data", tip = "Insert UIListLayout.", group = "layout", act = "create", arg = { class = "UIListLayout", intoSelection = true } },
    { id = "ui_grid", label = "UIGrid", icon = "dock", tip = "Insert UIGridLayout.", group = "layout", act = "create", arg = { class = "UIGridLayout", intoSelection = true } },
    { id = "ui_table", label = "UITable", icon = "data", tip = "Insert UITableLayout.", group = "layout", act = "create", arg = { class = "UITableLayout", intoSelection = true } },
    { id = "ui_padding", label = "UIPadding", icon = "plus", tip = "Insert UIPadding.", group = "layout", act = "create", arg = { class = "UIPadding", intoSelection = true } },
    { id = "ui_aspect", label = "Aspect", icon = "expand", tip = "Insert UIAspectRatioConstraint.", group = "layout", act = "create", arg = { class = "UIAspectRatioConstraint", intoSelection = true } },
    { id = "ui_sizecon", label = "Size Constr", icon = "lock", tip = "Insert UISizeConstraint.", group = "layout", act = "create", arg = { class = "UISizeConstraint", intoSelection = true } },
    { id = "ui_align", label = "Align Gui", icon = "share", tip = "Align selected GuiObjects.", group = "layout", act = "ui_align" },
    { id = "ui_distribute", label = "Distribute", icon = "share", tip = "Distribute selected GuiObjects.", group = "layout", act = "ui_distribute" },
    { id = "ui_corner", label = "UICorner", icon = "plus", tip = "Insert UICorner.", group = "style", act = "create", arg = { class = "UICorner", intoSelection = true } },
    { id = "ui_stroke", label = "UIStroke", icon = "edit", tip = "Insert UIStroke.", group = "style", act = "create", arg = { class = "UIStroke", intoSelection = true } },
    { id = "ui_gradient", label = "UIGradient", icon = "square", tip = "Insert UIGradient.", group = "style", act = "create", arg = { class = "UIGradient", intoSelection = true } },
    { id = "ui_scale", label = "UIScale", icon = "scaleI", tip = "Insert UIScale.", group = "style", act = "create", arg = { class = "UIScale", intoSelection = true } },
    { id = "ui_font", label = "Font", icon = "textA", tip = "Font picker for selection.", group = "style", act = "shell_panel", arg = { name = "ui_font" } },
    { id = "ui_theme", label = "UI Theme", icon = "bulb", tip = "Apply theme to ScreenGui.", group = "style", act = "shell_panel", arg = { name = "ui_theme" } },
    { id = "ui_nine", label = "9-Slice", icon = "boxG", tip = "9-slice setup for ImageLabels.", group = "style", act = "shell_panel", arg = { name = "ui_nine" } },
    { id = "ui_localize", label = "Localize", icon = "globe", tip = "Localization keys for texts.", group = "style", act = "shell_panel", arg = { name = "ui_localize" } },
    { id = "ui_bindclick", label = "On Click", icon = "select", tip = "Bind click -> action (creates listener code).", group = "bind", act = "shell_panel", arg = { name = "ui_bindclick" } },
    { id = "ui_bindvalue", label = "Bind Value", icon = "data", tip = "Bind text/visible to attribute.", group = "bind", act = "shell_panel", arg = { name = "ui_bindvalue" } },
    { id = "ui_animpanel", label = "Animate", icon = "play", tip = "Tween animation builder for GuiObjects.", group = "bind", act = "shell_panel", arg = { name = "ui_anim" } },
    { id = "ui_showhide", label = "Show/Hide", icon = "view", tip = "Toggle Visible on selection.", group = "bind", act = "ui_showhide" },
    { id = "ui_modal", label = "Modal", icon = "lock", tip = "Make ScreenGui modal + focus.", group = "bind", act = "ui_modal" },
    { id = "ui_nav", label = "Navigation", icon = "share", tip = "Screen navigation graph.", group = "bind", act = "shell_panel", arg = { name = "ui_nav" } },
    { id = "ui_preview", label = "Preview", icon = "view", tip = "Preview ScreenGui fullscreen.", group = "preview", act = "ui_preview" },
    { id = "ui_devices", label = "Devices", icon = "playersI", tip = "Preview at phone/tablet/desktop sizes.", group = "preview", act = "shell_panel", arg = { name = "ui_devices" } },
    { id = "ui_safearea", label = "Safe Area", icon = "boxG", tip = "Show safe-area guides.", group = "preview", act = "settings_toggle", arg = { key = "ui_safearea" } },
    { id = "ui_a11y", label = "A11y Check", icon = "check", tip = "Contrast/touch-size audit.", group = "preview", act = "ui_a11y" },
    { id = "ui_export", label = "Export UI", icon = "share", tip = "Export Gui JSON.", group = "preview", act = "ui_export" },
    { id = "ui_import", label = "Import UI", icon = "open", tip = "Import Gui JSON.", group = "preview", act = "ui_import", panel = "ui_import" },
    { id = "ui_snippets", label = "Snippets", icon = "dock", tip = "UI snippet library (button/card/bar...).", group = "create", act = "shell_panel", arg = { name = "ui_snippets" } },
    { id = "ui_zindex", label = "Z-Order", icon = "data", tip = "ZIndex bring/send controls.", group = "layout", act = "shell_panel", arg = { name = "ui_zindex" } },
    { id = "ui_anchor", label = "AnchorPt", icon = "pin", tip = "AnchorPoint presets.", group = "layout", act = "shell_panel", arg = { name = "ui_anchor" } },
    { id = "ui_autoscale", label = "Auto Scale", icon = "expand", tip = "Auto-scale rules for resolutions.", group = "preview", act = "shell_panel", arg = { name = "ui_autoscale" } },
  } }
T[#T + 1] = { id = "MATERIALS", label = "Materials", icon = "terrain",
  groups = { { id = "library", label = "Library" }, { id = "pbr", label = "PBR" },
    { id = "paint", label = "Paint" }, { id = "terrain", label = "Terrain" }, { id = "manage", label = "Manage" } },
  commands = {
    { id = "mat_browse", label = "Browse", icon = "search", tip = "Material library browser.", group = "library", act = "shell_panel", arg = { name = "mat_browse" } },
    { id = "mat_apply", label = "Apply", icon = "check", tip = "Apply current material to selection.", group = "library", act = "mat_apply" },
    { id = "mat_fav", label = "Favorites", icon = "gem", tip = "Favorite materials.", group = "library", act = "shell_panel", arg = { name = "mat_fav" } },
    { id = "mat_recent", label = "Recent", icon = "repfirst", tip = "Recently used materials.", group = "library", act = "shell_panel", arg = { name = "mat_recent" } },
    { id = "mat_search", label = "Search", icon = "search", tip = "Search materials by name/tag.", group = "library", act = "shell_panel", arg = { name = "mat_browse" } },
    { id = "mat_variants", label = "Variants", icon = "terrain", tip = "MaterialVariant manager for parts.", group = "library", act = "shell_panel", arg = { name = "mat_variants" } },
    { id = "mat_service", label = "Mat Service", icon = "data", tip = "MaterialService overrides.", group = "library", act = "shell_panel", arg = { name = "mat_service" } },
    { id = "mat_color", label = "Color", icon = "drop", tip = "Color picker (applies to selection).", group = "pbr", act = "shell_panel", arg = { name = "home_color" } },
    { id = "mat_transp", label = "Transp", icon = "square", tip = "Transparency slider.", group = "pbr", act = "shell_panel", arg = { name = "home_transp" } },
    { id = "mat_reflect", label = "Reflect", icon = "bulb", tip = "Reflectance slider.", group = "pbr", act = "shell_panel", arg = { name = "home_reflect" } },
    { id = "mat_metal", label = "Metalness", icon = "data", tip = "Honest: no PBR sliders on parts; SurfaceAppearance maps instead.", group = "pbr", act = "shell_panel", arg = { name = "mat_pbr" } },
    { id = "mat_rough", label = "Roughness", icon = "data", tip = "RoughnessMap setup via SurfaceAppearance.", group = "pbr", act = "shell_panel", arg = { name = "mat_pbr" } },
    { id = "mat_normal", label = "NormalMap", icon = "plus", tip = "NormalMap setup via SurfaceAppearance.", group = "pbr", act = "shell_panel", arg = { name = "mat_pbr" } },
    { id = "mat_colormap", label = "ColorMap", icon = "plus", tip = "ColorMap setup via SurfaceAppearance.", group = "pbr", act = "shell_panel", arg = { name = "mat_pbr" } },
    { id = "mat_surface", label = "SurfaceApp", icon = "plus", tip = "Create SurfaceAppearance on selection.", group = "pbr", act = "mat_surfaceapp" },
    { id = "mat_paint", label = "Paint Tool", icon = "drop", tip = "Paint tool with current material.", group = "paint", act = "tool_mode", arg = { mode = "Paint" } },
    { id = "mat_fill", label = "Fill Sel", icon = "plus", tip = "Fill selection with current material+color.", group = "paint", act = "mat_fill" },
    { id = "mat_replace", label = "Replace", icon = "rotate", tip = "Replace material A->B in scope.", group = "paint", act = "shell_panel", arg = { name = "mat_replace" } },
    { id = "mat_sample", label = "Sample", icon = "search", tip = "Sample material+color from part.", group = "paint", act = "tool_mode", arg = { mode = "Sample" } },
    { id = "mat_random", label = "Randomize", icon = "rotate", tip = "Randomize color/material in set.", group = "paint", act = "shell_panel", arg = { name = "mat_random" } },
    { id = "mat_gradient", label = "Gradient", icon = "square", tip = "Color gradient across selection.", group = "paint", act = "shell_panel", arg = { name = "mat_gradient" } },
    { id = "mat_tpaint", label = "Terr Paint", icon = "terrain", tip = "Terrain paint panel.", group = "terrain", act = "terrain_paint", panel = "terrain_paint" },
    { id = "mat_treplace", label = "Terr Repl", icon = "rotate", tip = "Terrain replace panel.", group = "terrain", act = "terrain_replace", panel = "terrain_replace" },
    { id = "mat_tpalette", label = "Terr Palette", icon = "terrain", tip = "Terrain palette editor.", group = "terrain", act = "shell_panel", arg = { name = "terrain_materials" } },
    { id = "mat_tcolors", label = "Terr Colors", icon = "square", tip = "Terrain material colors.", group = "terrain", act = "shell_panel", arg = { name = "terrain_colors" } },
    { id = "mat_water", label = "Water Mat", icon = "drop", tip = "Water material/color controls.", group = "terrain", act = "shell_panel", arg = { name = "water_surface" } },
    { id = "mat_new", label = "New Custom", icon = "plus", tip = "Create custom MaterialVariant.", group = "manage", act = "shell_panel", arg = { name = "mat_new" } },
    { id = "mat_edit", label = "Edit Custom", icon = "edit", tip = "Edit custom variant maps.", group = "manage", act = "shell_panel", arg = { name = "mat_new" } },
    { id = "mat_delete", label = "Delete", icon = "close", tip = "Delete custom variant.", group = "manage", act = "mat_delete" },
    { id = "mat_import", label = "Import", icon = "open", tip = "Import material pack JSON.", group = "manage", act = "mat_import", panel = "mat_import" },
    { id = "mat_export", label = "Export", icon = "share", tip = "Export material pack JSON.", group = "manage", act = "mat_export" },
    { id = "mat_audit", label = "Audit", icon = "search", tip = "Find missing textures/variants.", group = "manage", act = "mat_audit" },
    { id = "mat_physical", label = "Physical", icon = "data", tip = "PhysicalProperties editor.", group = "manage", act = "shell_panel", arg = { name = "mat_physical" } },
    { id = "mat_presets", label = "Presets", icon = "save", tip = "Look presets (mat+color+PBR).", group = "library", act = "shell_panel", arg = { name = "mat_presets" } },
    { id = "mat_match", label = "Match Scene", icon = "search", tip = "List all materials used in place.", group = "manage", act = "shell_panel", arg = { name = "mat_used" } },
    { id = "mat_copyprop", label = "Copy Look", icon = "copy", tip = "Copy material+color+PBR to buffer.", group = "manage", act = "mat_copyprop" },
    { id = "mat_pasteprop", label = "Paste Look", icon = "paste", tip = "Paste buffered look to selection.", group = "manage", act = "mat_pasteprop" },
    { id = "mat_swap2", label = "Swap 2 Mats", icon = "rotate", tip = "Swap two materials across scope.", group = "manage", act = "shell_panel", arg = { name = "mat_swap" } },
    { id = "mat_cleanunused", label = "Clean Unused", icon = "minus", tip = "Remove unused custom variants.", group = "manage", act = "mat_cleanunused" },
    { id = "mat_placeset", label = "Set Place Mat", icon = "check", tip = "Set material+color on all parts (undoable).", group = "manage", act = "shell_panel", arg = { name = "mat_placeset" } },
  } }
return T
