-- arkher/registry/tabs02.lua — Game, Home, World, Terrain, Modeler (5x40).
local T = {}
T[#T + 1] = { id = "GAME", label = "Game", icon = "game",
  groups = { { id = "rules", label = "Rules" }, { id = "players", label = "Players" },
    { id = "economy", label = "Economy" }, { id = "modes", label = "Modes" }, { id = "publish", label = "Publish" } },
  commands = {
    { id = "game_rules", label = "Rules", icon = "data", tip = "Game rules panel: win/lose, timers, teams.", group = "rules", act = "shell_panel", arg = { name = "game_rules" } },
    { id = "game_wintimer", label = "Win Timer", icon = "data", tip = "Match timer (seconds) stored in game config.", group = "rules", act = "shell_panel", arg = { name = "game_rules" } },
    { id = "game_friendly", label = "Friendly Fire", icon = "check", tip = "Toggle friendly-fire flag in game config.", group = "rules", act = "game_flag", arg = { key = "friendlyFire" } },
    { id = "game_respawn", label = "Respawn Time", icon = "rotate", tip = "Respawn delay (seconds) in game config.", group = "rules", act = "shell_panel", arg = { name = "game_rules" } },
    { id = "game_maxplayers", label = "Max Players", icon = "playersI", tip = "Max players (Players.MaxPlayers, real).", group = "rules", act = "shell_panel", arg = { name = "game_rules" } },
    { id = "game_respawnloc", label = "Respawn Mode", icon = "pin", tip = "RespawnLocation usage mode.", group = "rules", act = "shell_panel", arg = { name = "game_rules" } },
    { id = "game_spawns", label = "List Spawns", icon = "pin", tip = "List/select all SpawnLocations.", group = "rules", act = "game_listspawns" },
    { id = "game_checkpoints", label = "Checkpoints", icon = "check", tip = "Checkpoint chain manager.", group = "rules", act = "shell_panel", arg = { name = "game_checkpoints" } },
    { id = "game_spawnmgr", label = "Spawn Mgr", icon = "playersI", tip = "Player spawn manager.", group = "players", act = "shell_panel", arg = { name = "game_spawns" } },
    { id = "game_teams", label = "Teams", icon = "people", tip = "Teams manager: create/rename/colors.", group = "players", act = "shell_panel", arg = { name = "game_teams" } },
    { id = "game_leader", label = "Leaderboard", icon = "data", tip = "leaderstats template manager.", group = "players", act = "shell_panel", arg = { name = "game_leader" } },
    { id = "game_badges", label = "Badges", icon = "gem", tip = "Badge list (award via BadgeService at runtime).", group = "players", act = "shell_panel", arg = { name = "game_badges" } },
    { id = "game_kick", label = "Kick Player", icon = "close", tip = "Kick selected player (Play mode only, honest limit).", group = "players", act = "game_mod", arg = { op = "kick" } },
    { id = "game_spectate", label = "Spectate", icon = "view", tip = "Spectate selected player.", group = "players", act = "game_mod", arg = { op = "spectate" } },
    { id = "game_heal", label = "Heal All", icon = "plus", tip = "Set all Humanoids to full health.", group = "players", act = "game_mod", arg = { op = "healall" } },
    { id = "game_resetchar", label = "Reset Chars", icon = "rotate", tip = "Force-respawn all player characters.", group = "players", act = "game_mod", arg = { op = "resetall" } },
    { id = "game_currency", label = "Currency", icon = "gem", tip = "Currency definitions (name, icon, start).", group = "economy", act = "shell_panel", arg = { name = "game_currency" } },
    { id = "game_shop", label = "Shop", icon = "toolbox", tip = "Shop catalog: items, prices, stock.", group = "economy", act = "shell_panel", arg = { name = "game_shop" } },
    { id = "game_gamepass", label = "Gamepasses", icon = "gem", tip = "Gamepass ID registry + test grants.", group = "economy", act = "shell_panel", arg = { name = "game_passes" } },
    { id = "game_devprod", label = "Dev Products", icon = "gem", tip = "Developer product registry.", group = "economy", act = "shell_panel", arg = { name = "game_devprods" } },
    { id = "game_grant", label = "Grant Item", icon = "plus", tip = "Grant catalog item to selected player (preview).", group = "economy", act = "game_grant" },
    { id = "game_wipeecon", label = "Wipe Econ", icon = "minus", tip = "Reset preview economy state.", group = "economy", act = "game_wipeecon" },
    { id = "game_modes", label = "Modes", icon = "game", tip = "Game mode presets: FFA, Teams, Coop, Race.", group = "modes", act = "shell_panel", arg = { name = "game_modes" } },
    { id = "game_rounds", label = "Rounds", icon = "rotate", tip = "Round system: count, intermission, sudden death.", group = "modes", act = "shell_panel", arg = { name = "game_rounds" } },
    { id = "game_vote", label = "Map Vote", icon = "check", tip = "Map voting setup (map list + duration).", group = "modes", act = "shell_panel", arg = { name = "game_vote" } },
    { id = "game_lobby", label = "Lobby", icon = "home", tip = "Lobby config: min players, countdown, spawn.", group = "modes", act = "shell_panel", arg = { name = "game_lobby" } },
    { id = "game_events", label = "Live Events", icon = "play", tip = "Scheduled in-game events.", group = "modes", act = "shell_panel", arg = { name = "game_events" } },
    { id = "game_difficulty", label = "Difficulty", icon = "scaleI", tip = "Difficulty scalars (damage, speed, loot).", group = "modes", act = "shell_panel", arg = { name = "game_difficulty" } },
    { id = "game_quests", label = "Quests", icon = "check", tip = "Quest chain editor.", group = "modes", act = "shell_panel", arg = { name = "game_quests" } },
    { id = "game_daily", label = "Dailies", icon = "repfirst", tip = "Daily reward track.", group = "modes", act = "shell_panel", arg = { name = "game_daily" } },
    { id = "game_forcestart", label = "Force Start", icon = "play", tip = "Force-start match preview now.", group = "modes", act = "game_match", arg = { op = "start" } },
    { id = "game_endmatch", label = "End Match", icon = "close", tip = "Force-end match preview, show results.", group = "modes", act = "game_match", arg = { op = "finish" } },
    { id = "game_icon", label = "Game Icon", icon = "plus", tip = "Set game icon asset id.", group = "publish", act = "shell_panel", arg = { name = "game_icon" } },
    { id = "game_thumb", label = "Thumbnails", icon = "plus", tip = "Thumbnail asset ids.", group = "publish", act = "shell_panel", arg = { name = "game_thumb" } },
    { id = "game_desc", label = "Description", icon = "textA", tip = "Game description + genre + devices.", group = "publish", act = "shell_panel", arg = { name = "game_desc" } },
    { id = "game_access", label = "Access", icon = "lock", tip = "Private/Friends/Public access flag.", group = "publish", act = "shell_panel", arg = { name = "game_access" } },
    { id = "game_age", label = "Age Guide", icon = "info", tip = "Age recommendation + content flags.", group = "publish", act = "shell_panel", arg = { name = "game_age" } },
    { id = "game_update", label = "Update Notes", icon = "note", tip = "Changelog editor.", group = "publish", act = "shell_panel", arg = { name = "game_update" } },
    { id = "game_shutdown", label = "Shutdown", icon = "close", tip = "Shutdown all servers (Play mode; honest limit noted).", group = "publish", act = "game_shutdown" },
    { id = "game_migrate", label = "Migrate", icon = "share", tip = "Migrate players to new version (limit noted).", group = "publish", act = "game_migrate" },
  } }
T[#T + 1] = { id = "HOME", label = "Home", icon = "home",
  groups = { { id = "tools", label = "Tools" }, { id = "build", label = "Build" },
    { id = "style", label = "Style" }, { id = "camera", label = "Camera" }, { id = "help", label = "Help" } },
  commands = {
    { id = "home_select", label = "Select", icon = "select", tip = "Select tool (click/drag).", key = "Ctrl+1", group = "tools", act = "tool_mode", arg = { mode = "Select" } },
    { id = "home_move", label = "Move", icon = "move", tip = "Move tool (drag handles).", key = "Ctrl+2", group = "tools", act = "tool_mode", arg = { mode = "Move" } },
    { id = "home_scale", label = "Scale", icon = "scaleI", tip = "Scale tool.", key = "Ctrl+3", group = "tools", act = "tool_mode", arg = { mode = "Scale" } },
    { id = "home_rotate", label = "Rotate", icon = "rotate", tip = "Rotate tool.", key = "Ctrl+4", group = "tools", act = "tool_mode", arg = { mode = "Rotate" } },
    { id = "home_transform", label = "Transform", icon = "transform", tip = "Combined transform gizmo.", key = "Ctrl+5", group = "tools", act = "tool_mode", arg = { mode = "Transform" } },
    { id = "home_paint", label = "Paint", icon = "drop", tip = "Paint tool: click parts to apply color/material.", group = "tools", act = "tool_mode", arg = { mode = "Paint" } },
    { id = "home_draw", label = "Draw", icon = "edit", tip = "Draw part: drag on grid to size.", group = "tools", act = "tool_mode", arg = { mode = "Draw" } },
    { id = "home_erase", label = "Erase", icon = "close", tip = "Erase tool: click to delete (undoable).", group = "tools", act = "tool_mode", arg = { mode = "Erase" } },
    { id = "home_part", label = "Part", icon = "cubeW", tip = "Insert Part at focus.", group = "build", act = "create", arg = { class = "Part" } },
    { id = "home_group", label = "Group", icon = "group", tip = "Group selection.", key = "Ctrl+G", group = "build", act = "edit_group" },
    { id = "home_ungroup", label = "Ungroup", icon = "ungroup", tip = "Ungroup selection.", key = "Ctrl+U", group = "build", act = "edit_ungroup" },
    { id = "home_lock", label = "Lock", icon = "lock", tip = "Lock selection.", group = "build", act = "edit_lock" },
    { id = "home_anchor", label = "Anchor", icon = "anchor", tip = "Toggle anchor on selection.", group = "build", act = "edit_anchor" },
    { id = "home_play", label = "Play", icon = "play", tip = "Preview-play.", key = "F5", group = "build", act = "run_play" },
    { id = "home_stop", label = "Stop", icon = "close", tip = "Stop preview.", key = "Shift+F5", group = "build", act = "run_stop" },
    { id = "home_undo", label = "Undo", icon = "undo", tip = "Undo last action.", key = "Ctrl+Z", group = "build", act = "edit_undo" },
    { id = "home_color", label = "Color", icon = "drop", tip = "Color picker for selection/paint.", group = "style", act = "shell_panel", arg = { name = "home_color" } },
    { id = "home_material", label = "Material", icon = "terrain", tip = "Material picker for selection/paint.", group = "style", act = "shell_panel", arg = { name = "home_material" } },
    { id = "home_transp", label = "Transparency", icon = "square", tip = "Transparency slider for selection.", group = "style", act = "shell_panel", arg = { name = "home_transp" } },
    { id = "home_reflect", label = "Reflectance", icon = "bulb", tip = "Reflectance slider for selection.", group = "style", act = "shell_panel", arg = { name = "home_reflect" } },
    { id = "home_collision", label = "Collisions", icon = "check", tip = "Toggle collisions on selection.", group = "style", act = "edit_collide", arg = { toggle = true } },
    { id = "home_copy", label = "Copy", icon = "copy", tip = "Copy selection.", key = "Ctrl+C", group = "style", act = "edit_copy" },
    { id = "home_paste", label = "Paste", icon = "paste", tip = "Paste clipboard.", key = "Ctrl+V", group = "style", act = "edit_paste" },
    { id = "home_duplicate", label = "Duplicate", icon = "plus", tip = "Duplicate.", key = "Ctrl+D", group = "style", act = "edit_duplicate" },
    { id = "home_focus", label = "Focus", icon = "search", tip = "Focus selection.", key = "F", group = "camera", act = "view_focus" },
    { id = "home_top", label = "Top View", icon = "camera", tip = "Top camera.", group = "camera", act = "view_camera", arg = { preset = "top" } },
    { id = "home_front", label = "Front View", icon = "camera", tip = "Front camera.", group = "camera", act = "view_camera", arg = { preset = "front" } },
    { id = "home_persp", label = "Persp View", icon = "camera", tip = "Perspective camera.", group = "camera", act = "view_camera", arg = { preset = "persp" } },
    { id = "home_grid", label = "Grid", icon = "dock", tip = "Toggle grid.", group = "camera", act = "settings_toggle", arg = { key = "grid" } },
    { id = "home_snap", label = "Snap", icon = "snap", tip = "Toggle snapping.", group = "camera", act = "settings_toggle", arg = { key = "snap" } },
    { id = "home_explorer", label = "Explorer", icon = "dock", tip = "Toggle Explorer.", group = "camera", act = "shell_toggle", arg = { panel = "explorer" } },
    { id = "home_props", label = "Properties", icon = "data", tip = "Toggle Properties.", group = "camera", act = "shell_toggle", arg = { panel = "props" } },
    { id = "home_welcome", label = "Welcome", icon = "info", tip = "Welcome page: start/learn/templates.", group = "help", act = "shell_panel", arg = { name = "welcome" } },
    { id = "home_tour", label = "Tour", icon = "info", tip = "Guided tour.", group = "help", act = "shell_panel", arg = { name = "tour" } },
    { id = "home_tips", label = "Tips", icon = "bulb", tip = "Tip of the day + tips browser.", group = "help", act = "shell_panel", arg = { name = "tips" } },
    { id = "home_docs", label = "Docs", icon = "note", tip = "In-engine documentation browser.", group = "help", act = "shell_panel", arg = { name = "docs" } },
    { id = "home_about", label = "About", icon = "emblem", tip = "About ARKHER Engine.", group = "help", act = "shell_panel", arg = { name = "about" } },
    { id = "home_feedback", label = "Feedback", icon = "chat", tip = "Send feedback (stored in project).", group = "help", act = "shell_panel", arg = { name = "feedback" } },
    { id = "home_updates", label = "Updates", icon = "cloud", tip = "Engine update notes.", group = "help", act = "shell_panel", arg = { name = "updates" } },
    { id = "home_exit", label = "Exit", icon = "close", tip = "Close engine UI.", group = "help", act = "shell_exit" },
  } }
T[#T + 1] = { id = "WORLD", label = "World", icon = "globe",
  groups = { { id = "time", label = "Time" }, { id = "sky", label = "Sky" },
    { id = "physical", label = "Physical" }, { id = "streaming", label = "Streaming" }, { id = "zones", label = "Zones" } },
  commands = {
    { id = "world_clock", label = "Clock Time", icon = "data", tip = "Lighting.ClockTime slider (real).", group = "time", act = "shell_panel", arg = { name = "world_clock" } },
    { id = "world_daycycle", label = "Day Cycle", icon = "rotate", tip = "Day/night cycle runner (speed, pause).", group = "time", act = "shell_panel", arg = { name = "world_daycycle" } },
    { id = "world_lat", label = "Latitude", icon = "globe", tip = "GeographicLatitude (sun path).", group = "time", act = "shell_panel", arg = { name = "world_clock" } },
    { id = "world_sunposition", label = "Sun Now", icon = "bulb", tip = "Show current sun direction; snap clock to sunrise/noon/sunset.", group = "time", act = "shell_panel", arg = { name = "world_clock" } },
    { id = "world_presets", label = "Time Presets", icon = "bulb", tip = "Dawn/Noon/Dusk/Midnight one-click.", group = "time", act = "shell_panel", arg = { name = "world_presets" } },
    { id = "world_freeze", label = "Freeze Time", icon = "pause", tip = "Stop clock advance (cycle off).", group = "time", act = "world_freezetime" },
    { id = "world_ambience", label = "Ambient", icon = "square", tip = "Ambient color + shift top/bottom.", group = "sky", act = "shell_panel", arg = { name = "world_ambient" } },
    { id = "world_outdoor", label = "OutdoorAmb", icon = "square", tip = "OutdoorAmbient color.", group = "sky", act = "shell_panel", arg = { name = "world_ambient" } },
    { id = "world_brightness", label = "Brightness", icon = "bulb", tip = "Lighting.Brightness slider.", group = "sky", act = "shell_panel", arg = { name = "world_ambient" } },
    { id = "world_fog", label = "Fog", icon = "cloud", tip = "FogEnd/FogColor/FogStart.", group = "sky", act = "shell_panel", arg = { name = "world_fog" } },
    { id = "world_skychange", label = "Skybox", icon = "plus", tip = "Swap Sky (6 faces) from presets.", group = "sky", act = "shell_panel", arg = { name = "world_sky" } },
    { id = "world_stars", label = "Stars", icon = "effects", tip = "Toggle + configure Stars.", group = "sky", act = "shell_panel", arg = { name = "world_sky" } },
    { id = "world_atmo", label = "Atmosphere", icon = "cloud", tip = "Full Atmosphere editor.", group = "sky", act = "shell_panel", arg = { name = "light_atmosphere" } },
    { id = "world_gravity", label = "Gravity", icon = "data", tip = "Workspace.Gravity slider (real).", group = "physical", act = "shell_panel", arg = { name = "world_gravity" } },
    { id = "world_killy", label = "Kill Height", icon = "data", tip = "Read FallenPartsDestroyHeight; set safe floors.", group = "physical", act = "shell_panel", arg = { name = "world_killy" } },
    { id = "world_wind", label = "Wind", icon = "cloud", tip = "GlobalWind vector editor.", group = "physical", act = "shell_panel", arg = { name = "world_wind" } },
    { id = "world_air", label = "Air Density", icon = "data", tip = "Info: read-only in engine; workaround via forces.", group = "physical", act = "shell_panel", arg = { name = "world_limits" } },
    { id = "world_soundscapes", label = "Sound Areas", icon = "note", tip = "Ambient sound regions.", group = "physical", act = "shell_panel", arg = { name = "world_soundareas" } },
    { id = "world_streaming", label = "Streaming", icon = "share", tip = "StreamingEnabled/TargetRadius/MinRadius (real).", group = "streaming", act = "shell_panel", arg = { name = "world_streaming" } },
    { id = "world_persist", label = "Persist API", icon = "save", tip = "Streaming persist/pause helpers.", group = "streaming", act = "shell_panel", arg = { name = "world_streaming" } },
    { id = "world_preload", label = "Preload Area", icon = "open", tip = "RequestStreamAroundAsync at point.", group = "streaming", act = "world_preload" },
    { id = "world_memshow", label = "Mem Report", icon = "data", tip = "Memory usage report.", group = "streaming", act = "shell_panel", arg = { name = "perf_memory" } },
    { id = "world_zoneadd", label = "Add Zone", icon = "boxG", tip = "Create a Zone part here.", group = "zones", act = "game_zone" },
    { id = "world_zonelist", label = "Zone List", icon = "data", tip = "List/select zones.", group = "zones", act = "shell_panel", arg = { name = "world_zones" } },
    { id = "world_zonefx", label = "Zone FX", icon = "effects", tip = "Per-zone lighting/FX overrides.", group = "zones", act = "shell_panel", arg = { name = "world_zonefx" } },
    { id = "world_zonetp", label = "Zone TP", icon = "share", tip = "Teleport volumes setup.", group = "zones", act = "shell_panel", arg = { name = "world_zonetp" } },
    { id = "world_spawnzones", label = "Spawn Zones", icon = "pin", tip = "Assign SpawnLocations to zones.", group = "zones", act = "shell_panel", arg = { name = "world_spawnzones" } },
    { id = "world_pvpzones", label = "PvP Zones", icon = "check", tip = "PvP on/off volumes.", group = "zones", act = "shell_panel", arg = { name = "world_pvp" } },
    { id = "world_safezone", label = "Safe Zone", icon = "lock", tip = "Create safe-zone volume (no damage flag).", group = "zones", act = "world_safezone" },
    { id = "world_music", label = "Zone Music", icon = "note", tip = "Music triggers per zone.", group = "zones", act = "shell_panel", arg = { name = "world_zonemusic" } },
    { id = "world_weather", label = "Weather", icon = "cloud", tip = "Weather system: rain/snow/storm controls.", group = "physical", act = "shell_panel", arg = { name = "env_weather" } },
    { id = "world_seasons", label = "Seasons", icon = "repfirst", tip = "Season tint presets.", group = "physical", act = "shell_panel", arg = { name = "env_seasons" } },
    { id = "world_ocean", label = "Ocean Level", icon = "drop", tip = "Terrain water level (real, via Terrain).", group = "physical", act = "shell_panel", arg = { name = "water_level" } },
    { id = "world_bounds", label = "World Bounds", icon = "boxG", tip = "Playable bounds walls (visible/invisible).", group = "physical", act = "shell_panel", arg = { name = "world_bounds" } },
    { id = "world_minimap", label = "Minimap", icon = "camera", tip = "Minimap generator from top-down capture.", group = "zones", act = "shell_panel", arg = { name = "world_minimap" } },
    { id = "world_maplabel", label = "Map Labels", icon = "textA", tip = "Floating location labels.", group = "zones", act = "shell_panel", arg = { name = "world_maplabels" } },
    { id = "world_lod", label = "LOD", icon = "data", tip = "LOD groups: distance visibility.", group = "streaming", act = "shell_panel", arg = { name = "world_lod" } },
    { id = "world_culling", label = "Culling", icon = "view", tip = "Manual cull volumes.", group = "streaming", act = "shell_panel", arg = { name = "world_culling" } },
    { id = "world_audit", label = "Audit World", icon = "search", tip = "World audit: lighting/streaming/gaps.", group = "streaming", act = "world_audit" },
    { id = "world_defaults", label = "Defaults", icon = "rotate", tip = "Restore default world settings.", group = "sky", act = "world_defaults" },
  } }
T[#T + 1] = { id = "TERRAIN", label = "Terrain", icon = "terrain",
  groups = { { id = "sculpt", label = "Sculpt" }, { id = "paint", label = "Paint" },
    { id = "generate", label = "Generate" }, { id = "water", label = "Water" }, { id = "tools", label = "Tools" } },
  commands = {
    { id = "terrain_draw", label = "Draw", icon = "edit", tip = "Draw terrain: brush size/strength/shape/material UI.", group = "sculpt", act = "terrain_draw", panel = "terrain_draw" },
    { id = "terrain_sculpt", label = "Sculpt", icon = "terrain", tip = "Raise/lower/smooth/flatten sculpt panel.", group = "sculpt", act = "terrain_sculpt", panel = "terrain_sculpt" },
    { id = "terrain_smooth", label = "Smooth", icon = "terrain", tip = "Smooth brush (quick).", group = "sculpt", act = "terrain_brush", arg = { op = "smooth" } },
    { id = "terrain_flatten", label = "Flatten", icon = "terrain", tip = "Flatten brush (quick).", group = "sculpt", act = "terrain_brush", arg = { op = "flatten" } },
    { id = "terrain_erode", label = "Erode", icon = "terrain", tip = "Erosion brush + hydraulic sim panel.", group = "sculpt", act = "terrain_erode", panel = "terrain_erode" },
    { id = "terrain_add", label = "Add", icon = "plus", tip = "Add-material brush (quick).", group = "sculpt", act = "terrain_brush", arg = { op = "add" } },
    { id = "terrain_remove", label = "Subtract", icon = "minus", tip = "Subtract brush (quick).", group = "sculpt", act = "terrain_brush", arg = { op = "remove" } },
    { id = "terrain_grow", label = "Grow", icon = "plus", tip = "Grow brush (expand solid).", group = "sculpt", act = "terrain_brush", arg = { op = "grow" } },
    { id = "terrain_paint", label = "Paint", icon = "drop", tip = "Paint material panel (source->target).", group = "paint", act = "terrain_paint", panel = "terrain_paint" },
    { id = "terrain_replace", label = "Replace", icon = "rotate", tip = "Replace material in region.", group = "paint", act = "terrain_replace", panel = "terrain_replace" },
    { id = "terrain_materials", label = "Materials", icon = "terrain", tip = "Terrain material palette editor.", group = "paint", act = "shell_panel", arg = { name = "terrain_materials" } },
    { id = "terrain_decor", label = "Decor", icon = "effects", tip = "Grass/decoration density by material.", group = "paint", act = "shell_panel", arg = { name = "terrain_decor" } },
    { id = "terrain_colors", label = "Colors", icon = "square", tip = "Per-material color overrides.", group = "paint", act = "shell_panel", arg = { name = "terrain_colors" } },
    { id = "terrain_generate", label = "Generate", icon = "globe", tip = "Procedural islands/hills/canyons generator.", group = "generate", act = "terrain_generate", panel = "terrain_generate" },
    { id = "terrain_heightmap", label = "Heightmap", icon = "plus", tip = "Import heightmap image -> terrain.", group = "generate", act = "terrain_heightmap", panel = "terrain_heightmap" },
    { id = "terrain_stamp", label = "Stamp", icon = "plus", tip = "Stamp saved region at cursor.", group = "generate", act = "terrain_stamp", panel = "terrain_stamp" },
    { id = "terrain_caves", label = "Caves", icon = "minus", tip = "Carve cave tunnels along a path.", group = "generate", act = "terrain_caves", panel = "terrain_caves" },
    { id = "terrain_rivers", label = "Rivers", icon = "drop", tip = "Carve riverbed + fill water.", group = "generate", act = "terrain_rivers", panel = "terrain_rivers" },
    { id = "terrain_fillwater", label = "Fill Water", icon = "drop", tip = "Fill region with water.", group = "water", act = "terrain_water", arg = { op = "fill" } },
    { id = "terrain_drain", label = "Drain", icon = "minus", tip = "Remove water in region.", group = "water", act = "terrain_water", arg = { op = "drain" } },
    { id = "terrain_sealevel", label = "Sea Level", icon = "drop", tip = "Global water level control.", group = "water", act = "shell_panel", arg = { name = "water_level" } },
    { id = "terrain_watercolor", label = "Water Color", icon = "square", tip = "Water color/transparency/wave.", group = "water", act = "shell_panel", arg = { name = "water_surface" } },
    { id = "terrain_region", label = "Region", icon = "boxG", tip = "Select/copy/paste terrain regions.", group = "tools", act = "terrain_region", panel = "terrain_region" },
    { id = "terrain_copy", label = "Copy Region", icon = "copy", tip = "Copy terrain region to buffer.", group = "tools", act = "terrain_copy" },
    { id = "terrain_paste", label = "Paste Region", icon = "paste", tip = "Paste terrain buffer at cursor.", group = "tools", act = "terrain_paste" },
    { id = "terrain_clear", label = "Clear All", icon = "close", tip = "Clear all terrain (undoable backup).", group = "tools", act = "terrain_clear" },
    { id = "terrain_fillall", label = "Fill All", icon = "plus", tip = "Fill base with material (undoable).", group = "tools", act = "terrain_fillall", panel = "terrain_fillall" },
    { id = "terrain_readvox", label = "Read Voxels", icon = "data", tip = "Inspect voxel occupancy/material at point.", group = "tools", act = "terrain_readvox" },
    { id = "terrain_preview", label = "Preview", icon = "view", tip = "Before/after preview for last op.", group = "tools", act = "terrain_preview" },
    { id = "terrain_settings", label = "Settings", icon = "settings", tip = "Water/grass/voxel settings.", group = "tools", act = "shell_panel", arg = { name = "terrain_settings" } },
    { id = "terrain_undo", label = "T Undo", icon = "undo", tip = "Undo terrain op.", group = "tools", act = "edit_undo" },
    { id = "terrain_brushsize", label = "Brush Size", icon = "data", tip = "Quick brush size.", group = "sculpt", act = "shell_panel", arg = { name = "terrain_draw" } },
    { id = "terrain_autosmooth", label = "Auto Smooth", icon = "check", tip = "Auto-smooth after each stroke.", group = "sculpt", act = "settings_toggle", arg = { key = "terrain_autosmooth" } },
    { id = "terrain_symmetry", label = "Symmetry", icon = "share", tip = "Mirror strokes across axis.", group = "sculpt", act = "shell_panel", arg = { name = "terrain_symmetry" } },
    { id = "terrain_mask", label = "Mask", icon = "lock", tip = "Protect material/height with mask.", group = "paint", act = "shell_panel", arg = { name = "terrain_mask" } },
    { id = "terrain_layers", label = "Layers", icon = "data", tip = "Height layers stack view.", group = "generate", act = "shell_panel", arg = { name = "terrain_layers" } },
    { id = "terrain_export", label = "Export HMap", icon = "share", tip = "Export heightmap data (JSON).", group = "generate", act = "terrain_export" },
    { id = "terrain_import", label = "Import Vox", icon = "open", tip = "Import voxel JSON.", group = "generate", act = "terrain_import", panel = "terrain_import" },
    { id = "terrain_crater", label = "Crater", icon = "minus", tip = "Crater stamp brush.", group = "generate", act = "terrain_brush", arg = { op = "crater" } },
    { id = "terrain_plateau", label = "Plateau", icon = "plus", tip = "Plateau stamp brush.", group = "generate", act = "terrain_brush", arg = { op = "plateau" } },
  } }
T[#T + 1] = { id = "MODELER", label = "Modeler", icon = "model",
  groups = { { id = "create", label = "Create" }, { id = "mesh", label = "Mesh" },
    { id = "deform", label = "Deform" }, { id = "surface", label = "Surface" }, { id = "tools", label = "Tools" } },
  commands = {
    { id = "model_extrude", label = "Extrude", icon = "plus", tip = "Extrude: face/region offset panel (EditableMesh where available).", group = "create", act = "model_extrude", panel = "model_extrude" },
    { id = "model_bevel", label = "Bevel", icon = "model", tip = "Bevel edges panel (segments/amount).", group = "create", act = "model_bevel", panel = "model_bevel" },
    { id = "model_inset", label = "Inset", icon = "minus", tip = "Inset faces panel.", group = "create", act = "model_inset", panel = "model_inset" },
    { id = "model_bridge", label = "Bridge", icon = "share", tip = "Bridge two edge loops.", group = "create", act = "model_bridge", panel = "model_bridge" },
    { id = "model_merge", label = "Merge", icon = "group", tip = "Merge vertices/parts.", group = "create", act = "model_merge", panel = "model_merge" },
    { id = "model_split", label = "Split", icon = "cut", tip = "Split mesh/parts apart.", group = "create", act = "model_split", panel = "model_split" },
    { id = "model_cut", label = "Knife Cut", icon = "cut", tip = "Cut along drawn line.", group = "create", act = "tool_mode", arg = { mode = "Knife" } },
    { id = "model_subdiv", label = "Subdivide", icon = "plus", tip = "Subdivide faces.", group = "create", act = "model_subdiv" },
    { id = "model_vertex", label = "Vertex Mode", icon = "select", tip = "Edit vertices (EditableMesh).", group = "mesh", act = "tool_mode", arg = { mode = "VertexEdit" } },
    { id = "model_edge", label = "Edge Mode", icon = "select", tip = "Edit edges.", group = "mesh", act = "tool_mode", arg = { mode = "EdgeEdit" } },
    { id = "model_face", label = "Face Mode", icon = "select", tip = "Edit faces.", group = "mesh", act = "tool_mode", arg = { mode = "FaceEdit" } },
    { id = "model_weld", label = "Weld", icon = "pin", tip = "Weld parts (WeldConstraint).", group = "mesh", act = "model_weld" },
    { id = "model_union", label = "Union", icon = "group", tip = "Union selection (CSG via server bridge).", group = "mesh", act = "model_boolean", arg = { op = "union" } },
    { id = "model_subtract", label = "Subtract", icon = "minus", tip = "Negate-then-union (CSG via server bridge).", group = "mesh", act = "model_boolean", arg = { op = "subtract" } },
    { id = "model_intersect", label = "Intersect", icon = "plus", tip = "Intersect selection (CSG via server bridge).", group = "mesh", act = "model_boolean", arg = { op = "intersect" } },
    { id = "model_separate", label = "Separate", icon = "ungroup", tip = "Separate a Union back to parts (limit noted).", group = "mesh", act = "model_separate" },
    { id = "model_bend", label = "Bend", icon = "transform", tip = "Bend deformer.", group = "deform", act = "model_deform", arg = { kind = "bend" }, panel = "model_deform" },
    { id = "model_twist", label = "Twist", icon = "rotate", tip = "Twist deformer.", group = "deform", act = "model_deform", arg = { kind = "twist" }, panel = "model_deform" },
    { id = "model_taper", label = "Taper", icon = "transform", tip = "Taper deformer.", group = "deform", act = "model_deform", arg = { kind = "taper" }, panel = "model_deform" },
    { id = "model_lattice", label = "Lattice", icon = "boxG", tip = "Lattice cage deform.", group = "deform", act = "tool_mode", arg = { mode = "Lattice" } },
    { id = "model_sym", label = "Symmetry", icon = "share", tip = "Mirror modeling across axis.", group = "deform", act = "shell_panel", arg = { name = "model_sym" } },
    { id = "model_array", label = "Array", icon = "copy", tip = "Linear/radial array copies.", group = "deform", act = "model_array", panel = "model_array" },
    { id = "model_mirror", label = "Mirror Mesh", icon = "share", tip = "Mirror geometry across axis (part-level real).", group = "deform", act = "model_mirror", panel = "model_mirror" },
    { id = "model_uv", label = "UV Editor", icon = "plus", tip = "UV/Texture offset-scale editor.", group = "surface", act = "shell_panel", arg = { name = "model_uv" } },
    { id = "model_normals", label = "Normals", icon = "data", tip = "Recalculate/flip normals.", group = "surface", act = "model_normals" },
    { id = "model_smooth", label = "Smooth Shade", icon = "bulb", tip = "Smooth vs flat shading toggle.", group = "surface", act = "model_smoothshade" },
    { id = "model_decimate", label = "Decimate", icon = "minus", tip = "Reduce triangle count (EditableMesh).", group = "surface", act = "model_decimate", panel = "model_decimate" },
    { id = "model_remesh", label = "Remesh", icon = "rotate", tip = "Uniform remesh (voxel size).", group = "surface", act = "model_remesh", panel = "model_remesh" },
    { id = "model_bake", label = "Bake", icon = "save", tip = "Bake mesh to MeshPart asset (limit noted).", group = "surface", act = "model_bake" },
    { id = "model_measure", label = "Measure", icon = "scaleI", tip = "Measure mesh dimensions.", group = "tools", act = "tool_mode", arg = { mode = "Measure" } },
    { id = "model_pivot", label = "Pivot", icon = "share", tip = "Set/show model pivot.", group = "tools", act = "shell_panel", arg = { name = "model_pivot" } },
    { id = "model_origin", label = "Set Origin", icon = "pin", tip = "Move origin to cursor/center/bottom.", group = "tools", act = "shell_panel", arg = { name = "model_pivot" } },
    { id = "model_freeze", label = "Freeze Xf", icon = "lock", tip = "Freeze transforms into geometry.", group = "tools", act = "model_freeze" },
    { id = "model_resetxf", label = "Reset Xf", icon = "rotate", tip = "Reset transforms (keep shape).", group = "tools", act = "model_resetxf" },
    { id = "model_cleanup", label = "Cleanup", icon = "minus", tip = "Remove doubles, loose, degenerate.", group = "tools", act = "model_cleanup" },
    { id = "model_stats", label = "Mesh Stats", icon = "data", tip = "Verts/tris/parts report.", group = "tools", act = "shell_panel", arg = { name = "model_stats" } },
    { id = "model_export", label = "Export Mesh", icon = "share", tip = "Export mesh JSON/OBJ-ish.", group = "tools", act = "model_export" },
    { id = "model_import", label = "Import Mesh", icon = "open", tip = "Import mesh JSON to EditableMesh.", group = "tools", act = "model_import", panel = "model_import" },
    { id = "model_limits", label = "Limits", icon = "info", tip = "Honest CSG/EditableMesh limits + workarounds.", group = "tools", act = "shell_panel", arg = { name = "model_limits" } },
    { id = "model_snap", label = "Snap Opts", icon = "snap", tip = "Vertex/edge/face snapping options.", group = "tools", act = "shell_panel", arg = { name = "snap_settings" } },
  } }
return T
