-- arkher/registry/tabs01.lua — File, Edit, View, Insert, Run (5x40).
local T = {}
T[#T + 1] = { id = "FILE", label = "File", icon = "file",
  groups = { { id = "project", label = "Project" }, { id = "files", label = "Files" },
    { id = "transfer", label = "Transfer" }, { id = "versions", label = "Versions" }, { id = "config", label = "Config" } },
  commands = {
    { id = "file_new", label = "New Project", icon = "plus", tip = "New project: safe-clears Workspace into Baseplate, keeps engine UI.", key = "Ctrl+N", group = "project", act = "project_new", panel = "project_new" },
    { id = "file_open", label = "Open", icon = "open", tip = "Open a saved project (JSON in ServerStorage) or Baseplate/Empty/Terrain.", group = "project", act = "project_open", panel = "project_open" },
    { id = "file_save", label = "Save", icon = "save", tip = "Save project snapshot now (Workspace+Lighting+Terrain metadata).", key = "Ctrl+S", group = "project", act = "project_save" },
    { id = "file_saveas", label = "Save As", icon = "save", tip = "Save project under a new name/slot.", group = "project", act = "project_saveas", panel = "project_saveas" },
    { id = "file_revert", label = "Revert", icon = "rotate", tip = "Discard unsaved changes, reload last save.", group = "project", act = "project_revert" },
    { id = "file_close", label = "Close", icon = "close", tip = "Close project (clears Workspace to Empty).", group = "project", act = "project_close" },
    { id = "file_newplace", label = "New Place", icon = "plus", tip = "Register a new place slot in this project.", group = "project", act = "project_newplace" },
    { id = "file_recent", label = "Recent", icon = "repfirst", tip = "Open a recently used project.", group = "project", act = "shell_panel", arg = { name = "project_recent" } },
    { id = "file_autosave", label = "Autosave", icon = "check", tip = "Toggle autosave every 5 minutes.", key = "", group = "project", act = "settings_toggle", arg = { key = "autosave" } },
    { id = "file_projinfo", label = "Proj Info", icon = "info", tip = "Project stats: instances, scripts, size estimate.", group = "project", act = "shell_panel", arg = { name = "project_info" } },
    { id = "file_newfolder", label = "New Folder", icon = "folder", tip = "Create a Folder in Workspace.", group = "files", act = "create", arg = { class = "Folder" } },
    { id = "file_newscript", label = "New Script", icon = "script", tip = "Create a server Script in ServerScriptService.", group = "files", act = "create", arg = { class = "Script", parent = "ServerScriptService" } },
    { id = "file_newmodule", label = "New Module", icon = "script", tip = "Create a ModuleScript in ReplicatedStorage.", group = "files", act = "create", arg = { class = "ModuleScript", parent = "ReplicatedStorage" } },
    { id = "file_newlocal", label = "New Local", icon = "script", tip = "Create a LocalScript in StarterPlayerScripts.", group = "files", act = "create", arg = { class = "LocalScript", parent = "StarterPlayerScripts" } },
    { id = "file_import", label = "Import", icon = "folder", tip = "Import JSON (model/UI/mesh data) into the project.", group = "files", act = "project_import", panel = "project_import" },
    { id = "file_exportsel", label = "Export Sel", icon = "share", tip = "Export selection to JSON (shows + stores in project).", group = "files", act = "project_exportsel", panel = "project_export" },
    { id = "file_manage", label = "Manage", icon = "data", tip = "File manager: browse/rename/delete project files.", group = "files", act = "shell_panel", arg = { name = "files" } },
    { id = "file_dupplace", label = "Dupl Place", icon = "copy", tip = "Duplicate current place slot.", group = "files", act = "project_dupplace" },
    { id = "file_archive", label = "Archive", icon = "folderP", tip = "Archive project to a compressed JSON slot.", group = "files", act = "project_archive" },
    { id = "file_templates", label = "Templates", icon = "dock", tip = "Start from a template: Baseplate, Empty, Terrain, Obby kit.", group = "files", act = "shell_panel", arg = { name = "templates" } },
    { id = "file_exportplace", label = "Export Place", icon = "share", tip = "Export whole place metadata to JSON.", group = "transfer", act = "project_exportplace" },
    { id = "file_importplace", label = "Import Place", icon = "open", tip = "Import place JSON (rebuilds instances).", group = "transfer", act = "project_importplace", panel = "project_import" },
    { id = "file_publish", label = "Publish", icon = "cloud", tip = "Publish flow: validates, then guides real Studio publish.", group = "transfer", act = "project_publish", panel = "project_publish" },
    { id = "file_cloudsave", label = "Cloud Save", icon = "cloud", tip = "Save project JSON to Arkher Cloud slot.", group = "transfer", act = "project_cloudsave" },
    { id = "file_cloudopen", label = "Cloud Open", icon = "cloud", tip = "Load project JSON from Arkher Cloud slot.", group = "transfer", act = "project_cloudopen", panel = "project_cloud" },
    { id = "file_cloudstatus", label = "Cloud Info", icon = "info", tip = "Cloud slots, quota and status.", group = "transfer", act = "shell_panel", arg = { name = "cloud" } },
    { id = "file_history", label = "History", icon = "repfirst", tip = "Version history: list, restore, compare.", group = "versions", act = "shell_panel", arg = { name = "versions" } },
    { id = "file_backup", label = "Backup Now", icon = "save", tip = "Write an immediate backup snapshot.", group = "versions", act = "project_backup" },
    { id = "file_backupset", label = "Backup Opts", icon = "settings", tip = "Backup schedule, slots and retention.", group = "versions", act = "shell_panel", arg = { name = "backup" } },
    { id = "file_restore", label = "Restore", icon = "undo", tip = "Restore project from backup/version.", group = "versions", act = "project_restore", panel = "project_restore" },
    { id = "file_snapshot", label = "Snapshot", icon = "camera", tip = "Named snapshot of current state.", group = "versions", act = "project_snapshot", panel = "project_snapshot" },
    { id = "file_diff", label = "Compare", icon = "search", tip = "Compare two versions (instance diff).", group = "versions", act = "shell_panel", arg = { name = "versions_diff" } },
    { id = "file_settings", label = "Proj Settings", icon = "settings", tip = "Project settings: name, genre, permissions.", group = "config", act = "shell_panel", arg = { name = "project_settings" } },
    { id = "file_perms", label = "Permissions", icon = "lock", tip = "Who can edit: roles and locks.", group = "config", act = "shell_panel", arg = { name = "permissions" } },
    { id = "file_locale", label = "Language", icon = "globe", tip = "Project locale strings manager.", group = "config", act = "shell_panel", arg = { name = "localization" } },
    { id = "file_cleanup", label = "Cleanup", icon = "minus", tip = "Remove unanchored/unused debris (with undo).", group = "config", act = "project_cleanup" },
    { id = "file_validate", label = "Validate", icon = "check", tip = "Validate project: errors, warnings, fixes.", group = "config", act = "project_validate", panel = "project_validate" },
    { id = "file_collab", label = "Team", icon = "people", tip = "Team panel: invites and presence.", group = "config", act = "shell_panel", arg = { name = "team" } },
    { id = "file_doctor", label = "Doctor", icon = "search", tip = "Diagnose common project issues.", group = "config", act = "project_validate" },
    { id = "file_exit", label = "Exit Engine", icon = "close", tip = "Close the ARKHER engine UI (project stays).", group = "config", act = "shell_exit" },
  } }
T[#T + 1] = { id = "EDIT", label = "Edit", icon = "edit",
  groups = { { id = "history", label = "History" }, { id = "clipboard", label = "Clipboard" },
    { id = "arrange", label = "Arrange" }, { id = "select", label = "Select" }, { id = "advanced", label = "Advanced" } },
  commands = {
    { id = "edit_undo", label = "Undo", icon = "undo", tip = "Undo last action (grouped ops undo together).", key = "Ctrl+Z", group = "history", act = "edit_undo" },
    { id = "edit_redo", label = "Redo", icon = "redo", tip = "Redo undone action.", key = "Ctrl+Y", group = "history", act = "edit_redo" },
    { id = "edit_history", label = "History", icon = "repfirst", tip = "Action history list; jump to any point.", group = "history", act = "shell_panel", arg = { name = "edit_history" } },
    { id = "edit_repeat", label = "Repeat", icon = "redo", tip = "Repeat last command.", key = "Ctrl+Shift+Z", group = "history", act = "edit_repeat" },
    { id = "edit_clearhist", label = "Clear Hist", icon = "minus", tip = "Clear undo history (frees memory).", group = "history", act = "edit_clearhistory" },
    { id = "edit_cut", label = "Cut", icon = "cut", tip = "Cut selection to clipboard.", key = "Ctrl+X", group = "clipboard", act = "edit_cut" },
    { id = "edit_copy", label = "Copy", icon = "copy", tip = "Copy selection to clipboard.", key = "Ctrl+C", group = "clipboard", act = "edit_copy" },
    { id = "edit_paste", label = "Paste", icon = "paste", tip = "Paste clipboard into Workspace.", key = "Ctrl+V", group = "clipboard", act = "edit_paste" },
    { id = "edit_pasteinto", label = "Paste Into", icon = "paste", tip = "Paste clipboard inside current selection.", group = "clipboard", act = "edit_pasteinto" },
    { id = "edit_duplicate", label = "Duplicate", icon = "plus", tip = "Duplicate selection in place.", key = "Ctrl+D", group = "clipboard", act = "edit_duplicate" },
    { id = "edit_delete", label = "Delete", icon = "close", tip = "Delete selection (undoable).", key = "Del", group = "clipboard", act = "edit_delete" },
    { id = "edit_rename", label = "Rename", icon = "textA", tip = "Rename selection.", key = "F2", group = "clipboard", act = "edit_rename", panel = "edit_rename" },
    { id = "edit_copypath", label = "Copy Path", icon = "copy", tip = "Show + store full path of selection (Studio has no text clipboard).", group = "clipboard", act = "edit_copypath" },
    { id = "edit_group", label = "Group", icon = "group", tip = "Group selection into a Model.", key = "Ctrl+G", group = "arrange", act = "edit_group" },
    { id = "edit_ungroup", label = "Ungroup", icon = "ungroup", tip = "Ungroup selected Models.", key = "Ctrl+U", group = "arrange", act = "edit_ungroup" },
    { id = "edit_lock", label = "Lock", icon = "lock", tip = "Lock selection (Locked=true, undoable).", group = "arrange", act = "edit_lock" },
    { id = "edit_unlock", label = "Unlock", icon = "lock", tip = "Unlock selection.", group = "arrange", act = "edit_unlock" },
    { id = "edit_hide", label = "Hide", icon = "view", tip = "Hide selection (Transparency=1, keeps collisions).", group = "arrange", act = "edit_hide" },
    { id = "edit_unhide", label = "Unhide All", icon = "view", tip = "Restore hidden objects.", group = "arrange", act = "edit_unhide" },
    { id = "edit_anchor", label = "Anchor", icon = "anchor", tip = "Toggle Anchored on selection.", group = "arrange", act = "edit_anchor" },
    { id = "edit_unanchor", label = "Unanchor", icon = "anchor", tip = "Unanchor selection (falls with physics).", group = "arrange", act = "edit_unanchor" },
    { id = "edit_colon", label = "Collide On", icon = "check", tip = "CanCollide=true on selection.", group = "arrange", act = "edit_collide", arg = { value = true } },
    { id = "edit_coloff", label = "Collide Off", icon = "close", tip = "CanCollide=false on selection.", group = "arrange", act = "edit_collide", arg = { value = false } },
    { id = "edit_selall", label = "Select All", icon = "select", tip = "Select all editable Workspace descendants.", key = "Ctrl+A", group = "select", act = "sel_all" },
    { id = "edit_selnone", label = "Select None", icon = "select", tip = "Clear selection.", key = "Esc", group = "select", act = "sel_none" },
    { id = "edit_selinvert", label = "Invert Sel", icon = "select", tip = "Invert current selection.", group = "select", act = "sel_invert" },
    { id = "edit_selchildren", label = "Sel Children", icon = "select", tip = "Select children of current selection.", group = "select", act = "sel_children" },
    { id = "edit_selparent", label = "Sel Parent", icon = "select", tip = "Select parents of current selection.", group = "select", act = "sel_parent" },
    { id = "edit_selsimilar", label = "Sel Similar", icon = "select", tip = "Select all of same ClassName.", group = "select", act = "sel_similar" },
    { id = "edit_boxsel", label = "Box Select", icon = "select", tip = "Drag a box in viewport to select.", group = "select", act = "tool_mode", arg = { mode = "BoxSelect" } },
    { id = "edit_lasso", label = "Lasso", icon = "select", tip = "Freehand lasso selection (approximated by segments).", group = "select", act = "tool_mode", arg = { mode = "LassoSelect" } },
    { id = "edit_snap", label = "Snap Setup", icon = "snap", tip = "Grid/angle snap increments.", group = "advanced", act = "shell_panel", arg = { name = "snap_settings" } },
    { id = "edit_pivotreset", label = "Reset Pivot", icon = "share", tip = "Reset Model pivots to bounds center.", group = "advanced", act = "edit_pivotreset" },
    { id = "edit_alignx", label = "Align X", icon = "share", tip = "Align selection centers on X.", group = "advanced", act = "edit_align", arg = { axis = "X" } },
    { id = "edit_aligny", label = "Align Y", icon = "share", tip = "Align selection centers on Y.", group = "advanced", act = "edit_align", arg = { axis = "Y" } },
    { id = "edit_alignz", label = "Align Z", icon = "share", tip = "Align selection centers on Z.", group = "advanced", act = "edit_align", arg = { axis = "Z" } },
    { id = "edit_distx", label = "Dist X", icon = "share", tip = "Distribute selection evenly on X.", group = "advanced", act = "edit_distribute", arg = { axis = "X" } },
    { id = "edit_disty", label = "Dist Y", icon = "share", tip = "Distribute selection evenly on Y.", group = "advanced", act = "edit_distribute", arg = { axis = "Y" } },
    { id = "edit_distz", label = "Dist Z", icon = "share", tip = "Distribute selection evenly on Z.", group = "advanced", act = "edit_distribute", arg = { axis = "Z" } },
    { id = "edit_mirrorx", label = "Mirror X", icon = "share", tip = "Mirror selection across X (copies).", group = "advanced", act = "edit_mirror", arg = { axis = "X" } },
  } }
T[#T + 1] = { id = "VIEW", label = "View", icon = "view",
  groups = { { id = "panels", label = "Panels" }, { id = "camera", label = "Camera" },
    { id = "display", label = "Display" }, { id = "layout", label = "Layout" }, { id = "assist", label = "Assist" } },
  commands = {
    { id = "view_explorer", label = "Explorer", icon = "dock", tip = "Toggle Explorer panel.", key = "", group = "panels", act = "shell_toggle", arg = { panel = "explorer" } },
    { id = "view_props", label = "Properties", icon = "data", tip = "Toggle Properties panel.", group = "panels", act = "shell_toggle", arg = { panel = "props" } },
    { id = "view_output", label = "Output", icon = "textA", tip = "Toggle Output panel.", group = "panels", act = "shell_toggle", arg = { panel = "output" } },
    { id = "view_console", label = "Console", icon = "textA", tip = "Toggle command console (executes Lua).", group = "panels", act = "shell_toggle", arg = { panel = "console" } },
    { id = "view_problems", label = "Problems", icon = "close", tip = "Toggle Problems panel (errors/warnings).", group = "panels", act = "shell_toggle", arg = { panel = "problems" } },
    { id = "view_toolbox", label = "Toolbox", icon = "toolbox", tip = "Toggle Toolbox panel.", group = "panels", act = "shell_toggle", arg = { panel = "toolbox" } },
    { id = "view_statusbar", label = "Status Bar", icon = "dock", tip = "Toggle bottom status bar.", group = "panels", act = "shell_toggle", arg = { panel = "statusbar" } },
    { id = "view_vpbar", label = "Viewport Bar", icon = "camera", tip = "Toggle viewport toolbar.", group = "panels", act = "shell_toggle", arg = { panel = "vpbar" } },
    { id = "view_camfront", label = "Front", icon = "camera", tip = "Camera to front view.", key = "Num1", group = "camera", act = "view_camera", arg = { preset = "front" } },
    { id = "view_camback", label = "Back", icon = "camera", tip = "Camera to back view.", group = "camera", act = "view_camera", arg = { preset = "back" } },
    { id = "view_camleft", label = "Left", icon = "camera", tip = "Camera to left view.", group = "camera", act = "view_camera", arg = { preset = "left" } },
    { id = "view_camright", label = "Right", icon = "camera", tip = "Camera to right view.", group = "camera", act = "view_camera", arg = { preset = "right" } },
    { id = "view_camtop", label = "Top", icon = "camera", tip = "Camera to top view.", group = "camera", act = "view_camera", arg = { preset = "top" } },
    { id = "view_cambottom", label = "Bottom", icon = "camera", tip = "Camera to bottom view.", group = "camera", act = "view_camera", arg = { preset = "bottom" } },
    { id = "view_campersp", label = "Persp", icon = "camera", tip = "Perspective projection.", group = "camera", act = "view_camera", arg = { preset = "persp" } },
    { id = "view_fov", label = "FOV", icon = "camera", tip = "Field of view + near/far planes.", group = "camera", act = "shell_panel", arg = { name = "camera_fov" } },
    { id = "view_focus", label = "Focus", icon = "search", tip = "Frame camera on selection.", key = "F", group = "camera", act = "view_focus" },
    { id = "view_frameall", label = "Frame All", icon = "expand", tip = "Frame camera on all content.", key = "Shift+F", group = "camera", act = "view_frameall" },
    { id = "view_orbit", label = "Orbit", icon = "rotate", tip = "Orbit camera mode (drag).", group = "camera", act = "tool_mode", arg = { mode = "Camera" } },
    { id = "view_grid", label = "Grid", icon = "dock", tip = "Toggle grid overlay (drawn guides).", group = "display", act = "settings_toggle", arg = { key = "grid" } },
    { id = "view_snapvis", label = "Snap Vis", icon = "snap", tip = "Show snap increments overlay.", group = "display", act = "settings_toggle", arg = { key = "snapvis" } },
    { id = "view_uiscaleup", label = "UI Bigger", icon = "plus", tip = "Increase engine UI scale.", key = "Ctrl+=", group = "display", act = "view_uiscale", arg = { delta = 0.1 } },
    { id = "view_uiscaledn", label = "UI Smaller", icon = "minus", tip = "Decrease engine UI scale.", key = "Ctrl+-", group = "display", act = "view_uiscale", arg = { delta = -0.1 } },
    { id = "view_uiscalereset", label = "UI 100%", icon = "expand", tip = "Reset UI scale to 100%.", group = "display", act = "view_uiscale", arg = { set = 1 } },
    { id = "view_theme", label = "Theme", icon = "bulb", tip = "Theme + contrast controls.", group = "display", act = "shell_panel", arg = { name = "theme" } },
    { id = "view_contrast", label = "Contrast+", icon = "bulb", tip = "Toggle high-contrast theme.", group = "display", act = "settings_toggle", arg = { key = "contrast" } },
    { id = "view_focusmode", label = "Focus Mode", icon = "expand", tip = "Hide side panels, keep viewport.", group = "layout", act = "view_focusmode" },
    { id = "view_zen", label = "Zen", icon = "expand", tip = "Hide all panels (Esc restores).", group = "layout", act = "view_zen" },
    { id = "view_layoutsave", label = "Save Layout", icon = "save", tip = "Save panel layout preset.", group = "layout", act = "view_layout", arg = { op = "save" } },
    { id = "view_layoutload", label = "Load Layout", icon = "open", tip = "Load panel layout preset.", group = "layout", act = "view_layout", arg = { op = "load" } },
    { id = "view_layoutreset", label = "Reset Layout", icon = "rotate", tip = "Restore default layout.", group = "layout", act = "view_layout", arg = { op = "reset" } },
    { id = "view_measure", label = "Measure", icon = "scaleI", tip = "Measure distance between two clicks.", group = "assist", act = "tool_mode", arg = { mode = "Measure" } },
    { id = "view_ruler", label = "Rulers", icon = "scaleI", tip = "Toggle viewport rulers.", group = "assist", act = "settings_toggle", arg = { key = "rulers" } },
    { id = "view_coords", label = "Coords", icon = "data", tip = "Show cursor world coordinates.", group = "assist", act = "settings_toggle", arg = { key = "coords" } },
    { id = "view_stats", label = "Stats Bar", icon = "data", tip = "FPS/parts/memory mini-stats.", group = "assist", act = "shell_toggle", arg = { panel = "ministats" } },
    { id = "view_tooltips", label = "Tooltips", icon = "info", tip = "Toggle rich tooltips.", group = "assist", act = "settings_toggle", arg = { key = "tooltips" } },
    { id = "view_guidedtour", label = "Tour", icon = "info", tip = "Guided tour of the engine UI.", group = "assist", act = "shell_panel", arg = { name = "tour" } },
    { id = "view_shortcuts", label = "Shortcuts", icon = "textA", tip = "Shortcut map + remap.", group = "assist", act = "shell_panel", arg = { name = "shortcuts" } },
    { id = "view_cmdpalette", label = "Cmd Palette", icon = "search", tip = "Command palette: fuzzy-find any command.", key = "Ctrl+K", group = "assist", act = "shell_panel", arg = { name = "cmdpalette" } },
    { id = "view_copycam", label = "Copy Cam", icon = "camera", tip = "Copy camera CFrame to Output.", group = "assist", act = "view_copycam" },
  } }
T[#T + 1] = { id = "INSERT", label = "Insert", icon = "insert",
  groups = { { id = "basic", label = "Basic" }, { id = "containers", label = "Containers" },
    { id = "code", label = "Code" }, { id = "av", label = "Audio-Visual" }, { id = "gui", label = "GUI" }, { id = "gameplay", label = "Gameplay" } },
  commands = {
    { id = "ins_block", label = "Block", icon = "cubeW", tip = "Insert Part (Block).", group = "basic", act = "create", arg = { class = "Part", shape = "Block" } },
    { id = "ins_wedge", label = "Wedge", icon = "plus", tip = "Insert WedgePart.", group = "basic", act = "create", arg = { class = "WedgePart" } },
    { id = "ins_corner", label = "Corner", icon = "plus", tip = "Insert CornerWedgePart.", group = "basic", act = "create", arg = { class = "CornerWedgePart" } },
    { id = "ins_cyl", label = "Cylinder", icon = "plus", tip = "Insert Part (Cylinder).", group = "basic", act = "create", arg = { class = "Part", shape = "Cylinder" } },
    { id = "ins_ball", label = "Ball", icon = "plus", tip = "Insert Part (Ball).", group = "basic", act = "create", arg = { class = "Part", shape = "Ball" } },
    { id = "ins_truss", label = "Truss", icon = "plus", tip = "Insert TrussPart.", group = "basic", act = "create", arg = { class = "TrussPart" } },
    { id = "ins_meshpart", label = "MeshPart", icon = "model", tip = "Insert MeshPart (assign MeshId in Properties).", group = "basic", act = "create", arg = { class = "MeshPart" } },
    { id = "ins_full", label = "Full List", icon = "plus", tip = "Full class catalog with filters.", group = "basic", act = "shell_panel", arg = { name = "insert_full" } },
    { id = "ins_folder", label = "Folder", icon = "folder", tip = "Insert Folder.", group = "containers", act = "create", arg = { class = "Folder" } },
    { id = "ins_model", label = "Model", icon = "model", tip = "Insert Model.", group = "containers", act = "create", arg = { class = "Model" } },
    { id = "ins_tool", label = "Tool", icon = "toolbox", tip = "Insert Tool (equippable).", group = "containers", act = "create", arg = { class = "Tool" } },
    { id = "ins_attachment", label = "Attachment", icon = "pin", tip = "Insert Attachment into selection (or Workspace).", group = "containers", act = "phys_attachment" },
    { id = "ins_script", label = "Script", icon = "script", tip = "Insert server Script.", group = "code", act = "create", arg = { class = "Script", parent = "ServerScriptService" } },
    { id = "ins_localscript", label = "LocalScript", icon = "script", tip = "Insert LocalScript.", group = "code", act = "create", arg = { class = "LocalScript", parent = "StarterPlayerScripts" } },
    { id = "ins_module", label = "Module", icon = "script", tip = "Insert ModuleScript.", group = "code", act = "create", arg = { class = "ModuleScript", parent = "ReplicatedStorage" } },
    { id = "ins_bindable", label = "BindableEvent", icon = "script", tip = "Insert BindableEvent.", group = "code", act = "create", arg = { class = "BindableEvent", parent = "ReplicatedStorage" } },
    { id = "ins_sound", label = "Sound", icon = "note", tip = "Insert Sound (set SoundId in Properties or Audio tab).", group = "av", act = "create", arg = { class = "Sound" } },
    { id = "ins_particles", label = "Particles", icon = "particles", tip = "Insert ParticleEmitter with defaults.", group = "av", act = "fx_emit", arg = { kind = "particles" } },
    { id = "ins_fire", label = "Fire", icon = "fire", tip = "Insert Fire.", group = "av", act = "fx_emit", arg = { kind = "fire" } },
    { id = "ins_smoke", label = "Smoke", icon = "cloud", tip = "Insert Smoke.", group = "av", act = "fx_emit", arg = { kind = "smoke" } },
    { id = "ins_sparkles", label = "Sparkles", icon = "effects", tip = "Insert Sparkles.", group = "av", act = "fx_emit", arg = { kind = "sparkles" } },
    { id = "ins_light", label = "PointLight", icon = "bulb", tip = "Insert PointLight.", group = "av", act = "create", arg = { class = "PointLight" } },
    { id = "ins_spot", label = "SpotLight", icon = "bulb", tip = "Insert SpotLight.", group = "av", act = "create", arg = { class = "SpotLight" } },
    { id = "ins_surface", label = "SurfaceLight", icon = "bulb", tip = "Insert SurfaceLight.", group = "av", act = "create", arg = { class = "SurfaceLight" } },
    { id = "ins_decal", label = "Decal", icon = "plus", tip = "Insert Decal (set Texture in Properties).", group = "av", act = "create", arg = { class = "Decal" } },
    { id = "ins_texture", label = "Texture", icon = "plus", tip = "Insert Texture (set Texture in Properties).", group = "av", act = "create", arg = { class = "Texture" } },
    { id = "ins_screengui", label = "ScreenGui", icon = "dock", tip = "Insert ScreenGui in StarterGui.", group = "gui", act = "create", arg = { class = "ScreenGui", parent = "StarterGui" } },
    { id = "ins_frame", label = "Frame", icon = "dock", tip = "Insert Frame into selection.", group = "gui", act = "create", arg = { class = "Frame", intoSelection = true } },
    { id = "ins_textbutton", label = "TextButton", icon = "textA", tip = "Insert TextButton into selection.", group = "gui", act = "create", arg = { class = "TextButton", intoSelection = true } },
    { id = "ins_textlabel", label = "TextLabel", icon = "textA", tip = "Insert TextLabel into selection.", group = "gui", act = "create", arg = { class = "TextLabel", intoSelection = true } },
    { id = "ins_imagebutton", label = "ImageButton", icon = "plus", tip = "Insert ImageButton into selection.", group = "gui", act = "create", arg = { class = "ImageButton", intoSelection = true } },
    { id = "ins_scroll", label = "ScrollFrame", icon = "dock", tip = "Insert ScrollingFrame into selection.", group = "gui", act = "create", arg = { class = "ScrollingFrame", intoSelection = true } },
    { id = "ins_spawn", label = "Spawn", icon = "pin", tip = "Insert SpawnLocation.", group = "gameplay", act = "create", arg = { class = "SpawnLocation" } },
    { id = "ins_seat", label = "Seat", icon = "plus", tip = "Insert Seat.", group = "gameplay", act = "create", arg = { class = "Seat" } },
    { id = "ins_checkpoint", label = "Checkpoint", icon = "check", tip = "Checkpoint part (Neutral=false team logic ready).", group = "gameplay", act = "game_checkpoint" },
    { id = "ins_dialog", label = "Dialog", icon = "chat", tip = "Insert Dialog + DialogChoice.", group = "gameplay", act = "game_dialog" },
    { id = "ins_prompt", label = "ProxPrompt", icon = "pin", tip = "Insert ProximityPrompt into selection.", group = "gameplay", act = "create", arg = { class = "ProximityPrompt", intoSelection = true } },
    { id = "ins_clickdet", label = "ClickDetect", icon = "select", tip = "Insert ClickDetector into selection.", group = "gameplay", act = "create", arg = { class = "ClickDetector", intoSelection = true } },
    { id = "ins_leaderboard", label = "Leaderstats", icon = "data", tip = "Insert leaderstats folder + 2 sample values.", group = "gameplay", act = "game_leaderstats" },
    { id = "ins_zone", label = "Zone", icon = "boxG", tip = "Insert Zone part (CanCollide=false, named).", group = "gameplay", act = "game_zone" },
  } }
T[#T + 1] = { id = "RUN", label = "Run", icon = "run",
  groups = { { id = "transport", label = "Transport" }, { id = "testing", label = "Testing" },
    { id = "debug", label = "Debug" }, { id = "logs", label = "Logs" }, { id = "network", label = "Network" } },
  commands = {
    { id = "run_play", label = "Play", icon = "play", tip = "Preview-play: runs ARKHER simulation (NPC/AI/cutscene/loops).", key = "F5", group = "transport", act = "run_play" },
    { id = "run_pause", label = "Pause", icon = "pause", tip = "Pause preview simulation.", key = "F6", group = "transport", act = "run_pause" },
    { id = "run_stop", label = "Stop", icon = "close", tip = "Stop preview, restore pre-play state.", key = "Shift+F5", group = "transport", act = "run_stop" },
    { id = "run_restart", label = "Restart", icon = "rotate", tip = "Stop + Play again.", group = "transport", act = "run_restart" },
    { id = "run_step", label = "Step", icon = "play", tip = "Advance simulation one tick while paused.", key = "F7", group = "transport", act = "run_step" },
    { id = "run_speed", label = "Sim Speed", icon = "data", tip = "Simulation speed multiplier.", group = "transport", act = "shell_panel", arg = { name = "run_speed" } },
    { id = "run_reset", label = "Reset Sim", icon = "rotate", tip = "Reset all simulated actors to spawn.", group = "transport", act = "run_resetsim" },
    { id = "run_local", label = "Local Test", icon = "check", tip = "Run engine self-tests on current place.", group = "testing", act = "test_local" },
    { id = "run_bots", label = "Bot Clients", icon = "multiplayer", tip = "Spawn N simulated clients (bots) for multiplayer tests.", group = "testing", act = "test_bots", panel = "test_bots" },
    { id = "run_testall", label = "Test All", icon = "testing", tip = "Run all registered checks (place+audit).", group = "testing", act = "test_all" },
    { id = "run_testsel", label = "Test Selected", icon = "testing", tip = "Run checks scoped to selection.", group = "testing", act = "test_selected" },
    { id = "run_asserts", label = "Assertions", icon = "check", tip = "Assertion panel: define live checks.", group = "testing", act = "shell_panel", arg = { name = "test_asserts" } },
    { id = "run_coverage", label = "Coverage", icon = "data", tip = "Which systems were exercised this session.", group = "testing", act = "shell_panel", arg = { name = "test_coverage" } },
    { id = "run_breakpoints", label = "Breakpoints", icon = "close", tip = "Breakpoint list for script preview.", group = "debug", act = "shell_panel", arg = { name = "breakpoints" } },
    { id = "run_watch", label = "Watch", icon = "search", tip = "Watch expressions evaluated each tick.", group = "debug", act = "shell_panel", arg = { name = "watch" } },
    { id = "run_callstack", label = "Call Stack", icon = "data", tip = "Call stack of last error.", group = "debug", act = "shell_panel", arg = { name = "callstack" } },
    { id = "run_stepover", label = "Step Over", icon = "play", tip = "Debugger: step over.", group = "debug", act = "debug_step", arg = { mode = "over" } },
    { id = "run_stepinto", label = "Step Into", icon = "play", tip = "Debugger: step into.", group = "debug", act = "debug_step", arg = { mode = "into" } },
    { id = "run_continue", label = "Continue", icon = "play", tip = "Debugger: continue.", group = "debug", act = "debug_step", arg = { mode = "continue" } },
    { id = "run_eval", label = "Evaluate", icon = "textA", tip = "Evaluate expression in paused state.", group = "debug", act = "shell_panel", arg = { name = "debug_eval" } },
    { id = "run_output", label = "Output", icon = "textA", tip = "Show Output panel.", group = "logs", act = "shell_toggle", arg = { panel = "output" } },
    { id = "run_clearout", label = "Clear Output", icon = "minus", tip = "Clear Output panel.", group = "logs", act = "logs_clear" },
    { id = "run_errors", label = "Errors Only", icon = "close", tip = "Filter Output to errors.", group = "logs", act = "logs_filter", arg = { level = "error" } },
    { id = "run_warnings", label = "Warnings", icon = "close", tip = "Filter Output to warnings+.", group = "logs", act = "logs_filter", arg = { level = "warn" } },
    { id = "run_verbose", label = "Verbose", icon = "textA", tip = "Toggle verbose engine logging.", group = "logs", act = "settings_toggle", arg = { key = "verbose" } },
    { id = "run_savelog", label = "Save Log", icon = "save", tip = "Save Output log to project.", group = "logs", act = "logs_save" },
    { id = "run_latency", label = "Latency Sim", icon = "data", tip = "Artificial bridge latency (ms) for net tests.", group = "network", act = "shell_panel", arg = { name = "net_latency" } },
    { id = "run_netstats", label = "Net Stats", icon = "data", tip = "Bandwidth/steps/queue stats.", group = "network", act = "shell_panel", arg = { name = "net_stats" } },
    { id = "run_profilesnap", label = "Prof Snapshot", icon = "performance", tip = "Capture performance snapshot.", group = "network", act = "perf_snapshot" },
    { id = "run_record", label = "Record", icon = "close", tip = "Record session events to replay log.", group = "network", act = "run_record" },
    { id = "run_replay", label = "Replay", icon = "play", tip = "Replay recorded session events.", group = "network", act = "run_replay" },
    { id = "run_audit", label = "Audit Place", icon = "search", tip = "Full place audit (errors/warnings/perf).", group = "testing", act = "test_audit" },
    { id = "run_perfquick", label = "Quick Perf", icon = "performance", tip = "One-line perf readout in status bar.", group = "testing", act = "perf_quick" },
    { id = "run_mem", label = "Memory", icon = "data", tip = "Memory breakdown panel.", group = "debug", act = "shell_panel", arg = { name = "perf_memory" } },
    { id = "run_scripts", label = "Script Activity", icon = "script", tip = "Running scripts + activity rates.", group = "debug", act = "shell_panel", arg = { name = "script_activity" } },
    { id = "run_errorspanel", label = "Error List", icon = "close", tip = "Collected errors with jump-to-source.", group = "logs", act = "shell_panel", arg = { name = "error_list" } },
    { id = "run_exportlog", label = "Export Log", icon = "share", tip = "Export log as JSON.", group = "logs", act = "logs_export" },
    { id = "run_netgraph", label = "Net Graph", icon = "data", tip = "Live bandwidth graph.", group = "network", act = "shell_panel", arg = { name = "net_graph" } },
    { id = "run_freeze", label = "Freeze Net", icon = "pause", tip = "Freeze simulated traffic (inspect queues).", group = "network", act = "run_freeze" },
    { id = "run_help", label = "Run Help", icon = "info", tip = "What preview-play can/can't do (honest limits).", group = "network", act = "shell_panel", arg = { name = "run_help" } },
  } }
return T
