-- arkher/registry/tabs04.lua — Lighting, Water, Physics, Audio, Effects (5x40).
local T = {}
T[#T + 1] = { id = "LIGHTING", label = "Lighting", icon = "bulb",
  groups = { { id = "global", label = "Global" }, { id = "sun", label = "Sun" },
    { id = "fx", label = "Post FX" }, { id = "lights", label = "Lights" }, { id = "bake", label = "Presets" } },
  commands = {
    { id = "light_ambient", label = "Ambient", icon = "square", tip = "Ambient/OutdoorAmbient/Brightness editor.", group = "global", act = "shell_panel", arg = { name = "world_ambient" } },
    { id = "light_exposure", label = "Exposure", icon = "bulb", tip = "ExposureCompensation slider.", group = "global", act = "shell_panel", arg = { name = "light_exposure" } },
    { id = "light_tech", label = "Technology", icon = "data", tip = "Lighting technology (Compatibility/Future/ShadowMap).", group = "global", act = "shell_panel", arg = { name = "light_tech" } },
    { id = "light_shadows", label = "Shadows", icon = "check", tip = "GlobalShadows toggle.", group = "global", act = "light_shadows" },
    { id = "light_colorshift", label = "ColorShift", icon = "square", tip = "ColorShift_Top/Bottom editor (real).", group = "global", act = "shell_panel", arg = { name = "light_colorshift" } },
    { id = "light_clock", label = "Clock", icon = "data", tip = "ClockTime editor.", group = "sun", act = "shell_panel", arg = { name = "world_clock" } },
    { id = "light_suncolor", label = "Sun Color", icon = "square", tip = "Sun/Moon color via ColorShift.", group = "sun", act = "shell_panel", arg = { name = "light_sun" } },
    { id = "light_sunsize", label = "Sun Size", icon = "expand", tip = "SunAngularSize slider.", group = "sun", act = "shell_panel", arg = { name = "light_sun" } },
    { id = "light_moonsize", label = "Moon Size", icon = "expand", tip = "MoonAngularSize slider.", group = "sun", act = "shell_panel", arg = { name = "light_sun" } },
    { id = "light_bloom", label = "Bloom", icon = "effects", tip = "BloomEffect editor (create if missing).", group = "fx", act = "shell_panel", arg = { name = "light_bloom" } },
    { id = "light_blur", label = "Blur", icon = "effects", tip = "BlurEffect editor.", group = "fx", act = "shell_panel", arg = { name = "light_blur" } },
    { id = "light_colorcorr", label = "ColorCorrect", icon = "square", tip = "ColorCorrectionEffect editor.", group = "fx", act = "shell_panel", arg = { name = "light_colorcorr" } },
    { id = "light_dof", label = "DepthField", icon = "search", tip = "DepthOfFieldEffect editor.", group = "fx", act = "shell_panel", arg = { name = "light_dof" } },
    { id = "light_sunrays", label = "SunRays", icon = "bulb", tip = "SunRaysEffect editor.", group = "fx", act = "shell_panel", arg = { name = "light_sunrays" } },
    { id = "light_atmo", label = "Atmosphere", icon = "cloud", tip = "Full Atmosphere editor.", group = "fx", act = "shell_panel", arg = { name = "light_atmosphere" } },
    { id = "light_sky", label = "Sky", icon = "plus", tip = "Sky presets + custom faces.", group = "fx", act = "shell_panel", arg = { name = "world_sky" } },
    { id = "light_stars", label = "Stars", icon = "effects", tip = "Stars toggle + config.", group = "fx", act = "shell_panel", arg = { name = "world_sky" } },
    { id = "light_point", label = "Point", icon = "bulb", tip = "Insert PointLight.", group = "lights", act = "create", arg = { class = "PointLight" } },
    { id = "light_spot", label = "Spot", icon = "bulb", tip = "Insert SpotLight.", group = "lights", act = "create", arg = { class = "SpotLight" } },
    { id = "light_surface", label = "Surface", icon = "bulb", tip = "Insert SurfaceLight.", group = "lights", act = "create", arg = { class = "SurfaceLight" } },
    { id = "light_allprops", label = "All Lights", icon = "data", tip = "List/select all lights.", group = "lights", act = "shell_panel", arg = { name = "light_all" } },
    { id = "light_toggleall", label = "Toggle All", icon = "check", tip = "Enable/disable all lights.", group = "lights", act = "light_toggleall" },
    { id = "light_flicker", label = "Flicker", icon = "rotate", tip = "Flicker animator for selected lights.", group = "lights", act = "shell_panel", arg = { name = "light_flicker" } },
    { id = "light_daynight", label = "Day/Night", icon = "rotate", tip = "Day/night cycle runner.", group = "bake", act = "shell_panel", arg = { name = "world_daycycle" } },
    { id = "light_preset_day", label = "Preset Day", icon = "bulb", tip = "Apply daylight preset.", group = "bake", act = "light_preset", arg = { name = "day" } },
    { id = "light_preset_night", label = "Preset Night", icon = "bulb", tip = "Apply night preset.", group = "bake", act = "light_preset", arg = { name = "night" } },
    { id = "light_preset_sunset", label = "Preset Dusk", icon = "bulb", tip = "Apply sunset preset.", group = "bake", act = "light_preset", arg = { name = "sunset" } },
    { id = "light_preset_horror", label = "Preset Dark", icon = "bulb", tip = "Apply dark/horror preset.", group = "bake", act = "light_preset", arg = { name = "horror" } },
    { id = "light_savepreset", label = "Save Preset", icon = "save", tip = "Save current lighting as preset.", group = "bake", act = "light_savepreset", panel = "light_savepreset" },
    { id = "light_audit", label = "Audit", icon = "search", tip = "Light count/perf audit.", group = "bake", act = "light_audit" },
    { id = "light_fog", label = "Fog Panel", icon = "cloud", tip = "Fog controls.", group = "global", act = "shell_panel", arg = { name = "world_fog" } },
    { id = "light_envdiff", label = "Env Diffuse", icon = "square", tip = "EnvironmentDiffuseScale slider.", group = "global", act = "shell_panel", arg = { name = "light_exposure" } },
    { id = "light_envspec", label = "Env Spec", icon = "square", tip = "EnvironmentSpecularScale slider.", group = "global", act = "shell_panel", arg = { name = "light_exposure" } },
    { id = "light_prior", label = "Prioritize", icon = "check", tip = "Prioritize rendering of selected lights.", group = "lights", act = "light_prioritize" },
    { id = "light_range", label = "Range All", icon = "expand", tip = "Set range on all/selected lights.", group = "lights", act = "shell_panel", arg = { name = "light_range" } },
    { id = "light_colorall", label = "Color All", icon = "drop", tip = "Set color on all/selected lights.", group = "lights", act = "shell_panel", arg = { name = "light_colorall" } },
    { id = "light_strobe", label = "Strobe", icon = "rotate", tip = "Strobe animator for selected lights.", group = "lights", act = "shell_panel", arg = { name = "light_strobe" } },
    { id = "light_pwrcost", label = "Cost", icon = "data", tip = "Lighting perf cost estimate.", group = "bake", act = "light_cost" },
    { id = "light_reset", label = "Reset", icon = "rotate", tip = "Reset lighting to defaults.", group = "bake", act = "light_reset" },
    { id = "light_help", label = "Limits", icon = "info", tip = "Honest lighting limits (Future/shadows/mobile).", group = "bake", act = "shell_panel", arg = { name = "light_limits" } },
  } }
T[#T + 1] = { id = "WATER", label = "Water", icon = "drop",
  groups = { { id = "surface", label = "Surface" }, { id = "volume", label = "Volume" },
    { id = "effects", label = "Effects" }, { id = "gameplay", label = "Gameplay" }, { id = "tools", label = "Tools" } },
  commands = {
    { id = "water_level", label = "Sea Level", icon = "drop", tip = "Global water level.", group = "surface", act = "shell_panel", arg = { name = "water_level" } },
    { id = "water_color", label = "Color", icon = "square", tip = "WaterColor3.", group = "surface", act = "shell_panel", arg = { name = "water_surface" } },
    { id = "water_transp", label = "Transp", icon = "square", tip = "WaterTransparency.", group = "surface", act = "shell_panel", arg = { name = "water_surface" } },
    { id = "water_wave", label = "Waves", icon = "rotate", tip = "WaveSize/WaveSpeed/Direction.", group = "surface", act = "shell_panel", arg = { name = "water_surface" } },
    { id = "water_reflect", label = "Reflect", icon = "bulb", tip = "WaterReflectance.", group = "surface", act = "shell_panel", arg = { name = "water_surface" } },
    { id = "water_fill", label = "Fill", icon = "plus", tip = "Fill region with water.", group = "volume", act = "terrain_water", arg = { op = "fill" } },
    { id = "water_drain", label = "Drain", icon = "minus", tip = "Remove water in region.", group = "volume", act = "terrain_water", arg = { op = "drain" } },
    { id = "water_ocean", label = "Make Ocean", icon = "drop", tip = "Ocean: clear lowlands + set sea level.", group = "volume", act = "water_ocean", panel = "water_ocean" },
    { id = "water_lake", label = "Make Lake", icon = "drop", tip = "Carve lake basin + fill.", group = "volume", act = "water_lake", panel = "water_lake" },
    { id = "water_river", label = "Make River", icon = "drop", tip = "Carve riverbed + fill water.", group = "volume", act = "terrain_rivers", panel = "terrain_rivers" },
    { id = "water_foam", label = "Foam", icon = "effects", tip = "Shoreline foam particles.", group = "effects", act = "shell_panel", arg = { name = "water_foam" } },
    { id = "water_splash", label = "Splashes", icon = "effects", tip = "Splash particles on water entry (sim).", group = "effects", act = "shell_panel", arg = { name = "water_splash" } },
    { id = "water_under", label = "Underwater", icon = "view", tip = "Underwater FX (blur/tint when camera submerged).", group = "effects", act = "shell_panel", arg = { name = "water_under" } },
    { id = "water_caustics", label = "Caustics", icon = "bulb", tip = "Fake caustics projector.", group = "effects", act = "shell_panel", arg = { name = "water_caustics" } },
    { id = "water_rain", label = "Rain", icon = "cloud", tip = "Rain particle system.", group = "effects", act = "shell_panel", arg = { name = "env_rain" } },
    { id = "water_swim", label = "Swim", icon = "character", tip = "Swim settings (speed,_sink,damage).", group = "gameplay", act = "shell_panel", arg = { name = "water_swim" } },
    { id = "water_boat", label = "Boat Kit", icon = "toolbox", tip = "Boat seat + thrust setup.", group = "gameplay", act = "shell_panel", arg = { name = "water_boat" } },
    { id = "water_damage", label = "Water Dmg", icon = "close", tip = "Damage/safe water volumes.", group = "gameplay", act = "shell_panel", arg = { name = "water_damage" } },
    { id = "water_current", label = "Currents", icon = "share", tip = "Current volumes (push players).", group = "gameplay", act = "shell_panel", arg = { name = "water_current" } },
    { id = "water_dive", label = "Diving", icon = "data", tip = "Oxygen/dive config.", group = "gameplay", act = "shell_panel", arg = { name = "water_dive" } },
    { id = "water_fishing", label = "Fishing", icon = "toolbox", tip = "Fishing spots + loot tables.", group = "gameplay", act = "shell_panel", arg = { name = "water_fishing" } },
    { id = "water_measure", label = "Depth", icon = "scaleI", tip = "Measure water depth at cursor.", group = "tools", act = "water_depth" },
    { id = "water_flowmap", label = "Flow Map", icon = "data", tip = "Visualize currents.", group = "tools", act = "settings_toggle", arg = { key = "water_flowvis" } },
    { id = "water_audit", label = "Audit", icon = "search", tip = "Water audit: leaks, perf, gaps.", group = "tools", act = "water_audit" },
    { id = "water_export", label = "Export", icon = "share", tip = "Export water setup JSON.", group = "tools", act = "water_export" },
    { id = "water_preset_trop", label = "Tropical", icon = "drop", tip = "Tropical water preset.", group = "surface", act = "water_preset", arg = { name = "tropical" } },
    { id = "water_preset_murk", label = "Murky", icon = "drop", tip = "Murky water preset.", group = "surface", act = "water_preset", arg = { name = "murky" } },
    { id = "water_preset_arctic", label = "Arctic", icon = "drop", tip = "Arctic water preset.", group = "surface", act = "water_preset", arg = { name = "arctic" } },
    { id = "water_freeze", label = "Freeze", icon = "lock", tip = "Freeze water surfaces (ice look).", group = "surface", act = "water_freeze" },
    { id = "water_ice", label = "Ice Sheet", icon = "plus", tip = "Create ice sheet part on water.", group = "volume", act = "water_ice" },
    { id = "water_waterfall", label = "Waterfall", icon = "plus", tip = "Waterfall builder (parts+particles+sound).", group = "volume", act = "water_waterfall", panel = "water_waterfall" },
    { id = "water_pool", label = "Pool Kit", icon = "boxG", tip = "Swimming pool kit.", group = "volume", act = "shell_panel", arg = { name = "water_pool" } },
    { id = "water_well", label = "Well Kit", icon = "boxG", tip = "Well + bucket kit.", group = "volume", act = "shell_panel", arg = { name = "water_well" } },
    { id = "water_pump", label = "Pump", icon = "rotate", tip = "Pump: animate water level.", group = "effects", act = "shell_panel", arg = { name = "water_pump" } },
    { id = "water_tide", label = "Tides", icon = "rotate", tip = "Tide cycle animation.", group = "effects", act = "shell_panel", arg = { name = "water_tide" } },
    { id = "water_storm", label = "Storm Sea", icon = "cloud", tip = "Storm sea state preset.", group = "effects", act = "water_preset", arg = { name = "storm" } },
    { id = "water_buoy", label = "Buoyancy", icon = "data", tip = "Buoyancy tuning for parts.", group = "gameplay", act = "shell_panel", arg = { name = "water_buoy" } },
    { id = "water_rescue", label = "Rescue", icon = "plus", tip = "Auto-rescue drowning players.", group = "gameplay", act = "settings_toggle", arg = { key = "water_rescue" } },
    { id = "water_limits", label = "Limits", icon = "info", tip = "Honest water limits + workarounds.", group = "tools", act = "shell_panel", arg = { name = "water_limits" } },
    { id = "water_reset", label = "Reset", icon = "rotate", tip = "Reset water to defaults.", group = "tools", act = "water_reset" },
  } }
T[#T + 1] = { id = "PHYSICS", label = "Physics", icon = "physics",
  groups = { { id = "body", label = "Body" }, { id = "constraints", label = "Constraints" },
    { id = "forces", label = "Forces" }, { id = "vehicle", label = "Vehicle" }, { id = "debug", label = "Debug" } },
  commands = {
    { id = "phys_mass", label = "Mass", icon = "data", tip = "Mass/density editor (CustomPhysicalProperties).", group = "body", act = "shell_panel", arg = { name = "phys_mass" } },
    { id = "phys_friction", label = "Friction", icon = "data", tip = "Friction/FrictionWeight editor.", group = "body", act = "shell_panel", arg = { name = "phys_mass" } },
    { id = "phys_elastic", label = "Elasticity", icon = "data", tip = "Elasticity editor.", group = "body", act = "shell_panel", arg = { name = "phys_mass" } },
    { id = "phys_anchor", label = "Anchor", icon = "anchor", tip = "Toggle anchor on selection.", group = "body", act = "edit_anchor" },
    { id = "phys_collide", label = "CanCollide", icon = "check", tip = "Toggle collisions on selection.", group = "body", act = "edit_collide", arg = { toggle = true } },
    { id = "phys_massless", label = "Massless", icon = "check", tip = "Toggle Massless on selection.", group = "body", act = "prop_toggle", arg = { key = "Massless" } },
    { id = "phys_rootpri", label = "RootPriority", icon = "data", tip = "RootPriority editor.", group = "body", act = "shell_panel", arg = { name = "phys_root" } },
    { id = "phys_weld", label = "Weld", icon = "pin", tip = "WeldConstraint between two parts.", group = "constraints", act = "phys_constraint", arg = { kind = "Weld" }, panel = "phys_constraint" },
    { id = "phys_hinge", label = "Hinge", icon = "rotate", tip = "HingeConstraint + motor setup.", group = "constraints", act = "phys_constraint", arg = { kind = "Hinge" }, panel = "phys_constraint" },
    { id = "phys_rope", label = "Rope", icon = "share", tip = "RopeConstraint setup.", group = "constraints", act = "phys_constraint", arg = { kind = "Rope" }, panel = "phys_constraint" },
    { id = "phys_rod", label = "Rod", icon = "share", tip = "RodConstraint setup.", group = "constraints", act = "phys_constraint", arg = { kind = "Rod" }, panel = "phys_constraint" },
    { id = "phys_spring", label = "Spring", icon = "rotate", tip = "SpringConstraint + damping.", group = "constraints", act = "phys_constraint", arg = { kind = "Spring" }, panel = "phys_constraint" },
    { id = "phys_prism", label = "Prismatic", icon = "move", tip = "PrismaticConstraint + motor.", group = "constraints", act = "phys_constraint", arg = { kind = "Prismatic" }, panel = "phys_constraint" },
    { id = "phys_ballsock", label = "BallSocket", icon = "rotate", tip = "BallSocketConstraint setup.", group = "constraints", act = "phys_constraint", arg = { kind = "BallSocket" }, panel = "phys_constraint" },
    { id = "phys_align", label = "Align", icon = "share", tip = "AlignPosition/AlignOrientation pair.", group = "constraints", act = "phys_align" },
    { id = "phys_vectorf", label = "VectorForce", icon = "move", tip = "Insert VectorForce.", group = "forces", act = "create", arg = { class = "VectorForce", intoSelection = true } },
    { id = "phys_linearv", label = "LinearVel", icon = "move", tip = "Insert LinearVelocity.", group = "forces", act = "create", arg = { class = "LinearVelocity", intoSelection = true } },
    { id = "phys_angularv", label = "AngularVel", icon = "rotate", tip = "Insert AngularVelocity.", group = "forces", act = "create", arg = { class = "AngularVelocity", intoSelection = true } },
    { id = "phys_torque", label = "Torque", icon = "rotate", tip = "Insert Torque.", group = "forces", act = "create", arg = { class = "Torque", intoSelection = true } },
    { id = "phys_bodygyro", label = "BodyGyro", icon = "rotate", tip = "Insert BodyGyro (legacy, works).", group = "forces", act = "create", arg = { class = "BodyGyro", intoSelection = true } },
    { id = "phys_bodyvel", label = "BodyVelocity", icon = "move", tip = "Insert BodyVelocity (legacy, works).", group = "forces", act = "create", arg = { class = "BodyVelocity", intoSelection = true } },
    { id = "phys_explosion", label = "Explode", icon = "fire", tip = "Explosion at cursor (preview).", group = "forces", act = "phys_explode" },
    { id = "phys_car", label = "Car Kit", icon = "toolbox", tip = "Car chassis kit (hinges+motors).", group = "vehicle", act = "shell_panel", arg = { name = "phys_car" } },
    { id = "phys_tank", label = "Tank Kit", icon = "toolbox", tip = "Tank tread kit.", group = "vehicle", act = "shell_panel", arg = { name = "phys_tank" } },
    { id = "phys_plane", label = "Plane Kit", icon = "toolbox", tip = "Plane kit (gyro+thrust).", group = "vehicle", act = "shell_panel", arg = { name = "phys_plane" } },
    { id = "phys_boat", label = "Boat Phys", icon = "toolbox", tip = "Boat physics kit.", group = "vehicle", act = "shell_panel", arg = { name = "water_boat" } },
    { id = "phys_elevator", label = "Elevator", icon = "move", tip = "Elevator (prismatic + call buttons).", group = "vehicle", act = "shell_panel", arg = { name = "phys_elevator" } },
    { id = "phys_door", label = "Door Kit", icon = "toolbox", tip = "Hinged door + proximity.", group = "vehicle", act = "shell_panel", arg = { name = "phys_door" } },
    { id = "phys_drawbridge", label = "Drawbridge", icon = "toolbox", tip = "Drawbridge kit.", group = "vehicle", act = "shell_panel", arg = { name = "phys_drawbridge" } },
    { id = "phys_cannon", label = "Cannon", icon = "fire", tip = "Cannon: spawns projectile parts.", group = "vehicle", act = "shell_panel", arg = { name = "phys_cannon" } },
    { id = "phys_contacts", label = "Contacts", icon = "data", tip = "Live contact/stress monitor.", group = "debug", act = "shell_panel", arg = { name = "phys_contacts" } },
    { id = "phys_showjoints", label = "Show Joints", icon = "view", tip = "Visualize constraints.", group = "debug", act = "settings_toggle", arg = { key = "phys_jointvis" } },
    { id = "phys_sleep", label = "Sleeping", icon = "pause", tip = "Show sleeping parts.", group = "debug", act = "settings_toggle", arg = { key = "phys_sleepvis" } },
    { id = "phys_audit", label = "Audit", icon = "search", tip = "Physics audit: unanchored, mass, joints.", group = "debug", act = "phys_audit" },
    { id = "phys_freeze", label = "Freeze All", icon = "lock", tip = "Anchor everything (undoable).", group = "debug", act = "phys_freezeall" },
    { id = "phys_unfreeze", label = "Unfreeze", icon = "lock", tip = "Restore pre-freeze anchors.", group = "debug", act = "phys_unfreeze" },
    { id = "phys_gravity", label = "Gravity", icon = "data", tip = "Gravity slider.", group = "debug", act = "shell_panel", arg = { name = "world_gravity" } },
    { id = "phys_limits", label = "Limits", icon = "info", tip = "Honest physics limits.", group = "debug", act = "shell_panel", arg = { name = "phys_limits" } },
    { id = "phys_attachment", label = "Attachment", icon = "pin", tip = "Insert Attachment into selection.", group = "constraints", act = "phys_attachment" },
    { id = "phys_break", label = "BreakJoints", icon = "close", tip = "BreakJoints on selection.", group = "constraints", act = "phys_breakjoints" },
  } }
T[#T + 1] = { id = "AUDIO", label = "Audio", icon = "note",
  groups = { { id = "library", label = "Library" }, { id = "mixer", label = "Mixer" },
    { id = "fx", label = "FX" }, { id = "zones", label = "Zones" }, { id = "tools", label = "Tools" } },
  commands = {
    { id = "audio_browse", label = "Browse", icon = "search", tip = "Sound library browser (local registry + ids).", group = "library", act = "shell_panel", arg = { name = "audio_browse" } },
    { id = "audio_play", label = "Play", icon = "play", tip = "Play selected Sound.", group = "library", act = "audio_play" },
    { id = "audio_stop", label = "Stop", icon = "close", tip = "Stop selected/all sounds.", group = "library", act = "audio_stop" },
    { id = "audio_pause", label = "Pause", icon = "pause", tip = "Pause selected sound.", group = "library", act = "audio_pause" },
    { id = "audio_add", label = "Add Sound", icon = "plus", tip = "Insert Sound with id panel.", group = "library", act = "audio_add", panel = "audio_add" },
    { id = "audio_replace", label = "Replace Id", icon = "rotate", tip = "Replace SoundId on selection.", group = "library", act = "shell_panel", arg = { name = "audio_replace" } },
    { id = "audio_preload", label = "Preload", icon = "open", tip = "Preload sounds (PreloadAsync, honest).", group = "library", act = "audio_preload" },
    { id = "audio_mixer", label = "Mixer", icon = "data", tip = "Full mixer: buses, volume, mute/solo.", group = "mixer", act = "shell_panel", arg = { name = "audio_mixer" } },
    { id = "audio_master", label = "Master Vol", icon = "data", tip = "Master volume slider.", group = "mixer", act = "shell_panel", arg = { name = "audio_mixer" } },
    { id = "audio_music", label = "Music Bus", icon = "note", tip = "Music bus level.", group = "mixer", act = "shell_panel", arg = { name = "audio_mixer" } },
    { id = "audio_sfxbus", label = "SFX Bus", icon = "effects", tip = "SFX bus level.", group = "mixer", act = "shell_panel", arg = { name = "audio_mixer" } },
    { id = "audio_voicebus", label = "Voice Bus", icon = "chat", tip = "Voice bus level.", group = "mixer", act = "shell_panel", arg = { name = "audio_mixer" } },
    { id = "audio_equalizer", label = "Equalizer", icon = "data", tip = "EqualizerSoundEffect editor.", group = "fx", act = "shell_panel", arg = { name = "audio_eq" } },
    { id = "audio_reverb", label = "Reverb", icon = "effects", tip = "ReverbSoundEffect editor.", group = "fx", act = "shell_panel", arg = { name = "audio_reverb" } },
    { id = "audio_echo", label = "Echo", icon = "effects", tip = "EchoSoundEffect editor.", group = "fx", act = "shell_panel", arg = { name = "audio_echo" } },
    { id = "audio_distort", label = "Distortion", icon = "effects", tip = "DistortionSoundEffect editor.", group = "fx", act = "shell_panel", arg = { name = "audio_distort" } },
    { id = "audio_chorus", label = "Chorus", icon = "effects", tip = "ChorusSoundEffect editor.", group = "fx", act = "shell_panel", arg = { name = "audio_chorus" } },
    { id = "audio_pitch", label = "Pitch", icon = "data", tip = "PitchSoundEffect editor.", group = "fx", act = "shell_panel", arg = { name = "audio_pitch" } },
    { id = "audio_3d", label = "3D Setup", icon = "expand", tip = "RollOff/Min/Max distance editor.", group = "fx", act = "shell_panel", arg = { name = "audio_3d" } },
    { id = "audio_zoneadd", label = "Add Zone", icon = "boxG", tip = "Create music/ambient zone.", group = "zones", act = "audio_zoneadd" },
    { id = "audio_zonelist", label = "Zone List", icon = "data", tip = "List/select audio zones.", group = "zones", act = "shell_panel", arg = { name = "audio_zones" } },
    { id = "audio_crossfade", label = "Crossfade", icon = "share", tip = "Zone crossfade times.", group = "zones", act = "shell_panel", arg = { name = "audio_crossfade" } },
    { id = "audio_playlist", label = "Playlist", icon = "note", tip = "Playlist editor (shuffle/loop).", group = "zones", act = "shell_panel", arg = { name = "audio_playlist" } },
    { id = "audio_daynight", label = "Day/Night", icon = "rotate", tip = "Different tracks by clock time.", group = "zones", act = "shell_panel", arg = { name = "audio_daynight" } },
    { id = "audio_footsteps", label = "Footsteps", icon = "effects", tip = "Footstep sounds by material.", group = "zones", act = "shell_panel", arg = { name = "audio_footsteps" } },
    { id = "audio_voicechat", label = "Voice Chat", icon = "chat", tip = "VoiceChatService info + enable.", group = "zones", act = "shell_panel", arg = { name = "audio_voicechat" } },
    { id = "audio_record", label = "Record", icon = "close", tip = "Honest: no mic capture API; import guide instead.", group = "tools", act = "shell_panel", arg = { name = "audio_record" } },
    { id = "audio_trim", label = "Trim", icon = "cut", tip = "Honest: no DSP trim; TimePosition markers instead.", group = "tools", act = "shell_panel", arg = { name = "audio_trim" } },
    { id = "audio_fade", label = "Fade IO", icon = "data", tip = "Fade in/out animator.", group = "tools", act = "shell_panel", arg = { name = "audio_fade" } },
    { id = "audio_loop", label = "Loop", icon = "rotate", tip = "Toggle Looped on selection.", group = "tools", act = "prop_toggle", arg = { key = "Looped" } },
    { id = "audio_audit", label = "Audit", icon = "search", tip = "Audio audit: missing ids, overlap, loudness.", group = "tools", act = "audio_audit" },
    { id = "audio_export", label = "Export", icon = "share", tip = "Export audio setup JSON.", group = "tools", act = "audio_export" },
    { id = "audio_muteall", label = "Mute All", icon = "close", tip = "Mute all sounds.", group = "mixer", act = "audio_muteall" },
    { id = "audio_unmute", label = "Unmute", icon = "check", tip = "Unmute all sounds.", group = "mixer", act = "audio_unmute" },
    { id = "audio_duck", label = "Ducking", icon = "data", tip = "Music ducks under voice/SFX.", group = "mixer", act = "settings_toggle", arg = { key = "audio_duck" } },
    { id = "audio_test", label = "Test Tone", icon = "play", tip = "Play test tone (synthesized id).", group = "library", act = "audio_testtone" },
    { id = "audio_captions", label = "Captions", icon = "textA", tip = "Caption track for sounds (a11y).", group = "tools", act = "shell_panel", arg = { name = "audio_captions" } },
    { id = "audio_haptic", label = "Haptics", icon = "playersI", tip = "Haptic pulses synced to beats (mobile/gamepad).", group = "tools", act = "shell_panel", arg = { name = "audio_haptic" } },
    { id = "audio_limits", label = "Limits", icon = "info", tip = "Honest audio limits.", group = "tools", act = "shell_panel", arg = { name = "audio_limits" } },
    { id = "audio_reset", label = "Reset", icon = "rotate", tip = "Reset audio setup.", group = "tools", act = "audio_reset" },
  } }
T[#T + 1] = { id = "EFFECTS", label = "Effects", icon = "effects",
  groups = { { id = "particles", label = "Particles" }, { id = "legacy", label = "Legacy FX" },
    { id = "beams", label = "Beams" }, { id = "screen", label = "Screen" }, { id = "control", label = "Control" } },
  commands = {
    { id = "fx_emitter", label = "Emitter", icon = "particles", tip = "ParticleEmitter full editor.", group = "particles", act = "shell_panel", arg = { name = "fx_emitter" } },
    { id = "fx_rate", label = "Rate", icon = "data", tip = "Emission rate slider.", group = "particles", act = "shell_panel", arg = { name = "fx_emitter" } },
    { id = "fx_lifetime", label = "Lifetime", icon = "data", tip = "Lifetime range editor.", group = "particles", act = "shell_panel", arg = { name = "fx_emitter" } },
    { id = "fx_speed", label = "Speed", icon = "data", tip = "Speed range editor.", group = "particles", act = "shell_panel", arg = { name = "fx_emitter" } },
    { id = "fx_colorseq", label = "Color", icon = "square", tip = "Color sequence editor.", group = "particles", act = "shell_panel", arg = { name = "fx_colorseq" } },
    { id = "fx_sizeseq", label = "Size", icon = "expand", tip = "Size/Transparency sequence editor.", group = "particles", act = "shell_panel", arg = { name = "fx_sizeseq" } },
    { id = "fx_burst", label = "Burst", icon = "fire", tip = "Emit N now.", group = "particles", act = "fx_burst" },
    { id = "fx_toggle", label = "Toggle Emit", icon = "check", tip = "Toggle Enabled on emitters.", group = "particles", act = "fx_toggle" },
    { id = "fx_fire", label = "Fire", icon = "fire", tip = "Insert/configure Fire.", group = "legacy", act = "fx_emit", arg = { kind = "fire" } },
    { id = "fx_smoke", label = "Smoke", icon = "cloud", tip = "Insert/configure Smoke.", group = "legacy", act = "fx_emit", arg = { kind = "smoke" } },
    { id = "fx_sparkles", label = "Sparkles", icon = "effects", tip = "Insert Sparkles.", group = "legacy", act = "fx_emit", arg = { kind = "sparkles" } },
    { id = "fx_forcefield", label = "ForceField", icon = "plus", tip = "ForceField on character/selection.", group = "legacy", act = "fx_forcefield" },
    { id = "fx_explosionfx", label = "Explosion", icon = "fire", tip = "Explosion FX at cursor.", group = "legacy", act = "phys_explode" },
    { id = "fx_beam", label = "Beam", icon = "share", tip = "Beam between 2 attachments.", group = "beams", act = "fx_beam", panel = "fx_beam" },
    { id = "fx_trail", label = "Trail", icon = "share", tip = "Trail on selection.", group = "beams", act = "fx_trail" },
    { id = "fx_halo", label = "Halo", icon = "effects", tip = "Billboard halo kit.", group = "beams", act = "shell_panel", arg = { name = "fx_halo" } },
    { id = "fx_lightning", label = "Lightning", icon = "effects", tip = "Lightning bolt generator.", group = "beams", act = "fx_lightning", panel = "fx_lightning" },
    { id = "fx_laser", label = "Laser", icon = "close", tip = "Laser beam kit.", group = "beams", act = "shell_panel", arg = { name = "fx_laser" } },
    { id = "fx_shake", label = "Shake", icon = "rotate", tip = "Screen shake trigger.", group = "screen", act = "fx_shake" },
    { id = "fx_flash", label = "Flash", icon = "bulb", tip = "Screen flash overlay.", group = "screen", act = "fx_flash" },
    { id = "fx_fade", label = "Fade", icon = "square", tip = "Screen fade animator.", group = "screen", act = "shell_panel", arg = { name = "fx_fade" } },
    { id = "fx_vignette", label = "Vignette", icon = "square", tip = "Vignette overlay.", group = "screen", act = "settings_toggle", arg = { key = "fx_vignette" } },
    { id = "fx_slowmo", label = "Slow-Mo", icon = "pause", tip = "Slow-motion preview timescale.", group = "screen", act = "fx_slowmo" },
    { id = "fx_hitstop", label = "Hitstop", icon = "pause", tip = "Hitstop pulse (freeze ms).", group = "screen", act = "fx_hitstop" },
    { id = "fx_alltoggle", label = "All FX Off", icon = "close", tip = "Disable all emitters (perf).", group = "control", act = "fx_alloff" },
    { id = "fx_allon", label = "All FX On", icon = "check", tip = "Re-enable emitters.", group = "control", act = "fx_allon" },
    { id = "fx_perf", label = "FX Perf", icon = "performance", tip = "Emitter count/rate audit.", group = "control", act = "fx_audit" },
    { id = "fx_cull", label = "Cull Dist", icon = "view", tip = "Distance culling for emitters.", group = "control", act = "shell_panel", arg = { name = "fx_cull" } },
    { id = "fx_presets", label = "Presets", icon = "save", tip = "FX preset library.", group = "control", act = "shell_panel", arg = { name = "fx_presets" } },
    { id = "fx_savepreset", label = "Save Preset", icon = "save", tip = "Save emitter as preset.", group = "control", act = "fx_savepreset", panel = "fx_savepreset" },
    { id = "fx_clear", label = "Clear All", icon = "minus", tip = "Clear live particles from all emitters now.", group = "control", act = "fx_clear" },
    { id = "fx_texture", label = "Texture", icon = "plus", tip = "Emitter texture id.", group = "particles", act = "shell_panel", arg = { name = "fx_texture" } },
    { id = "fx_shape", label = "Shape", icon = "boxG", tip = "Emission shape + spread.", group = "particles", act = "shell_panel", arg = { name = "fx_shape" } },
    { id = "fx_drag", label = "Drag", icon = "data", tip = "Drag/acceleration editor.", group = "particles", act = "shell_panel", arg = { name = "fx_drag" } },
    { id = "fx_rot", label = "Rotation", icon = "rotate", tip = "RotSpeed range editor.", group = "particles", act = "shell_panel", arg = { name = "fx_rot" } },
    { id = "fx_wind", label = "Wind Affect", icon = "cloud", tip = "Wind influence toggle.", group = "particles", act = "shell_panel", arg = { name = "fx_wind" } },
    { id = "fx_lightemit", label = "LightEmit", icon = "bulb", tip = "LightEmission/LightInfluence sliders.", group = "particles", act = "shell_panel", arg = { name = "fx_lightemit" } },
    { id = "fx_zoffset", label = "ZOffset", icon = "data", tip = "ZOffset slider.", group = "particles", act = "shell_panel", arg = { name = "fx_zoffset" } },
    { id = "fx_sparkles2", label = "Sparkle FX", icon = "effects", tip = "Sparkle burst at cursor.", group = "legacy", act = "fx_sparkleburst" },
    { id = "fx_confetti", label = "Confetti", icon = "effects", tip = "Confetti cannon kit.", group = "legacy", act = "shell_panel", arg = { name = "fx_confetti" } },
  } }
return T
