-- arkher/registry/tabs05.lua — NPC, AI, Scripting, Multiplayer, Performance (5x40).
local T = {}
T[#T + 1] = { id = "NPC", label = "NPC", icon = "npc",
  groups = { { id = "create", label = "Create" }, { id = "brain", label = "Brain" },
    { id = "dialog", label = "Dialog" }, { id = "combat", label = "Combat" }, { id = "manage", label = "Manage" } },
  commands = {
    { id = "npc_new", label = "New NPC", icon = "npc", tip = "Spawn NPC rig + brain + dialog.", group = "create", act = "npc_new", panel = "npc_new" },
    { id = "npc_civilian", label = "Civilian", icon = "character", tip = "Civilian preset (wander, no combat).", group = "create", act = "npc_preset", arg = { name = "civilian" } },
    { id = "npc_guard", label = "Guard", icon = "lock", tip = "Guard preset (patrol + chase).", group = "create", act = "npc_preset", arg = { name = "guard" } },
    { id = "npc_merchant", label = "Merchant", icon = "toolbox", tip = "Merchant preset (shop dialog).", group = "create", act = "npc_preset", arg = { name = "merchant" } },
    { id = "npc_enemy", label = "Enemy", icon = "close", tip = "Enemy preset (chase + attack).", group = "create", act = "npc_preset", arg = { name = "enemy" } },
    { id = "npc_clone", label = "Clone", icon = "copy", tip = "Clone selected NPC.", group = "create", act = "edit_duplicate" },
    { id = "npc_delete", label = "Delete", icon = "close", tip = "Delete selected NPC.", group = "create", act = "edit_delete" },
    { id = "npc_look", label = "Look", icon = "character", tip = "NPC appearance editor.", group = "create", act = "shell_panel", arg = { name = "npc_look" } },
    { id = "npc_waypoints", label = "Waypoints", icon = "pin", tip = "Waypoint path editor.", group = "brain", act = "shell_panel", arg = { name = "npc_waypoints" } },
    { id = "npc_patrol", label = "Patrol", icon = "rotate", tip = "Patrol mode on/off.", group = "brain", act = "npc_mode", arg = { mode = "patrol" } },
    { id = "npc_wander", label = "Wander", icon = "rotate", tip = "Wander mode on/off.", group = "brain", act = "npc_mode", arg = { mode = "wander" } },
    { id = "npc_follow", label = "Follow", icon = "share", tip = "Follow target (player/NPC).", group = "brain", act = "npc_mode", arg = { mode = "follow" } },
    { id = "npc_stay", label = "Stay", icon = "pause", tip = "Stay/idle mode.", group = "brain", act = "npc_mode", arg = { mode = "stay" } },
    { id = "npc_senses", label = "Senses", icon = "search", tip = "Sight/hearing ranges.", group = "brain", act = "shell_panel", arg = { name = "npc_senses" } },
    { id = "npc_speed", label = "Speed", icon = "data", tip = "Move speed editor.", group = "brain", act = "shell_panel", arg = { name = "npc_stats" } },
    { id = "npc_tree", label = "Behavior", icon = "data", tip = "Behavior state machine editor.", group = "brain", act = "shell_panel", arg = { name = "npc_behavior" } },
    { id = "npc_dialogedit", label = "Dialog Tree", icon = "chat", tip = "Dialog tree editor.", group = "dialog", act = "shell_panel", arg = { name = "npc_dialog" } },
    { id = "npc_greet", label = "Greeting", icon = "chat", tip = "Greeting text.", group = "dialog", act = "shell_panel", arg = { name = "npc_dialog" } },
    { id = "npc_shop", label = "Shop", icon = "toolbox", tip = "NPC shop inventory.", group = "dialog", act = "shell_panel", arg = { name = "npc_shop" } },
    { id = "npc_quest", label = "Quest Giver", icon = "check", tip = "Quest giver setup.", group = "dialog", act = "shell_panel", arg = { name = "npc_quest" } },
    { id = "npc_testtalk", label = "Test Talk", icon = "play", tip = "Preview dialog flow.", group = "dialog", act = "npc_testtalk" },
    { id = "npc_hp", label = "HP/DMG", icon = "data", tip = "Health/damage editor.", group = "combat", act = "shell_panel", arg = { name = "npc_combat" } },
    { id = "npc_aggro", label = "Aggro", icon = "search", tip = "Aggro range + conditions.", group = "combat", act = "shell_panel", arg = { name = "npc_combat" } },
    { id = "npc_attack", label = "Attack", icon = "fire", tip = "Attack style (melee/ranged).", group = "combat", act = "shell_panel", arg = { name = "npc_combat" } },
    { id = "npc_loot", label = "Loot", icon = "gem", tip = "Loot table editor.", group = "combat", act = "shell_panel", arg = { name = "npc_loot" } },
    { id = "npc_respawn", label = "Respawn", icon = "rotate", tip = "Respawn time + point.", group = "combat", act = "shell_panel", arg = { name = "npc_respawn" } },
    { id = "npc_faction", label = "Factions", icon = "people", tip = "Faction relations matrix.", group = "combat", act = "shell_panel", arg = { name = "npc_factions" } },
    { id = "npc_list", label = "NPC List", icon = "data", tip = "List/select all NPCs.", group = "manage", act = "shell_panel", arg = { name = "npc_list" } },
    { id = "npc_teleport", label = "Bring All", icon = "share", tip = "Teleport all NPCs to focus.", group = "manage", act = "npc_bringall" },
    { id = "npc_freeze", label = "Freeze AI", icon = "pause", tip = "Pause all NPC brains.", group = "manage", act = "npc_freeze" },
    { id = "npc_unfreeze", label = "Resume AI", icon = "play", tip = "Resume all NPC brains.", group = "manage", act = "npc_unfreeze" },
    { id = "npc_export", label = "Export", icon = "share", tip = "Export NPC JSON.", group = "manage", act = "npc_export" },
    { id = "npc_import", label = "Import", icon = "open", tip = "Import NPC JSON.", group = "manage", act = "npc_import", panel = "npc_import" },
    { id = "npc_audit", label = "Audit", icon = "search", tip = "NPC audit: missing brains/paths.", group = "manage", act = "npc_audit" },
    { id = "npc_names", label = "Names", icon = "textA", tip = "Nameplates + titles.", group = "manage", act = "shell_panel", arg = { name = "npc_names" } },
    { id = "npc_healthbar", label = "Healthbars", icon = "check", tip = "Toggle overhead healthbars on NPCs.", group = "manage", act = "npc_healthbar" },
    { id = "npc_schedule", label = "Schedule", icon = "repfirst", tip = "Day/night schedules.", group = "brain", act = "shell_panel", arg = { name = "npc_schedule" } },
    { id = "npc_emote", label = "Emote", icon = "play", tip = "Play emote on NPC.", group = "dialog", act = "shell_panel", arg = { name = "npc_emote" } },
    { id = "npc_voice", label = "Voice", icon = "chat", tip = "NPC voice/barks.", group = "dialog", act = "shell_panel", arg = { name = "npc_voice" } },
    { id = "npc_mount", label = "Mount", icon = "share", tip = "Mount/vehicle attach.", group = "combat", act = "shell_panel", arg = { name = "npc_mount" } },
  } }
T[#T + 1] = { id = "AI", label = "AI", icon = "ai",
  groups = { { id = "director", label = "Director" }, { id = "nav", label = "Nav" },
    { id = "perception", label = "Perception" }, { id = "learning", label = "Learning" }, { id = "tools", label = "Tools" } },
  commands = {
    { id = "ai_enable", label = "Enable AI", icon = "check", tip = "Enable global AI director.", group = "director", act = "ai_enable" },
    { id = "ai_disable", label = "Disable AI", icon = "close", tip = "Disable global AI.", group = "director", act = "ai_disable" },
    { id = "ai_tickrate", label = "Tick Rate", icon = "data", tip = "AI think rate (Hz).", group = "director", act = "shell_panel", arg = { name = "ai_tick" } },
    { id = "ai_budget", label = "Budget", icon = "data", tip = "ms budget per tick.", group = "director", act = "shell_panel", arg = { name = "ai_tick" } },
    { id = "ai_difficulty", label = "Difficulty", icon = "scaleI", tip = "Global AI difficulty scalar.", group = "director", act = "shell_panel", arg = { name = "ai_difficulty" } },
    { id = "ai_spawner", label = "Spawner", icon = "plus", tip = "AI spawner volumes.", group = "director", act = "shell_panel", arg = { name = "ai_spawner" } },
    { id = "ai_waves", label = "Waves", icon = "rotate", tip = "Wave/combat director.", group = "director", act = "shell_panel", arg = { name = "ai_waves" } },
    { id = "ai_objectives", label = "Objectives", icon = "check", tip = "AI objective list.", group = "director", act = "shell_panel", arg = { name = "ai_objectives" } },
    { id = "ai_navmesh", label = "NavMesh", icon = "data", tip = "Pathfinding bake + visualize.", group = "nav", act = "shell_panel", arg = { name = "ai_navmesh" } },
    { id = "ai_path", label = "Find Path", icon = "share", tip = "Test path A->B with PathfindingService.", group = "nav", act = "ai_findpath" },
    { id = "ai_costs", label = "Costs", icon = "data", tip = "Material path costs.", group = "nav", act = "shell_panel", arg = { name = "ai_costs" } },
    { id = "ai_links", label = "Links", icon = "share", tip = "PathfindingLinks (jumps/ladders).", group = "nav", act = "shell_panel", arg = { name = "ai_links" } },
    { id = "ai_blockers", label = "Blockers", icon = "lock", tip = "Nav blockers volumes.", group = "nav", act = "shell_panel", arg = { name = "ai_blockers" } },
    { id = "ai_crowd", label = "Crowd", icon = "people", tip = "Crowd flow fields.", group = "nav", act = "shell_panel", arg = { name = "ai_crowd" } },
    { id = "ai_sight", label = "Sight", icon = "view", tip = "Global sight config.", group = "perception", act = "shell_panel", arg = { name = "ai_sight" } },
    { id = "ai_hearing", label = "Hearing", icon = "chat", tip = "Noise event system.", group = "perception", act = "shell_panel", arg = { name = "ai_hearing" } },
    { id = "ai_memory", label = "Memory", icon = "data", tip = "Stimulus memory decay.", group = "perception", act = "shell_panel", arg = { name = "ai_memory" } },
    { id = "ai_alert", label = "Alert Lvls", icon = "close", tip = "Alert level propagation.", group = "perception", act = "shell_panel", arg = { name = "ai_alert" } },
    { id = "ai_factions", label = "Factions", icon = "people", tip = "Faction relation editor.", group = "perception", act = "shell_panel", arg = { name = "npc_factions" } },
    { id = "ai_utility", label = "Utility AI", icon = "data", tip = "Utility scorers editor.", group = "learning", act = "shell_panel", arg = { name = "ai_utility" } },
    { id = "ai_htn", label = "Planner", icon = "data", tip = "Goal planner (honest: scripted plans).", group = "learning", act = "shell_panel", arg = { name = "ai_planner" } },
    { id = "ai_adapt", label = "Adapt", icon = "rotate", tip = "Adaptive difficulty tracker.", group = "learning", act = "shell_panel", arg = { name = "ai_adapt" } },
    { id = "ai_personality", label = "Personality", icon = "character", tip = "Trait sliders (brave/curious...).", group = "learning", act = "shell_panel", arg = { name = "ai_personality" } },
    { id = "ai_debugvis", label = "Debug Vis", icon = "view", tip = "Show AI states/paths/senses.", group = "tools", act = "settings_toggle", arg = { key = "ai_debugvis" } },
    { id = "ai_profiler", label = "AI Profiler", icon = "performance", tip = "Per-agent think cost.", group = "tools", act = "shell_panel", arg = { name = "ai_profiler" } },
    { id = "ai_log", label = "AI Log", icon = "textA", tip = "Decision log viewer.", group = "tools", act = "shell_panel", arg = { name = "ai_log" } },
    { id = "ai_audit", label = "Audit", icon = "search", tip = "AI audit: stuck agents, costs.", group = "tools", act = "ai_audit" },
    { id = "ai_export", label = "Export", icon = "share", tip = "Export AI config JSON.", group = "tools", act = "ai_export" },
    { id = "ai_import", label = "Import", icon = "open", tip = "Import AI config JSON.", group = "tools", act = "ai_import", panel = "ai_import" },
    { id = "ai_possess", label = "Possess", icon = "select", tip = "Possess agent (control it).", group = "director", act = "ai_possess" },
    { id = "ai_killall", label = "Kill Agents", icon = "close", tip = "Remove all AI agents.", group = "director", act = "ai_killall" },
    { id = "ai_pauseone", label = "Pause One", icon = "pause", tip = "Pause selected agent brain.", group = "director", act = "ai_pauseone" },
    { id = "ai_resumeone", label = "Resume One", icon = "play", tip = "Resume selected agent brain.", group = "director", act = "ai_resumeone" },
    { id = "ai_goto", label = "Send To", icon = "share", tip = "Send selected agent to cursor.", group = "nav", act = "ai_sendto" },
    { id = "ai_formations", label = "Formations", icon = "group", tip = "Squad formations.", group = "nav", act = "shell_panel", arg = { name = "ai_formations" } },
    { id = "ai_squads", label = "Squads", icon = "people", tip = "Squad manager.", group = "nav", act = "shell_panel", arg = { name = "ai_squads" } },
    { id = "ai_blackboard", label = "Blackboard", icon = "data", tip = "Shared blackboard viewer.", group = "perception", act = "shell_panel", arg = { name = "ai_blackboard" } },
    { id = "ai_stimuli", label = "Stimuli", icon = "effects", tip = "Fire test stimulus (noise/sight).", group = "perception", act = "ai_stimulus", panel = "ai_stimulus" },
    { id = "ai_limits", label = "Limits", icon = "info", tip = "Honest AI limits (server-side/pathfinding).", group = "tools", act = "shell_panel", arg = { name = "ai_limits" } },
    { id = "ai_reset", label = "Reset", icon = "rotate", tip = "Reset AI director state.", group = "tools", act = "ai_reset" },
  } }
T[#T + 1] = { id = "SCRIPTING", label = "Scripting", icon = "script",
  groups = { { id = "edit", label = "Edit" }, { id = "run", label = "Run" },
    { id = "debug", label = "Debug" }, { id = "organize", label = "Organize" }, { id = "api", label = "API" } },
  commands = {
    { id = "script_open", label = "Open", icon = "open", tip = "Open script editor for selection.", group = "edit", act = "script_open", panel = "script_editor" },
    { id = "script_new", label = "New Script", icon = "plus", tip = "New Script in ServerScriptService.", group = "edit", act = "create", arg = { class = "Script", parent = "ServerScriptService" } },
    { id = "script_newlocal", label = "New Local", icon = "plus", tip = "New LocalScript.", group = "edit", act = "create", arg = { class = "LocalScript", parent = "StarterPlayerScripts" } },
    { id = "script_newmodule", label = "New Module", icon = "plus", tip = "New ModuleScript.", group = "edit", act = "create", arg = { class = "ModuleScript", parent = "ReplicatedStorage" } },
    { id = "script_find", label = "Find", icon = "search", tip = "Find in script (honest: Source is PluginSecurity; searches stored copies).", group = "edit", act = "shell_panel", arg = { name = "script_find" } },
    { id = "script_replace", label = "Replace", icon = "rotate", tip = "Replace in stored script copies.", group = "edit", act = "shell_panel", arg = { name = "script_replace" } },
    { id = "script_format", label = "Format", icon = "textA", tip = "Format stored source.", group = "edit", act = "script_format" },
    { id = "script_snippets", label = "Snippets", icon = "dock", tip = "Code snippet library.", group = "edit", act = "shell_panel", arg = { name = "script_snippets" } },
    { id = "script_runonce", label = "Run Once", icon = "play", tip = "Execute selection/source now (sandboxed).", group = "run", act = "script_runonce" },
    { id = "script_runloop", label = "Run Loop", icon = "rotate", tip = "Run every tick until stopped.", group = "run", act = "script_runloop" },
    { id = "script_stoploop", label = "Stop Loop", icon = "close", tip = "Stop looped execution.", group = "run", act = "script_stoploop" },
    { id = "script_console", label = "Console", icon = "textA", tip = "Open Lua console.", group = "run", act = "shell_toggle", arg = { panel = "console" } },
    { id = "script_server", label = "To Server", icon = "share", tip = "Send snippet to server bridge.", group = "run", act = "script_toserver" },
    { id = "script_inject", label = "Inject", icon = "plus", tip = "Inject stored source into new Script.", group = "run", act = "script_inject" },
    { id = "script_breakpoints", label = "Breakpoints", icon = "close", tip = "Breakpoint manager.", group = "debug", act = "shell_panel", arg = { name = "breakpoints" } },
    { id = "script_watch", label = "Watch", icon = "search", tip = "Watch expressions.", group = "debug", act = "shell_panel", arg = { name = "watch" } },
    { id = "script_stack", label = "Stack", icon = "data", tip = "Error stack viewer.", group = "debug", act = "shell_panel", arg = { name = "callstack" } },
    { id = "script_profile", label = "Profile", icon = "performance", tip = "Profile function cost.", group = "debug", act = "shell_panel", arg = { name = "script_profile" } },
    { id = "script_errors", label = "Errors", icon = "close", tip = "Collected script errors.", group = "debug", act = "shell_panel", arg = { name = "error_list" } },
    { id = "script_lint", label = "Lint", icon = "check", tip = "Lint stored source (loadstring check).", group = "debug", act = "script_lint" },
    { id = "script_deps", label = "Deps", icon = "share", tip = "Require dependency graph.", group = "organize", act = "shell_panel", arg = { name = "script_deps" } },
    { id = "script_todos", label = "TODOs", icon = "textA", tip = "TODO/FIXME scanner.", group = "organize", act = "shell_panel", arg = { name = "script_todos" } },
    { id = "script_outline", label = "Outline", icon = "data", tip = "Function outline of source.", group = "organize", act = "shell_panel", arg = { name = "script_outline" } },
    { id = "script_refs", label = "Find Refs", icon = "search", tip = "Find references to selection.", group = "organize", act = "shell_panel", arg = { name = "script_refs" } },
    { id = "script_rename", label = "Rename Sym", icon = "textA", tip = "Rename symbol in stored source.", group = "organize", act = "shell_panel", arg = { name = "script_rename" } },
    { id = "script_docs", label = "API Docs", icon = "note", tip = "Roblox API reference browser (offline subset).", group = "api", act = "shell_panel", arg = { name = "script_docs" } },
    { id = "script_arkherapi", label = "Arkher API", icon = "emblem", tip = "ARKHER engine API reference.", group = "api", act = "shell_panel", arg = { name = "arkher_api" } },
    { id = "script_events", label = "Events", icon = "play", tip = "RemoteEvent/RemoteFunction manager.", group = "api", act = "shell_panel", arg = { name = "script_remotes" } },
    { id = "script_attrs", label = "Attributes", icon = "data", tip = "Attribute editor for selection.", group = "api", act = "shell_panel", arg = { name = "char_attrs" } },
    { id = "script_tags", label = "Tags", icon = "textA", tip = "CollectionService tags.", group = "api", act = "shell_panel", arg = { name = "char_tags" } },
    { id = "script_limits", label = "Limits", icon = "info", tip = "Honest scripting limits (Source/plugin security).", group = "edit", act = "shell_panel", arg = { name = "script_limits" } },
    { id = "script_history", label = "History", icon = "repfirst", tip = "Edit history per script.", group = "organize", act = "shell_panel", arg = { name = "script_history" } },
    { id = "script_diff", label = "Diff", icon = "search", tip = "Diff stored source vs injected.", group = "organize", act = "shell_panel", arg = { name = "script_diff" } },
    { id = "script_export", label = "Export", icon = "share", tip = "Export scripts JSON.", group = "organize", act = "script_export" },
    { id = "script_import", label = "Import", icon = "open", tip = "Import scripts JSON.", group = "organize", act = "script_import", panel = "script_import" },
    { id = "script_bindkey", label = "Bind Key", icon = "textA", tip = "Bind key to snippet.", group = "run", act = "shell_panel", arg = { name = "script_bindkey" } },
    { id = "script_autorun", label = "Autorun", icon = "play", tip = "Autorun snippets on Play.", group = "run", act = "shell_panel", arg = { name = "script_autorun" } },
    { id = "script_sandbox", label = "Sandbox", icon = "lock", tip = "Sandbox permissions for runs.", group = "run", act = "shell_panel", arg = { name = "script_sandbox" } },
    { id = "script_disable", label = "Enable/Dis", icon = "check", tip = "Toggle Disabled on selected Scripts.", group = "run", act = "script_disable" },
    { id = "script_clearout", label = "Clear Out", icon = "minus", tip = "Clear script output.", group = "debug", act = "logs_clear" },
  } }
T[#T + 1] = { id = "MULTIPLAYER", label = "Multiplayer", icon = "multiplayer",
  groups = { { id = "session", label = "Session" }, { id = "replicate", label = "Replicate" },
    { id = "chat", label = "Chat" }, { id = "security", label = "Security" }, { id = "test", label = "Test" } },
  commands = {
    { id = "multi_players", label = "Players", icon = "playersI", tip = "Player list + admin.", group = "session", act = "shell_panel", arg = { name = "multi_players" } },
    { id = "multi_invite", label = "Invite", icon = "plus", tip = "Invite flow (honest: link/code based).", group = "session", act = "shell_panel", arg = { name = "multi_invite" } },
    { id = "multi_kick", label = "Kick", icon = "close", tip = "Kick player (Play mode).", group = "session", act = "game_mod", arg = { op = "kick" } },
    { id = "multi_ban", label = "Ban", icon = "lock", tip = "Ban list manager.", group = "session", act = "shell_panel", arg = { name = "multi_ban" } },
    { id = "multi_teleport", label = "Teleport", icon = "share", tip = "Teleport players between places (limit noted).", group = "session", act = "shell_panel", arg = { name = "multi_teleport" } },
    { id = "multi_parties", label = "Parties", icon = "people", tip = "Party/lobby groups.", group = "session", act = "shell_panel", arg = { name = "multi_parties" } },
    { id = "multi_owner", label = "Ownership", icon = "select", tip = "Network ownership viewer.", group = "replicate", act = "shell_panel", arg = { name = "multi_owner" } },
    { id = "multi_streaming", label = "Streaming", icon = "share", tip = "Per-player streaming config.", group = "replicate", act = "shell_panel", arg = { name = "world_streaming" } },
    { id = "multi_replication", label = "Replic Info", icon = "data", tip = "What replicates where (guide).", group = "replicate", act = "shell_panel", arg = { name = "multi_replic" } },
    { id = "multi_remotes", label = "Remotes", icon = "play", tip = "Remote traffic monitor.", group = "replicate", act = "shell_panel", arg = { name = "multi_remotes" } },
    { id = "multi_bandwidth", label = "Bandwidth", icon = "data", tip = "Bandwidth estimator.", group = "replicate", act = "shell_panel", arg = { name = "net_stats" } },
    { id = "multi_chatsetup", label = "Chat Setup", icon = "chat", tip = "Chat channels + bubbles.", group = "chat", act = "shell_panel", arg = { name = "multi_chat" } },
    { id = "multi_mute", label = "Mute", icon = "close", tip = "Mute player chat.", group = "chat", act = "multi_mute" },
    { id = "multi_announce", label = "Announce", icon = "chat", tip = "Broadcast announcement.", group = "chat", act = "multi_announce", panel = "multi_announce" },
    { id = "multi_filter", label = "Filter", icon = "check", tip = "Text filter test (FilterStringAsync).", group = "chat", act = "shell_panel", arg = { name = "multi_filter" } },
    { id = "multi_anticheat", label = "AntiCheat", icon = "lock", tip = "Server checks: speed/teleport/fly.", group = "security", act = "shell_panel", arg = { name = "multi_anticheat" } },
    { id = "multi_validate", label = "Validate", icon = "check", tip = "Remote payload validators.", group = "security", act = "shell_panel", arg = { name = "multi_validate" } },
    { id = "multi_ratelimit", label = "Rate Limit", icon = "data", tip = "Remote rate limits.", group = "security", act = "shell_panel", arg = { name = "multi_ratelimit" } },
    { id = "multi_exploitlog", label = "Exploit Log", icon = "textA", tip = "Flagged behavior log.", group = "security", act = "shell_panel", arg = { name = "multi_exploitlog" } },
    { id = "multi_bots", label = "Test Bots", icon = "multiplayer", tip = "Spawn simulated clients.", group = "test", act = "test_bots", panel = "test_bots" },
    { id = "multi_latency", label = "Latency", icon = "data", tip = "Latency simulator.", group = "test", act = "shell_panel", arg = { name = "net_latency" } },
    { id = "multi_netgraph", label = "Net Graph", icon = "data", tip = "Live bandwidth graph.", group = "test", act = "shell_panel", arg = { name = "net_graph" } },
    { id = "multi_stress", label = "Stress", icon = "performance", tip = "Stress test: N bots + traffic.", group = "test", act = "multi_stress", panel = "multi_stress" },
    { id = "multi_desync", label = "Desync?", icon = "search", tip = "Desync detector (sim vs state).", group = "test", act = "multi_desync" },
    { id = "multi_roles", label = "Roles", icon = "people", tip = "Admin/mod roles.", group = "session", act = "shell_panel", arg = { name = "multi_roles" } },
    { id = "multi_votekick", label = "Vote Kick", icon = "check", tip = "Vote-kick setup.", group = "session", act = "shell_panel", arg = { name = "multi_votekick" } },
    { id = "multi_spectate", label = "Spectate", icon = "view", tip = "Spectate player.", group = "session", act = "game_mod", arg = { op = "spectate" } },
    { id = "multi_follow", label = "Follow", icon = "share", tip = "Follow player camera.", group = "session", act = "game_mod", arg = { op = "follow" } },
    { id = "multi_private", label = "Private Svr", icon = "lock", tip = "Reserved server flow (limit noted).", group = "session", act = "shell_panel", arg = { name = "multi_private" } },
    { id = "multi_cross", label = "Cross-Svr", icon = "share", tip = "MessagingService channels.", group = "replicate", act = "shell_panel", arg = { name = "multi_cross" } },
    { id = "multi_memory", label = "MemoryStore", icon = "data", tip = "MemoryStore queues/maps.", group = "replicate", act = "shell_panel", arg = { name = "multi_memory" } },
    { id = "multi_datastores", label = "DataStores", icon = "save", tip = "DataStore browser/manager.", group = "replicate", act = "shell_panel", arg = { name = "multi_datastores" } },
    { id = "multi_emotesync", label = "Emote Sync", icon = "play", tip = "Synced emote triggers.", group = "chat", act = "shell_panel", arg = { name = "multi_emotesync" } },
    { id = "multi_nametags", label = "Nametags", icon = "textA", tip = "Overhead nametag config.", group = "chat", act = "shell_panel", arg = { name = "multi_nametags" } },
    { id = "multi_limits", label = "Limits", icon = "info", tip = "Honest multiplayer limits.", group = "test", act = "shell_panel", arg = { name = "multi_limits" } },
    { id = "multi_audit", label = "Audit Net", icon = "search", tip = "Network audit.", group = "test", act = "multi_audit" },
    { id = "multi_savecfg", label = "Save Config", icon = "save", tip = "Save net config.", group = "test", act = "multi_savecfg" },
    { id = "multi_loadcfg", label = "Load Config", icon = "open", tip = "Load net config.", group = "test", act = "multi_loadcfg", panel = "multi_loadcfg" },
    { id = "multi_ping", label = "Ping", icon = "data", tip = "Ping test to server bridge.", group = "test", act = "multi_ping" },
    { id = "multi_reset", label = "Reset Net", icon = "rotate", tip = "Reset net sim state.", group = "test", act = "multi_reset" },
  } }
T[#T + 1] = { id = "PERFORMANCE", label = "Performance", icon = "performance",
  groups = { { id = "monitor", label = "Monitor" }, { id = "memory", label = "Memory" },
    { id = "optimize", label = "Optimize" }, { id = "budget", label = "Budget" }, { id = "report", label = "Report" } },
  commands = {
    { id = "perf_fps", label = "FPS", icon = "data", tip = "FPS meter (real).", group = "monitor", act = "perf_fps" },
    { id = "perf_frame", label = "Frame", icon = "data", tip = "Frame time breakdown.", group = "monitor", act = "shell_panel", arg = { name = "perf_frame" } },
    { id = "perf_drawcalls", label = "Drawcalls", icon = "data", tip = "Drawcall/triangle stats (real).", group = "monitor", act = "shell_panel", arg = { name = "perf_draw" } },
    { id = "perf_physics", label = "Physics", icon = "physics", tip = "Physics step/contacts stats.", group = "monitor", act = "shell_panel", arg = { name = "perf_phys" } },
    { id = "perf_network", label = "Network", icon = "data", tip = "Bandwidth stats (real).", group = "monitor", act = "shell_panel", arg = { name = "net_stats" } },
    { id = "perf_scripts", label = "Scripts", icon = "script", tip = "Script activity rates.", group = "monitor", act = "shell_panel", arg = { name = "script_activity" } },
    { id = "perf_memnow", label = "Memory Now", icon = "data", tip = "Current memory readout.", group = "memory", act = "perf_quick" },
    { id = "perf_membreak", label = "Breakdown", icon = "data", tip = "Memory breakdown panel.", group = "memory", act = "shell_panel", arg = { name = "perf_memory" } },
    { id = "perf_gc", label = "GC", icon = "rotate", tip = "GC stats + collect now.", group = "memory", act = "perf_gc" },
    { id = "perf_leaks", label = "Leaks", icon = "search", tip = "Leak detector (growth watch).", group = "memory", act = "shell_panel", arg = { name = "perf_leaks" } },
    { id = "perf_textures", label = "Textures", icon = "plus", tip = "Texture memory estimate.", group = "memory", act = "shell_panel", arg = { name = "perf_textures" } },
    { id = "perf_meshes", label = "Meshes", icon = "model", tip = "Mesh memory estimate.", group = "memory", act = "shell_panel", arg = { name = "perf_meshes" } },
    { id = "perf_cull", label = "Culling", icon = "view", tip = "Cull volumes + distances.", group = "optimize", act = "shell_panel", arg = { name = "world_culling" } },
    { id = "perf_lod", label = "LOD", icon = "data", tip = "LOD groups manager.", group = "optimize", act = "shell_panel", arg = { name = "world_lod" } },
    { id = "perf_merge", label = "Merge", icon = "group", tip = "Merge static parts (union/anchor).", group = "optimize", act = "perf_merge", panel = "perf_merge" },
    { id = "perf_streaming", label = "Streaming", icon = "share", tip = "Streaming config.", group = "optimize", act = "shell_panel", arg = { name = "world_streaming" } },
    { id = "perf_particles", label = "Particles", icon = "particles", tip = "Emitter budget enforcement.", group = "optimize", act = "shell_panel", arg = { name = "perf_particles" } },
    { id = "perf_lights", label = "Lights", icon = "bulb", tip = "Light budget enforcement.", group = "optimize", act = "shell_panel", arg = { name = "perf_lights" } },
    { id = "perf_budgetset", label = "Set Budget", icon = "data", tip = "FPS/memory/part budgets.", group = "budget", act = "shell_panel", arg = { name = "perf_budget" } },
    { id = "perf_alerts", label = "Alerts", icon = "close", tip = "Budget breach alerts.", group = "budget", act = "shell_panel", arg = { name = "perf_alerts" } },
    { id = "perf_autotune", label = "AutoTune", icon = "rotate", tip = "Auto quality scaler.", group = "budget", act = "shell_panel", arg = { name = "perf_autotune" } },
    { id = "perf_quality", label = "Quality", icon = "scaleI", tip = "Quality level override.", group = "budget", act = "shell_panel", arg = { name = "perf_quality" } },
    { id = "perf_snapshot", label = "Snapshot", icon = "camera", tip = "Capture perf snapshot.", group = "report", act = "perf_snapshot" },
    { id = "perf_compare", label = "Compare", icon = "search", tip = "Compare two snapshots.", group = "report", act = "shell_panel", arg = { name = "perf_compare" } },
    { id = "perf_export", label = "Export", icon = "share", tip = "Export perf report JSON.", group = "report", act = "perf_export" },
    { id = "perf_audit", label = "Full Audit", icon = "search", tip = "Full performance audit.", group = "report", act = "perf_audit" },
    { id = "perf_device", label = "Device", icon = "playersI", tip = "Device class detection + tips.", group = "report", act = "shell_panel", arg = { name = "perf_device" } },
    { id = "perf_record", label = "Record", icon = "close", tip = "Record perf timeline.", group = "monitor", act = "perf_record" },
    { id = "perf_stoprec", label = "Stop Rec", icon = "pause", tip = "Stop perf recording.", group = "monitor", act = "perf_stoprec" },
    { id = "perf_microprof", label = "MicroProf", icon = "data", tip = "MicroProfiler labels guide (honest).", group = "monitor", act = "shell_panel", arg = { name = "perf_micro" } },
    { id = "perf_streammem", label = "Stream Mem", icon = "data", tip = "Streaming memory stats.", group = "memory", act = "shell_panel", arg = { name = "perf_streammem" } },
    { id = "perf_animcost", label = "Anim Cost", icon = "keyframe", tip = "Animation cost estimate.", group = "memory", act = "shell_panel", arg = { name = "perf_animcost" } },
    { id = "perf_physcost", label = "Phys Cost", icon = "physics", tip = "Physics cost estimate.", group = "optimize", act = "shell_panel", arg = { name = "perf_physcost" } },
    { id = "perf_shadows", label = "Shadows", icon = "bulb", tip = "Shadow cost controls.", group = "optimize", act = "shell_panel", arg = { name = "perf_shadows" } },
    { id = "perf_fxscale", label = "FX Scale", icon = "effects", tip = "Global FX quality scale.", group = "optimize", act = "shell_panel", arg = { name = "perf_fxscale" } },
    { id = "perf_audio", label = "Audio Cost", icon = "note", tip = "Active voice count + caps.", group = "optimize", act = "shell_panel", arg = { name = "perf_audio" } },
    { id = "perf_gc2", label = "GC Graph", icon = "data", tip = "GC pressure graph.", group = "memory", act = "shell_panel", arg = { name = "perf_gcgraph" } },
    { id = "perf_regress", label = "Regressions", icon = "search", tip = "Detect perf regressions vs baseline.", group = "report", act = "shell_panel", arg = { name = "perf_regress" } },
    { id = "perf_baseline", label = "Baseline", icon = "save", tip = "Save current as baseline.", group = "report", act = "perf_baseline" },
    { id = "perf_limits", label = "Limits", icon = "info", tip = "Honest perf API limits (GPU stats etc).", group = "report", act = "shell_panel", arg = { name = "perf_limits" } },
  } }
return T
