-- Testa o motor do Terrain Editor R10 (pinceis voxel reais, undo, layers, gen, hidro).
dofile("studio-completo/tools/mock.lua")

local RS = game:GetService("ReplicatedStorage")
local src = io.open("studio-completo/scripts/server.lua"):read("*a")
local fn, serr = loadstring(src, "[server]")
assert(fn, "sintaxe do server: " .. tostring(serr))
local ok, rerr = pcall(fn)
assert(ok, "execucao do server falhou: " .. tostring(rerr))

local bridge = RS:FindFirstChild("ArkherStudioBridge")
local request = bridge:FindFirstChild("Request")
local testPlayer = game:GetService("Players"):FindFirstChild("WhiteXz73_Developer")
local function invoke(action, payload)
	return rawget(request, "__props").OnServerInvoke(testPlayer, action, payload or {})
end
local pass, fail = 0, 0
local function check(cond, msg)
	if cond then pass = pass + 1 print("  OK  " .. msg)
	else fail = fail + 1 print("  FALHOU  " .. msg) end
end

local ws = game:GetService("Workspace")
local ter = Instance.new("Terrain")
ter.Name = "Terrain"
ter.Parent = ws
local function cellAt(cx, cy, cz)
	local r = Region3.new(Vector3.new(cx * 4, cy * 4, cz * 4), Vector3.new(cx * 4 + 4, cy * 4 + 4, cz * 4 + 4))
	local m, o = ter:ReadVoxels(r, 4)
	return m[1][1][1].Name, o[1][1][1]
end
local function occSum(r)
	local _, o = ter:ReadVoxels(r, 4)
	local s = o.Size
	local sum = 0
	for x = 1, s.X do for y = 1, s.Y do for z = 1, s.Z do sum = sum + o[x][y][z] end end end
	return sum
end

print("\n== Terrain R10: undo vazio honesto ==")
local ue = invoke("TerrainUndo", {})
check(ue and ue.error and ue.error:find("desfazer") ~= nil, "Undo vazio: erro honesto")
local re = invoke("TerrainRedo", {})
check(re and re.error and re.error:find("refazer") ~= nil, "Redo vazio: erro honesto")

print("\n== Terrain R10: draw/sculpt/raise/lower ==")
local d1 = invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 0 }, radius = 8, strength = 1, material = "Rock" })
check(d1 and d1.touched > 20 and d1.dabs == 1, "draw toca voxels (" .. tostring(d1 and d1.touched) .. ")")
local m0, o0 = cellAt(0, 4, 0)
check(m0 == "Rock" and o0 == 1, "draw preenche centro com Rock (mat=" .. m0 .. " occ=" .. o0 .. ")")
local d2 = invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 0 }, radius = 8, strength = 1, material = "Sand" })
local m0b = cellAt(0, 4, 0)
check(m0b == "Rock", "draw NAO repinta solido (honesto: pintar = paint)")
local cellsBefore = ter:CountCells()
invoke("TerrainStroke", { tool = "sculpt", center = { x = 0, y = 20, z = 0 }, radius = 8, strength = 1 })
local _, oS = cellAt(0, 4, 0)
check(oS == 0 and ter:CountCells() < cellsBefore, "sculpt escava centro (occ=0)")
invoke("TerrainStroke", { tool = "raise", center = { x = 60, y = 20, z = 0 }, radius = 8, strength = 0.5, material = "Grass" })
local _, oR = cellAt(15, 4, 0)
check(math.abs(oR - 0.25) < 0.01, "raise gradual: centro occ=0.25 (" .. oR .. ")")
invoke("TerrainStroke", { tool = "draw", center = { x = 80, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass" })
invoke("TerrainStroke", { tool = "lower", center = { x = 80, y = 20, z = 0 }, radius = 8, strength = 0.5 })
local _, oL = cellAt(20, 4, 0)
check(math.abs(oL - 0.75) < 0.01, "lower gradual: centro occ=0.75 (" .. oL .. ")")

print("\n== Terrain R10: flatten/smooth/erode/crater ==")
invoke("TerrainStroke", { tool = "draw", center = { x = 400, y = 20, z = 0 }, radius = 8, strength = 1, material = "Ground" })
invoke("TerrainStroke", { tool = "flatten", center = { x = 400, y = 20, z = 0 }, radius = 16, strength = 1, planeY = 20, material = "Ground" })
local _, oB = cellAt(100, 3, 0)
local _, oA = cellAt(100, 6, 0)
check(oB == 1 and oA == 0, "flatten nivela no plano (abaixo=1 acima=0)")
ter:FillRegion(Region3.new(Vector3.new(200, 0, -16), Vector3.new(232, 4, 16)), 4, Enum.Material.Grass)
invoke("TerrainStroke", { tool = "sculpt", center = { x = 216, y = 2, z = 0 }, radius = 6, strength = 1 })
local _, oH = cellAt(54, 0, 0)
check(oH == 0, "buraco de 1 celula p/ teste do smooth")
invoke("TerrainStroke", { tool = "smooth", center = { x = 216, y = 2, z = 0 }, radius = 8, strength = 1 })
local _, oH2 = cellAt(54, 0, 0)
check(oH2 > 0.1, "smooth puxa buraco p/ media dos vizinhos (0 -> " .. string.format("%.2f", oH2) .. ")")
invoke("TerrainStroke", { tool = "draw", center = { x = 300, y = 20, z = 0 }, radius = 8, strength = 1, material = "Rock" })
invoke("TerrainStroke", { tool = "erode", center = { x = 300, y = 20, z = 0 }, radius = 8, strength = 1, seed = 3 })
local _, oE = cellAt(75, 4, 0)
check(oE < 1, "erode corroi centro (occ=" .. string.format("%.2f", oE) .. ")")
ter:FillRegion(Region3.new(Vector3.new(104, 0, -32), Vector3.new(136, 4, 32)), 4, Enum.Material.Grass)
invoke("TerrainStroke", { tool = "crater", center = { x = 120, y = 4, z = 0 }, radius = 16, strength = 1, material = "Rock" })
local _, oC = cellAt(30, 0, 0)
local _, oRim = cellAt(33, 1, 0)
check(oC == 0 and oRim > 0.2, "cratera: centro escavado + borda levantada (rim=" .. string.format("%.2f", oRim) .. ")")

print("\n== Terrain R10: paint/replace/water/drain ==")
invoke("TerrainStroke", { tool = "draw", center = { x = 500, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass" })
invoke("TerrainStroke", { tool = "paint", center = { x = 500, y = 20, z = 0 }, radius = 8, strength = 1, material = "Brick" })
local mP, oP = cellAt(125, 4, 0)
check(mP == "Brick" and oP == 1, "paint troca material sem mexer occupancy")
local cAir = ter:CountCells()
invoke("TerrainStroke", { tool = "paint", center = { x = 900, y = 60, z = 0 }, radius = 8, strength = 1, material = "Brick" })
check(ter:CountCells() == cAir, "paint no ar nao cria nada (honesto)")
invoke("TerrainStroke", { tool = "replace", center = { x = 500, y = 20, z = 0 }, radius = 8, strength = 1, material = "Sand", source = "Brick" })
check(cellAt(125, 4, 0) == "Sand", "replace fonte->alvo no pincel")
invoke("TerrainStroke", { tool = "draw", center = { x = 520, y = 20, z = 0 }, radius = 6, strength = 1, material = "Grass" })
invoke("TerrainStroke", { tool = "replace", center = { x = 520, y = 20, z = 0 }, radius = 6, strength = 1, material = "Sand", source = "Rock" })
check(cellAt(130, 4, 0) == "Grass", "replace respeita source (nao achou Rock, manteve Grass)")
invoke("TerrainStroke", { tool = "water", center = { x = 540, y = 20, z = 0 }, radius = 8, strength = 1 })
local mW = cellAt(135, 4, 0)
check(mW == "Water", "water preenche canal liquido (legacy le Water)")
invoke("TerrainStroke", { tool = "drain", center = { x = 540, y = 20, z = 0 }, radius = 8, strength = 1 })
check(cellAt(135, 4, 0) == "Air", "drain seca a agua")

print("\n== Terrain R10: falloff/simetria/ruido/validacao ==")
invoke("TerrainStroke", { tool = "draw", center = { x = 700, y = 20, z = 0 }, radius = 12, strength = 0.5, hardness = 0, falloff = 1, material = "Slate" })
local _, oFC = cellAt(175, 4, 0)
local _, oFE = cellAt(177, 4, 0)
check(oFC > oFE, "falloff: borda mais fraca que centro (" .. string.format("%.2f", oFC) .. ">" .. string.format("%.2f", oFE) .. ")")
invoke("TerrainStroke", { tool = "draw", center = { x = 20, y = 60, z = 0 }, radius = 8, strength = 1, material = "Ice", symmetry = "x" })
local _, oM = cellAt(-5, 14, 0)
check(oM > 0, "simetria x espelha o dab (occ=" .. oM .. ")")
ter:Clear()
local rN = Region3.new(Vector3.new(580, 0, -20), Vector3.new(620, 40, 20))
invoke("TerrainStroke", { tool = "draw", center = { x = 600, y = 20, z = 0 }, radius = 12, strength = 1, noise = 0.8, seed = 5, material = "Mud" })
local s1 = occSum(rN)
ter:Clear()
invoke("TerrainStroke", { tool = "draw", center = { x = 600, y = 20, z = 0 }, radius = 12, strength = 1, noise = 0.8, seed = 5, material = "Mud" })
check(math.abs(occSum(rN) - s1) < 1e-6, "ruido com seed e deterministico (soma=" .. string.format("%.1f", s1) .. ")")
local bad = invoke("TerrainStroke", { tool = "lasers", center = { x = 0, y = 0, z = 0 } })
check(bad and bad.error and bad.error:find("tool invalida") ~= nil, "tool invalida rejeitada")
local badM = invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 0, z = 0 }, material = "Unobtanium" })
check(badM and badM.error ~= nil, "material invalido rejeitado")
local big = invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 100, z = 0 }, radius = 500, strength = 1, material = "Grass" })
check(big and big.touched > 0, "radius gigante clamped (sem erro, sem travar)")

print("\n== Terrain R10: undo/redo de pincel ==")
ter:Clear()
invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass" })
local cDrew = ter:CountCells()
check(cDrew > 0, "draw conta celulas (" .. cDrew .. ")")
invoke("TerrainUndo", {})
check(ter:CountCells() == 0, "undo restaura snapshot (0 celulas)")
invoke("TerrainRedo", {})
check(ter:CountCells() == cDrew, "redo reaplica (" .. cDrew .. ")")
ter:Clear()
invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 0 }, radius = 32, strength = 1, material = "Grass" })
local cBig = ter:CountCells()
invoke("TerrainUndo", {})
invoke("TerrainRedo", {})
check(ter:CountCells() == cBig, "undo/redo exato em raio grande (" .. cBig .. ")")
ter:Clear()
invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass", stroke = "begin" })
invoke("TerrainStroke", { tool = "draw", center = { x = 16, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass", stroke = "dab" })
local cSt = ter:CountCells()
invoke("TerrainStroke", { tool = "draw", center = { x = 32, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass", stroke = "end" })
local cSt2 = ter:CountCells()
invoke("TerrainUndo", {})
check(ter:CountCells() == 0 and cSt2 > cSt, "stroke agrupado: 1 undo remove 3 dabs")

print("\n== Terrain R10: camadas nao-destrutivas ==")
ter:Clear()
local la = invoke("TerrainLayer", { op = "add", name = "L1", cx = 0, cz = 200, sx = 128, sz = 128 })
check(la and la.layers == 1, "layer add")
local stIn = invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 200 }, radius = 8, strength = 1, material = "Grass", layer = "L1" })
check(stIn and stIn.recorded == true, "stroke dentro da regiao entra na camada")
local stOut = invoke("TerrainStroke", { tool = "draw", center = { x = 0, y = 20, z = 0 }, radius = 8, strength = 1, material = "Grass", layer = "L1" })
check(stOut and stOut.recorded == false, "stroke fora da regiao NAO entra (honesto)")
local _, oLay = cellAt(0, 4, 50)
check(oLay == 1, "voxel da camada existe")
invoke("TerrainLayer", { op = "hide", name = "L1" })
local _, oHid = cellAt(0, 4, 50)
local _, oOut = cellAt(0, 4, 0)
check(oHid == 0 and oOut == 1, "hide restaura base sem tocar fora da regiao")
invoke("TerrainLayer", { op = "show", name = "L1" })
local _, oSho = cellAt(0, 4, 50)
check(oSho == 1, "show re-executa ops da camada")
local ov = invoke("TerrainLayer", { op = "add", name = "L2", cx = 0, cz = 200, sx = 64, sz = 64 })
check(ov and ov.error and ov.error:find("sobrepor") ~= nil, "camadas sobrepostas rejeitadas")
local ll = invoke("TerrainLayer", { op = "list" })
check(ll and #ll.layers == 1 and ll.layers[1].ops == 1, "list mostra 1 camada com 1 op")
invoke("TerrainLayer", { op = "clear", name = "L1" })
local ll2 = invoke("TerrainLayer", { op = "list" })
local _, oClr = cellAt(0, 4, 50)
check(ll2.layers[1].ops == 0 and oClr == 0, "clear zera ops e volta ao base")
invoke("TerrainLayer", { op = "remove", name = "L1" })
check(#invoke("TerrainLayer", { op = "list" }).layers == 0, "remove camada")

print("\n== Terrain R10: geracao procedural + agua ==")
ter:Clear()
local g0 = invoke("TerrainGen", { seed = 7, size = 128, height = 32, cx = 1000, cz = 0, biome = "meadow", erosion = 1 })
ter:Clear()
local g1 = invoke("TerrainGen", { seed = 7, size = 128, height = 32, cx = 1000, cz = 0, biome = "meadow", waterLevel = g0.minH + 8, erosion = 1 })
check(g1 and g1.cells > 1000 and g1.waterCells > 0, "gen meadow: " .. tostring(g1 and g1.msg))
ter:Clear()
local g2 = invoke("TerrainGen", { seed = 7, size = 128, height = 32, cx = 1000, cz = 0, biome = "meadow", waterLevel = g0.minH + 8, erosion = 1 })
check(g2.cells == g1.cells and g2.minH == g1.minH and g2.maxH == g1.maxH, "gen deterministica (seed igual = igual)")
invoke("TerrainUndo", {})
check(ter:CountCells() == 0, "gen entra no undo (1 entrada)")
local wp = invoke("TerrainWaterProps", { transparency = 0.7, color = { r = 10, g = 20, b = 30 } })
check(wp and wp.props.transparency == 0.7 and wp.props.color[1] == 10, "water props aplicadas")
local wc = invoke("TerrainWaterProps", { transparency = 5 })
check(wc.props.transparency == 1, "water props clamped")
local rn = invoke("TerrainRain", { on = true, radius = 64 })
local rig = ws:FindFirstChild("ArkherRainRig")
local em = rig and rig:FindFirstChildOfClass("ParticleEmitter")
check(rn.on == true and em and em.Rate > 0, "rain cria emissor real (rate=" .. tostring(em and em.Rate) .. ")")
invoke("TerrainRain", { on = false })
check(ws:FindFirstChild("ArkherRainRig") == nil, "rain off remove rig")
invoke("TerrainFlood", { y = 4, cx = 2000, cz = 2000, sx = 64, sz = 64 })
local hy = invoke("TerrainHydro", { cx = 2000, cz = 2000, sx = 64, sz = 64, sy = 32, y0 = -8 })
check(hy.waterCells > 0 and hy.volume == hy.waterCells * 64 and hy.maxDepth > 0, "hidro: " .. tostring(hy.msg))
local sts = invoke("TerrainStats", {})
check(sts and sts.undo >= 1 and sts.layers == 0 and sts.cells ~= nil, "stats retorna numeros reais (undo=" .. tostring(sts and sts.undo) .. ")")

print("TERRAIN R10: " .. pass .. " passaram, " .. fail .. " falharam")
if fail > 0 then os.exit(1) end
